<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,2,1,'0NS40MPAxa4=');
$cfg_Cs[2]=array(0,2,1,'sci7+cTh');
$cfg_Cs[3]=array(0,2,1,'0NS40LO1xKM=');
$cfg_Cs[4]=array(0,2,1,'w8DFrtfUxcQ=');
$cfg_Cs[5]=array(0,2,1,'uN/H5cPAxa4=');
$cfg_Cs[6]=array(0,2,1,'x+W0v8PAxa4=');
$cfg_Cs[7]=array(0,2,1,'s8nIy737vMk=');
$cfg_Cs[8]=array(0,2,1,'0OPIy1ZJUA==');
$cfg_Cs[9]=array(0,2,1,'zca89s28xqw=');
$cfg_Cs[11]=array(0,1,1,'udjT2s7Sw8c=');
$cfg_Cs[12]=array(11,1,1,'warPtc7Sw8c=');
$cfg_Cs[13]=array(11,1,1,'w+LU8Mn5w/c=');
$cfg_Cs[14]=array(11,1,1,'udjT2s7Sw8c=');
?>