{dede:field name='keywords'}日籍美女{/dede:field}
{dede:field name='description'}日籍美女冲田杏梨。{/dede:field}
{dede:field name='title'}日籍美女冲田杏梨{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/13340431J935Z-15349.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340431L34I0-23107.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340431M3KF-31551.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340431N1D10-4QZ.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340431N9B40-52315.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340431O53C0-61024.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340431P1ZF-KO5.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/13340431PW620-S326.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/13340431Q5EF-915Q.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/13340431R35130-10Z53.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/13340431S02210-112463.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/13340431SG240-12ca.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/13340431T5RZ-135938.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/13340431U33B0-14A15.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/13340431V04410-155M5.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/13340431VG4Z-1DD4.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/13340431W561Z-1I107.jpg{/dede:field}
