{dede:field name='keywords'}写真,生活,美女,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美空美女生活写真{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354240H000P-1O21.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354240H0GB0-25T7.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354240H10P10-32264.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354240H161460-43528.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354240H222410-5JV.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354240H2P550-61114.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354240H332560-N918.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354240H3IF-V3R.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354240H419250-91L5.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354240H460c0-10S18.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354240H52E30-119148.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/1354240H5UA0-122226.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/1354240H63240-13Z20.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/1354240HF4420-142c4.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/1354240HLPP-153328.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/1354240HR0Q0-164154.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c121130/1354240HW2930-1N920.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c121130/1354240H9393F-1R630.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c121130/1354240Hc5940-1c537.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c121130/1354240I030Y0-2050N.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c121130/1354240I0T2Z-214E8.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c121130/1354240I1263F-225929.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c121130/1354240I1O330-231a7.jpg{/dede:img}
{dede:img ddimg='' text='图 24'}/uploads/allimg/c121130/1354240I245310-244036.jpg{/dede:img}
{dede:img ddimg='' text='图 25'}/uploads/allimg/c121130/1354240I302a0-25Y47.jpg{/dede:img}
{dede:img ddimg='' text='图 26'}/uploads/allimg/c121130/1354240I3564Z-2632T.jpg{/dede:img}
{dede:img ddimg='' text='图 27'}/uploads/allimg/c121130/1354240I411B0-2L943.jpg{/dede:img}
{dede:img ddimg='' text='图 28'}/uploads/allimg/c121130/1354240I460450-2X2N.jpg{/dede:img}
{dede:img ddimg='' text='图 29'}/uploads/allimg/c121130/1354240I502X0-294V6.jpg{/dede:img}
{dede:img ddimg='' text='图 30'}/uploads/allimg/c121130/1354240I5532Z-302343.jpg{/dede:img}
{dede:img ddimg='' text='图 31'}/uploads/allimg/c121130/1354240I6013P-3159A.jpg{/dede:img}
{dede:img ddimg='' text='图 32'}/uploads/allimg/c121130/1354240I643160-325J6.jpg{/dede:img}
{dede:img ddimg='' text='图 33'}/uploads/allimg/c121130/1354240IE2130-334631.jpg{/dede:img}
{dede:img ddimg='' text='图 34'}/uploads/allimg/c121130/1354240IJ4130-34E58.jpg{/dede:img}
{dede:img ddimg='' text='图 35'}/uploads/allimg/c121130/1354240IOYF-3510J.jpg{/dede:img}
{dede:img ddimg='' text='图 36'}/uploads/allimg/c121130/1354240IT3M0-3613E.jpg{/dede:img}
{dede:img ddimg='' text='图 37'}/uploads/allimg/c121130/1354240IY3320-3J501.jpg{/dede:img}
{dede:img ddimg='' text='图 38'}/uploads/allimg/c121130/1354240I953940-3Qc5.jpg{/dede:img}
{dede:img ddimg='' text='图 39'}/uploads/allimg/c121130/1354240J012150-391B4.jpg{/dede:img}
{dede:img ddimg='' text='图 40'}/uploads/allimg/c121130/1354240J05E20-4040A.jpg{/dede:img}
{dede:img ddimg='' text='图 41'}/uploads/allimg/c121130/1354240J1Zb0-41PT.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/1354240H000P-1O21_lit.jpg{/dede:field}
