<?php
$z[0]=Array("field","明星美女,美女图片,美女,诱人美",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",72,116);
$z[1][4]['name']="description";
$z[2]=Array("field","龙星妍纯黑色",118,168);
$z[2][4]['name']="title";
$z[3]=Array("field","",170,209);
$z[3][4]['name']="writer";
$z[4]=Array("field","",211,250);
$z[4][4]['name']="source";
$z[5]=Array("field","",252,292);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",294,331);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2945324J50-112b1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U29453291150-123221.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U294533LV0-131421.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U29453410160-14Z28.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2945343P60-1522Z.jpg{/dede:img}",333,1018);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2945324J50-112b1_lit.jpg",1020,1110);
$z[8][4]['name']="litpic";

?>