<?php
$z[0]=Array("field","性感美女,美女私房,美女,诱人美",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",72,116);
$z[1][4]['name']="description";
$z[2]=Array("field","性感美女金美辛化身美丽空姐",118,182);
$z[2][4]['name']="title";
$z[3]=Array("field","",184,223);
$z[3][4]['name']="writer";
$z[4]=Array("field","",225,264);
$z[4][4]['name']="source";
$z[5]=Array("field","",266,306);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",308,345);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2U424Y560-244216.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2U42NKP-25B27.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2U43B0030-264148.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2U43RK30-2J193.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2U44014950-2XC0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2U4425X60-2c302.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2U4503560-305630.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U2U452IR0-31H14.jpg{/dede:img}",347,1293);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2U424Y560-244216_lit.jpg",1295,1385);
$z[8][4]['name']="litpic";

?>