<?php
$z[0]=Array("field","美女,春天,,",0,52);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",54,98);
$z[1][4]['name']="description";
$z[2]=Array("field","春天的美女",100,148);
$z[2][4]['name']="title";
$z[3]=Array("field","",150,189);
$z[3][4]['name']="writer";
$z[4]=Array("field","",191,230);
$z[4][4]['name']="source";
$z[5]=Array("field","",232,272);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",274,311);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334022Ka02Z-20b19.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334022L101530-2120H.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334022L22M20-224R0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334022L354050-236021.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334022L4O50-241927.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334022L595c0-2532M.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334022LH1Q0-2BC1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334022LTSZ-2K014.jpg{/dede:img}",313,1266);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/1334022L955440-2T239.jpg",1268,1355);
$z[8][4]['name']="litpic";

?>