<?php
$z[0]=Array("field","蝴蝶,情人,,",0,52);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",54,98);
$z[1][4]['name']="description";
$z[2]=Array("field","粉色情人蝴蝶飞，翩翩丽影入梦来",100,168);
$z[2][4]['name']="title";
$z[3]=Array("field","",170,209);
$z[3][4]['name']="writer";
$z[4]=Array("field","",211,250);
$z[4][4]['name']="source";
$z[5]=Array("field","",252,292);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",294,331);
$z[6][4]['name']="body";
$z[7]=Array("field","",333,372);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542391Y3OF-11962.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542391Z21350-2M96.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542391Za60-31317.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354239191E5Z-45954.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542391923R30-55015.jpg{/dede:img}",374,1055);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/13542391Y3OF-11962_lit.jpg",1057,1146);
$z[9][4]['name']="litpic";

?>