{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/13341205A05440-1M10.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/13341205D24Z-2L26.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/13341205G24S0-31W2.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/13341205J26320-494R.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/13341205M1U50-52N7.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/13341205P021P-DG7.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/13341205R5FP-K637.jpg{/dede:img}