{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542391S3110-3195O.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542391T092F-3213Q.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542391U03610-3360H.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542391U63K0-34S55.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542391V0X10-355540.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542391V60150-3644G.jpg{/dede:img}