{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}豹纹翘臀嫩模征服M3{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U291HFL0-241229.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U291I494150-25S09.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U291J064N0-263639.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U291JI1220-2G146.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U291K6230F-2Y4V.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U291KI51P-291345.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U291L05X0-301R3.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U291L304Q0-312123.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c131124/13U291LK5540-3229E.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c131124/13U291LS1440-331926.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c131124/13U291MW250-343K0.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c131124/13U291N11G10-353602.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c131124/13U291NAP50-3D634.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c131124/13U291NR5U0-3N4c.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c131124/13U291O1100F-3W5O.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c131124/13U291O20WP-393326.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c131124/13U291HFL0-241229_lit.jpg{/dede:field}
