{dede:field name='keywords'}小嶋阳菜写真{/dede:field}
{dede:field name='description'}身为日本人气少女组合AKB48 TEAM A成员和no3b的小嶋阳菜事业和人气可是越来越高了，除了演艺活动外，杂誌、平面写真等等更是让小嶋阳菜成为众人注目的焦点。{/dede:field}
{dede:field name='title'}小嶋阳菜泳装写真{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/13340314FK020-10GM.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340314I49410-11G10.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340314L31260-1263J.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340314NX030-134519.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340314S3D50-1443H.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340314W55160-15X43.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340314ZE10-1D209.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/13340314933V40-1M203.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133403149641020-1S0N.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/13340314c19140-1a1Q.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/13340315024M60-205137.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/1334031506233F-21Q51.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133403150c22P-221032.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/13340315123BZ-2342H.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133403151D2550-2494V.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133403152100910-255161.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/133403152421a0-2DQ5.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/133403152HC50-2H426.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/13340315322G20-2V293.jpg{/dede:field}
