{dede:field name='keywords'}叶玉卿{/dede:field}
{dede:field name='description'}众星学叶玉卿穿衣 绝世美人打动男人心{/dede:field}
{dede:field name='title'}众星学叶玉卿穿衣 绝世美人打动男人心{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402HVP250-12C18.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402HW62c0-131259.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402HX2KZ-142332.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402HX94140-152958.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402HY60A0-1D3D.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402HZ2MZ-1O4S.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402HZV430-1X245.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133402H9163V0-1c355.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133402H922Q50-202448.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133402H92L0P-21J12.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133402H93H5F-222940.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133402H942UP-23A40.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133402H9492J0-24T42.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133402H9555c0-2555H.jpg{/dede:field}
