<?php
$z[0]=Array("field","呂婉柔",0,47);
$z[0][4]['name']="keywords";
$z[1]=Array("field","国内嫩模吕婉柔在香港和台湾宣传2011最新写真《Love ME》，曝光的一组写真中吕婉柔真空上阵不设防，与汪小菲的火辣短信内容、手机接二连三丢失等炒作不断之下，人气已有所暴涨。",49,258);
$z[1][4]['name']="description";
$z[2]=Array("field","呂婉柔新写真集美图曝光",260,320);
$z[2][4]['name']="title";
$z[3]=Array("field","",322,361);
$z[3][4]['name']="writer";
$z[4]=Array("field","",363,402);
$z[4][4]['name']="source";
$z[5]=Array("field","",404,444);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",446,483);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/13340313VIX0-1I55.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403139123330-2F03.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334031396050F-35603.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334031400102F-44631.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403140512930-51F3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334031412Da0-C155.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403141YT30-M106.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403142O9340-V120.jpg{/dede:img}",485,1440);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133403143114a0-94002.jpg",1442,1529);
$z[8][4]['name']="litpic";

?>