{dede:field name='keywords'}美女{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}丰满迷人美女西田麻衣开心秀美胸{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334035O130410-14516.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334035O2Ba0-2A31.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334035O345A0-3N01.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334035O426060-440O.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334035O522a0-5H44.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334035O605C0-ED0.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334035OB6260-MG5.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334035OO3630-S603.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/1334035OY6420-a613.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/1334035Oc5910-101Y5.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/1334035P092N0-113L5.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/1334035P1U3Z-124959.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/1334035P2OQ0-13aR.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/1334035P3H240-146158.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/1334035P45O20-153513.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/1334035P5351Z-1CP2.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/1334035P624020-1N0Y.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/1334035PE43P-1RP8.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c120410/1334035PL51Z-195646.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c120410/1334035PR4550-201952.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c120410/1334035P914140-21LV.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c120410/1334035Q003930-22K36.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c120410/1334035Q0W530-235614.jpg{/dede:img}
{dede:img ddimg='' text='图 24'}/uploads/allimg/c120410/1334035Q1D5F-241407.jpg{/dede:img}
{dede:img ddimg='' text='图 25'}/uploads/allimg/c120410/1334035Q222530-252c0.jpg{/dede:img}
{dede:img ddimg='' text='图 26'}/uploads/allimg/c120410/1334035Q2T930-264340.jpg{/dede:img}
{dede:img ddimg='' text='图 27'}/uploads/allimg/c120410/1334035Q345Q0-2GR3.jpg{/dede:img}
{dede:img ddimg='' text='图 28'}/uploads/allimg/c120410/1334035Q41V20-2UY6.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/1334035Q50a50-2b4I.jpg{/dede:field}
