<?php
$z[0]=Array("field","车模私房大片",0,53);
$z[0][4]['name']="keywords";
$z[1]=Array("field","车模私房大片。",55,113);
$z[1][4]['name']="description";
$z[2]=Array("field","车模私房大片二",115,167);
$z[2][4]['name']="title";
$z[3]=Array("field","",169,208);
$z[3][4]['name']="writer";
$z[4]=Array("field","",210,249);
$z[4][4]['name']="source";
$z[5]=Array("field","",251,291);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",293,330);
$z[6][4]['name']="body";
$z[7]=Array("field","",332,371);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423cJ32240-249B0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423cK6260-252033.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423cLO0-264223.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423cM94310-2L531.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423cO4AP-2U1U.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423cP9DZ-296158.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423cR00130-302128.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423cS062P-31c31.jpg{/dede:img}",373,1322);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423cJ32240-249B0_lit.jpg",1324,1414);
$z[9][4]['name']="litpic";

?>