<?php
$z[0]=Array("field","日本MM桜木凛游泳池可爱写真",0,67);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供日本MM桜木凛游泳池可爱写真。",69,155);
$z[1][4]['name']="description";
$z[2]=Array("field","日本MM桜木凛游泳池可爱写真",157,221);
$z[2][4]['name']="title";
$z[3]=Array("field","",223,262);
$z[3][4]['name']="writer";
$z[4]=Array("field","",264,303);
$z[4][4]['name']="source";
$z[5]=Array("field","",305,345);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",347,384);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A24b4240-1U59.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A25011440-24O8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A25045W0-3XE.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A250Q060-43218.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A25133550-5I42.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A251D060-62Q2.jpg{/dede:img}",386,1155);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A24b4240-1U59_lit.jpg",1157,1246);
$z[8][4]['name']="litpic";

?>