{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423ZA4X0-194b2.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423ZB3D40-20Y27.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423ZC0210-21J16.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423ZCW230-223559.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423ZDK620-23W49.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423ZE31E0-2493N.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423ZF15a0-2553G.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423ZFWc0-2A952.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/135423ZGJ610-2G291.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/135423ZHE5F-2VG4.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/135423ZI5TF-296249.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/135423ZJ41060-3030D.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/135423ZK13420-319411.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/135423ZL0DF-32J36.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/135423ZLM060-333463.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/135423ZM61230-343612.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c121130/135423ZN4W20-355043.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c121130/135423ZO3160-364P5.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c121130/135423ZP01420-3OX5.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c121130/135423ZPQ5F-3W205.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c121130/135423ZQK2P-3913G.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c121130/135423ZR5W60-402635.jpg{/dede:img}