<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="600";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/c130311/13629B2D551F-3I244.jpg ",93,254);
$z[1][4]['ddimg']="/uploads/allimg/c130311/13629B2D551F-3I244.jpg";
$z[1][4]['text']="ͼ 1";
$z[1][4]['width']="460";
$z[1][4]['height']="690";
$z[2]=Array("img"," /uploads/allimg/c130311/13629B2DX60-3UE9.jpg ",256,413);
$z[2][4]['ddimg']="/uploads/allimg/c130311/13629B2DX60-3UE9.jpg";
$z[2][4]['text']="ͼ 2";
$z[2][4]['width']="533";
$z[2][4]['height']="800";
$z[3]=Array("img"," /uploads/allimg/c130311/13629B2E34340-395002.jpg ",415,580);
$z[3][4]['ddimg']="/uploads/allimg/c130311/13629B2E34340-395002.jpg";
$z[3][4]['text']="ͼ 3";
$z[3][4]['width']="440";
$z[3][4]['height']="660";

?>