{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542400626210-522N1.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542400630U30-53A61.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135424006364530-541250.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424006409440-55ZI.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424006462920-564330.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542400A21540-5K506.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/13542400AC430-5S151.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/13542400B1U0-59E18.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/13542400B54R0-6063W.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/13542400C14T0-611930.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/13542400C64260-623193.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/13542400D09510-63D37.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/13542400D62250-642042.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/13542400E312F-A35Z.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/13542400EQ910-BY47.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/13542400F35310-CHE.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c121130/13542400FQ060-D3I1.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c121130/13542400G24W0-E5031.jpg{/dede:img}