<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="150";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","http://img.qqsisi.com/allimg/111122/10-111122163400.jpg",187,284);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","http://img.qqsisi.com/allimg/111122/10-111122163404.jpg",286,383);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","http://img.qqsisi.com/allimg/111122/10-111122163407.jpg",385,482);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","http://img.qqsisi.com/allimg/111122/10-111122163412.jpg",484,581);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","http://img.qqsisi.com/allimg/111122/10-111122163415.jpg",583,680);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","http://img.qqsisi.com/allimg/111122/10-111122163419.jpg",682,779);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";
$z[8]=Array("img","http://img.qqsisi.com/allimg/111122/10-111122163421.jpg",781,878);
$z[8][4]['ddimg']="";
$z[8][4]['text']="图 7";
$z[9]=Array("img","http://img.qqsisi.com/allimg/111122/10-111122163424.jpg",880,977);
$z[9][4]['ddimg']="";
$z[9][4]['text']="图 8";

?>