{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美腿模特第373期Eva{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133404I1C6010-21a42.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133404I2014R0-222329.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133404I2305150-232a5.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133404I25WJ0-24HU.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404I2VDZ-254055.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133404I31D2P-2BS3.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133404I3430250-2NO8.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133404I3M2950-2SJ6.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133404I406210-293455.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133404I4342060-305519.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133404I1C6010-21a42_lit.jpg{/dede:field}
