{dede:field name='keywords'}韩版章子怡{/dede:field}
{dede:field name='description'}近日，在韩国《挑战！超模KOREA 2》节目中，出现一名叫做李珍妮（Lee Je-ni）的参赛者，因为她的鹅蛋脸和开朗的笑容激似大陆影星章子怡，因此被很多人称呼为韩版的章子怡。最近，一组李珍妮的性感照还在网上流传，引起网友的热议，网友更称“她比原版的章子怡{/dede:field}
{dede:field name='title'}“韩版章子怡”性感照网上流传{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133404340952960-3Rc7.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340434101L40-392Z3.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334043410K40-404310.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340434113F60-4141A.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404341205420-424544.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/1334043412C4Z-43XZ.jpg{/dede:field}
