<?php
$z[0]=Array("field","韩版章子怡",0,51);
$z[0][4]['name']="keywords";
$z[1]=Array("field","近日，在韩国《挑战！超模KOREA 2》节目中，出现一名叫做李珍妮（Lee Je-ni）的参赛者，因为她的鹅蛋脸和开朗的笑容激似大陆影星章子怡，因此被很多人称呼为韩版的章子怡。最近，一组李珍妮的性感照还在网上流传，引起网友的热议，网友更称“她比原版的章子怡",53,337);
$z[1][4]['name']="description";
$z[2]=Array("field","“韩版章子怡”性感照网上流传",339,405);
$z[2][4]['name']="title";
$z[3]=Array("field","",407,446);
$z[3][4]['name']="writer";
$z[4]=Array("field","",448,487);
$z[4][4]['name']="source";
$z[5]=Array("field","",489,529);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",531,568);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133404340952960-3Rc7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340434101L40-392Z3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334043410K40-404310.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340434113F60-4141A.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404341205420-424544.jpg{/dede:img}",570,1259);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/1334043412C4Z-43XZ.jpg",1261,1346);
$z[8][4]['name']="litpic";

?>