<?php
$z[0]=Array("field","靓丽美女",0,49);
$z[0][4]['name']="keywords";
$z[1]=Array("field","靓丽美女秀美腿",51,109);
$z[1][4]['name']="description";
$z[2]=Array("field","靓丽美女秀美腿",111,163);
$z[2][4]['name']="title";
$z[3]=Array("field","",165,204);
$z[3][4]['name']="writer";
$z[4]=Array("field","",206,245);
$z[4][4]['name']="source";
$z[5]=Array("field","",247,287);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",289,326);
$z[6][4]['name']="body";
$z[7]=Array("field","",328,367);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423b4SJ40-1a253.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423b4W00F-206312.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423b4Z9330-213560.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423b494020-22E33.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423b4a50Z-232B3.jpg{/dede:img}",369,1050);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423b4SJ40-1a253_lit.jpg",1052,1141);
$z[9][4]['name']="litpic";

?>