<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","天使诱惑",89,135);
$z[2][4]['name']="title";
$z[3]=Array("field","",137,176);
$z[3][4]['name']="writer";
$z[4]=Array("field","",178,217);
$z[4][4]['name']="source";
$z[5]=Array("field","",219,259);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",261,298);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2W962Q1F-K5Y.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2W96354D0-UV6.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2W9A430Z-93014.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2W9AOY0-105C3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2W9D01F-112515.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2W9D43Q0-12R24.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2Wa1T930-139134.jpg{/dede:img}",300,1147);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2W962Q1F-K5Y_lit.jpg",1149,1235);
$z[8][4]['name']="litpic";

?>