<?php
$z[0]=Array("field","性感美女,美女图片,高清美女,美",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",72,116);
$z[1][4]['name']="description";
$z[2]=Array("field","性感美女挑逗你的欲望",118,176);
$z[2][4]['name']="title";
$z[3]=Array("field","",178,217);
$z[3][4]['name']="writer";
$z[4]=Array("field","",219,258);
$z[4][4]['name']="source";
$z[5]=Array("field","",260,300);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",302,339);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2U30C10P-15I8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2U30EGP-24P6.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2U30M55Z-39358.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2U30O4E0-4c54.jpg{/dede:img}",341,920);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2U30C10P-15I8_lit.jpg",922,1009);
$z[8][4]['name']="litpic";

?>