{dede:field name='keywords'}日本女优次原最新写真{/dede:field}
{dede:field name='description'}提供最漂亮的日本女优次原最新写真{/dede:field}
{dede:field name='title'}日本女优次原最新写真{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/13340544Z39430-5b14.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334054491H3Z-62247.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334054492XK0-I931.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133405449413G0-X464.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133405449521450-c093.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133405449A5L0-104J3.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340544a64X0-113321.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/13340544bQ3Z-1261b.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133405450005460-134P6.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133405450110210-149506.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133405450246130-15K46.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/1334054503322P-164257.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133405450430Q0-1GM1.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/1334054505434Z-1R0Q.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/13340544Z39430-5b14_lit.jpg{/dede:field}
