<?php
$z[0]=Array("field","北电最美考生古力娜",0,59);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供北电最美考生古力娜。",61,139);
$z[1][4]['name']="description";
$z[2]=Array("field","北电最美考生古力娜",141,197);
$z[2][4]['name']="title";
$z[3]=Array("field","",199,238);
$z[3][4]['name']="writer";
$z[4]=Array("field","",240,279);
$z[4][4]['name']="source";
$z[5]=Array("field","",281,321);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",323,360);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A15c1450-131210.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A16021060-144957.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A16050640-151628.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A160Q230-1635G.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A16112640-1N439.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A16134120-1T936.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629A161QJ0-1b561.jpg{/dede:img}",362,1232);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A15c1450-131210_lit.jpg",1234,1325);
$z[8][4]['name']="litpic";

?>