{dede:field name='keywords'}琪の私人灰色空间,清纯靓丽{/dede:field}
{dede:field name='description'}美桌图片库提供琪の私人灰色空间 清纯靓丽。{/dede:field}
{dede:field name='title'}琪の私人灰色空间 清纯靓丽{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A201L120-215504.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A202033P-224615.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A2023F30-23U29.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A202B460-2462O.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A203000Z-25S34.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A20325b0-2645M.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c130311/13629A201L120-215504_lit.jpg{/dede:field}
