{dede:field name='keywords'}比基尼美女海滩写真{/dede:field}
{dede:field name='description'}美桌图片库提供比基尼美女海滩写真。{/dede:field}
{dede:field name='title'}比基尼美女海滩写真{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A1B59310-201361.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A1B94230-21T27.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A1C1P40-225335.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A1C52040-23G52.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A1CQ4P-242449.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A1D1OZ-25O17.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c130311/13629A1B59310-201361_lit.jpg{/dede:field}
