<?php
$z[0]=Array("field","妹妹懒庸的早晨，起床时美丽的窘",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供妹妹懒庸的早晨，起床时美丽的窘态。",73,165);
$z[1][4]['name']="description";
$z[2]=Array("field","妹妹懒庸的早晨，起床时美丽的窘态",167,237);
$z[2][4]['name']="title";
$z[3]=Array("field","",239,278);
$z[3][4]['name']="writer";
$z[4]=Array("field","",280,319);
$z[4][4]['name']="source";
$z[5]=Array("field","",321,361);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",363,400);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B2D551F-3I244.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B2DX60-3UE9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B2E34340-395002.jpg{/dede:img}",402,899);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629B2D551F-3I244_lit.jpg",901,990);
$z[8][4]['name']="litpic";

?>