{dede:field name='keywords'}网络,年度,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}09年度90后网络红人程琳新照{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133404263132250-421550.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334042632Y150-4391Y.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340426343X60-443V6.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334042635c160-454935.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404263O940-462431.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133404263922950-4H061.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334042640Q140-4U560.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/13340426431010-495123.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/13340426444SP-50Z95.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/1334042646262F-51U18.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133404264K4030-52W26.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133404264PH0-532610.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133404264919160-54KB.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/1334042A050960-5595R.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/1334042A1P1P-5B5T.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/1334042A26150-5K419.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/1334042A3553P-5R614.jpg{/dede:field}
