<?php
$z[0]=Array("field","蓝天绿水杉原杏璃",0,57);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的蓝天绿水杉原杏璃",59,131);
$z[1][4]['name']="description";
$z[2]=Array("field","蓝天绿水杉原杏璃",133,187);
$z[2][4]['name']="title";
$z[3]=Array("field","",189,228);
$z[3][4]['name']="writer";
$z[4]=Array("field","",230,269);
$z[4][4]['name']="source";
$z[5]=Array("field","",271,311);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",313,350);
$z[6][4]['name']="body";
$z[7]=Array("field","",352,391);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542440OFV0-261238.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542440PKH0-2J349.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542440Q63430-2X127.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542440R4b0-293333.jpg{/dede:img}",393,984);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/13542440OFV0-261238_lit.jpg",986,1076);
$z[9][4]['name']="litpic";

?>