{dede:field name='keywords'}蓝天绿水杉原杏璃{/dede:field}
{dede:field name='description'}提供最漂亮的蓝天绿水杉原杏璃{/dede:field}
{dede:field name='title'}蓝天绿水杉原杏璃{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542440OFV0-261238.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542440PKH0-2J349.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542440Q63430-2X127.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542440R4b0-293333.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/13542440OFV0-261238_lit.jpg{/dede:field}
