{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542404K530P-12092.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542404L20C0-24613.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542404LBA0-36059.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542404M1G30-4B23.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542404M94520-5R24.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542404N3250-A136.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/13542404NQ5P-I192.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/13542404O2LF-T628.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/13542404OR040-a956.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/13542404P40610-1014I.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/13542404PUC0-114T4.jpg{/dede:img}