<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="150";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","http://img.qqsisi.com/allimg/111116/10-1111161A507.jpg",187,283);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","http://img.qqsisi.com/allimg/111116/10-1111161A509.jpg",285,381);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","http://img.qqsisi.com/allimg/111116/10-1111161A511.jpg",383,479);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","http://img.qqsisi.com/allimg/111116/10-1111161A513.jpg",481,577);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","http://img.qqsisi.com/allimg/111116/10-1111161A515.jpg",579,675);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","http://img.qqsisi.com/allimg/111116/10-1111161A517.jpg",677,773);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";
$z[8]=Array("img","http://img.qqsisi.com/allimg/111116/10-1111161A519.jpg",775,871);
$z[8][4]['ddimg']="";
$z[8][4]['text']="图 7";
$z[9]=Array("img","http://img.qqsisi.com/allimg/111116/10-1111161A522.jpg",873,969);
$z[9][4]['ddimg']="";
$z[9][4]['text']="图 8";

?>