<?php
$z[0]=Array("field","大片,最新,,",0,52);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",54,98);
$z[1][4]['name']="description";
$z[2]=Array("field","景甜最新大片",100,150);
$z[2][4]['name']="title";
$z[3]=Array("field","",152,191);
$z[3][4]['name']="writer";
$z[4]=Array("field","",193,232);
$z[4][4]['name']="source";
$z[5]=Array("field","",234,274);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",276,313);
$z[6][4]['name']="body";
$z[7]=Array("field","",315,354);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354241964c150-25O24.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542419A52310-2A054.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542419B331F-2ME1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542419C230P-2W2b.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542419D0N50-294217.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542419D51c0-303500.jpg{/dede:img}",356,1131);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/1354241964c150-25O24_lit.jpg",1133,1224);
$z[9][4]['name']="litpic";

?>