{dede:field name='keywords'}自拍,气质,美的,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}超美的气质靓女小沁甜美自拍{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403H3235550-4M251.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403H332Q50-4Y533.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403H3411130-491R9.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403H3493240-501T2.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403H35P020-515H0.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403H3ALP-523J3.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403H3IM30-531415.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403H3QG10-54a95.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133403H3W9320-556333.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133403H3952150-5A635.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133403H401B30-5J206.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133403H4094E0-5R212.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133403H4164150-593053.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133403H4250540-601116.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133403H430a20-61Y07.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133403H43a2F-62T91.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/133403H44K310-632553.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/133403H4551520-642V8.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c120410/133403H462H50-A2F3.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c120410/133403H4GRZ-B4124.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c120410/133403H4N5J0-C3411.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c120410/133403H4U1260-DZ59.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c120410/133403H4Z5940-ERD.jpg{/dede:img}
{dede:img ddimg='' text='图 24'}/uploads/allimg/c120410/133403H4aG20-FA94.jpg{/dede:img}
{dede:img ddimg='' text='图 25'}/uploads/allimg/c120410/133403H5051c0-G1917.jpg{/dede:img}
{dede:img ddimg='' text='图 26'}/uploads/allimg/c120410/133403H5122I0-H61S.jpg{/dede:img}
{dede:img ddimg='' text='图 27'}/uploads/allimg/c120410/133403H51aP-IRc.jpg{/dede:img}
{dede:img ddimg='' text='图 28'}/uploads/allimg/c120410/133403H52C4Z-JKE.jpg{/dede:img}
{dede:img ddimg='' text='图 29'}/uploads/allimg/c120410/133403H535350-K1095.jpg{/dede:img}
{dede:img ddimg='' text='图 30'}/uploads/allimg/c120410/133403H3235550-4M251.jpg{/dede:img}
{dede:img ddimg='' text='图 31'}/uploads/allimg/c120410/133403H332Q50-4Y533.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133403H5431K0-L2V6.jpg{/dede:field}
