<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","中国式美丽",89,137);
$z[2][4]['name']="title";
$z[3]=Array("field","",139,178);
$z[3][4]['name']="writer";
$z[4]=Array("field","",180,219);
$z[4][4]['name']="source";
$z[5]=Array("field","",221,258);
$z[5][4]['name']="body";
$z[6]=Array("field","",260,300);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/13341205a5460-R4X.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/133412060051c0-93043.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/13341206122040-10U45.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334120614923P-11VS.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/133412061OA30-121505.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/1334120620QS0-135316.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/133412062361060-1463c.jpg{/dede:img}",302,1170);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120411/13341205a5460-R4X_lit.jpg",1172,1260);
$z[8][4]['name']="litpic";

?>