{dede:field name='keywords'}私立女学馆{/dede:field}
{dede:field name='description'}提供最漂亮的私立女学馆{/dede:field}
{dede:field name='title'}私立女学馆{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405R4Ob0-143055.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133405R49564P-155617.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133405R505W10-1645B.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133405R51G540-1L462.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133405R53IJ0-1XJ7.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133405R552350-193054.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133405R5B33F-2050P.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133405R5O4L0-212639.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133405R59E10-225320.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133405R60Q360-23V24.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133405R62023Z-243G8.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133405R6334J0-255240.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133405R64D2P-2CA3.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133405RB1HF-2K2W.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133405R4Ob0-143055_lit.jpg{/dede:field}
