<?php
$z[0]=Array("field","佐々木このみ",0,53);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的佐々木このみ",55,123);
$z[1][4]['name']="description";
$z[2]=Array("field","佐々木このみ",125,175);
$z[2][4]['name']="title";
$z[3]=Array("field","",177,216);
$z[3][4]['name']="writer";
$z[4]=Array("field","",218,257);
$z[4][4]['name']="source";
$z[5]=Array("field","",259,296);
$z[5][4]['name']="body";
$z[6]=Array("field","",298,338);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405416291620-242162.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334054164F030-253158.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340541A93Y0-2Bc7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340541C45560-2L045.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340541D92320-2T151.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340541F392Z-295a4.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340541G625P-30U39.jpg{/dede:img}",340,1210);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133405416291620-242162_lit.jpg",1212,1305);
$z[8][4]['name']="litpic";

?>