{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}时尚林晓寓{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/133412245414310-119124.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/133412245C1240-121E2.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/13341224594S50-13M33.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/133412246211430-14R02.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/1334122464Y260-151534.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/13341224C3J30-163157.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/13341224F1C50-1ME4.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/13341224HOP-1US9.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/13341224K52530-192G9.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120411/13341224N133P-201U3.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/133412245414310-119124_lit.jpg{/dede:field}
