<?php
$z[0]=Array("field","尤物,90后,性感美女,美女写真,明",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",73,117);
$z[1][4]['name']="description";
$z[2]=Array("field","90后混血尤物诗朵雅",119,175);
$z[2][4]['name']="title";
$z[3]=Array("field","",177,216);
$z[3][4]['name']="writer";
$z[4]=Array("field","",218,257);
$z[4][4]['name']="source";
$z[5]=Array("field","",259,299);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",301,338);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U29430a40P-15151.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2943144220-25E7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U29431593410-3Q20.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U29431U2630-42146.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U29432140540-535E.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U294323U360-64339.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U294324c360-N130.jpg{/dede:img}",340,1201);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U29430a40P-15151_lit.jpg",1203,1292);
$z[8][4]['name']="litpic";

?>