<?php
$z[0]=Array("field","性感美女,迷人唯美清纯美女街拍",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供性感美女 迷人唯美清纯美女街拍写真。",72,165);
$z[1][4]['name']="description";
$z[2]=Array("field","性感美女 迷人唯美清纯美女街拍写真",167,238);
$z[2][4]['name']="title";
$z[3]=Array("field","",240,279);
$z[3][4]['name']="writer";
$z[4]=Array("field","",281,320);
$z[4][4]['name']="source";
$z[5]=Array("field","",322,362);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",364,401);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B142b5F-104916.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B1433S40-1164B.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B143DN0-121363.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B143a0P-134125.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629B144193Z-143393.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629B1444B0-155M4.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629B144JE0-1B4E.jpg{/dede:img}",403,1265);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629B142b5F-104916_lit.jpg",1267,1357);
$z[8][4]['name']="litpic";

?>