<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","清迈性感诱惑",89,139);
$z[2][4]['name']="title";
$z[3]=Array("field","",141,180);
$z[3][4]['name']="writer";
$z[4]=Array("field","",182,221);
$z[4][4]['name']="source";
$z[5]=Array("field","",223,263);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",265,302);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2V15I5950-16315.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2V15L4050-2K19.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2V15c3160-35I9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2V1605OF-444K.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2V1615XF-5b26.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2V161UC0-63M8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2V1A1WZ-LM7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U2V1A510Z-W0b.jpg{/dede:img}",304,1236);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2V15I5950-16315_lit.jpg",1238,1327);
$z[8][4]['name']="litpic";

?>