{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}笑容依旧灿烂{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/133412120C43F-9E32.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334121210EC0-103R2.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/133412121445B0-1135T.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/133412121P9460-1222X.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/1334121221915P-13J54.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/1334121225U130-143A7.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/133412122b4R0-155P4.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/13341212336250-161G4.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/133412123I0K0-1J954.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/133412120C43F-9E32_lit.jpg{/dede:field}
