<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="235";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","/uploads/allimg/c131124/13U2WW300960-1520V.jpg",187,275);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","/uploads/allimg/c131124/13U2WW322560-1640c.jpg",277,365);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","/uploads/allimg/c131124/13U2WW341V0-1I5R.jpg",367,453);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","/uploads/allimg/c131124/13U2WW4HW0-1TG2.jpg",455,540);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","/uploads/allimg/c131124/13U2WW4935F-195N7.jpg",542,629);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","/uploads/allimg/c131124/13U2WW5094F-209194.jpg",631,719);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";
$z[8]=Array("img","/uploads/allimg/c131124/13U2WW542W0-213227.jpg",721,809);
$z[8][4]['ddimg']="";
$z[8][4]['text']="图 7";
$z[9]=Array("img","/uploads/allimg/c131124/13U2WWA24P-22N17.jpg",811,897);
$z[9][4]['ddimg']="";
$z[9][4]['text']="图 8";

?>