{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423b2I54F-5c457.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423b2N4120-602M7.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423b2S04P-61F02.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423b2XB10-621952.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423b2934K0-634247.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423b2aA10-644918.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423b3023520-AB59.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423b30IC0-B1I1.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/135423b311S20-C2A7.jpg{/dede:img}