{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}http://img.qqsisi.com/allimg/111116/10-1111161AA7.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}http://img.qqsisi.com/allimg/111116/10-1111161AA9.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}http://img.qqsisi.com/allimg/111116/10-1111161AF1.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}http://img.qqsisi.com/allimg/111116/10-1111161AF3.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}http://img.qqsisi.com/allimg/111116/10-1111161AF5.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}http://img.qqsisi.com/allimg/111116/10-1111161AF6.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}http://img.qqsisi.com/allimg/111116/10-1111161AF9.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}http://img.qqsisi.com/allimg/111116/10-1111161AG0.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}http://img.qqsisi.com/allimg/111116/10-1111161AG2.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}http://img.qqsisi.com/allimg/111116/10-1111161AG5.jpg{/dede:img}