{dede:field name='keywords'}日本女优幸田まお{/dede:field}
{dede:field name='description'}提供最漂亮的日本女优幸田まお{/dede:field}
{dede:field name='title'}日本女优幸田まお{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354244S5604P-444a0.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354244SD3260-452029.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354244SN3020-4C338.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354244S912W0-4LM9.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354244T019E0-4XD2.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354244T103050-4c319.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354244T1b140-502S0.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354244T295K0-511941.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354244T3c030-52H96.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354244T520210-533b3.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354244T621530-54Z14.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/1354244TG2420-552330.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/1354244TQ1430-5AQ0.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/1354244T91K30-5H0Y.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/1354244U022210-5V4P.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/1354244U1161P-59E54.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/1354244S5604P-444a0_lit.jpg{/dede:field}
