<?php
$z[0]=Array("field","超萌90后美女,甜美超猛户外写真",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供超萌90后美女 甜美超猛户外写真图片。",72,165);
$z[1][4]['name']="description";
$z[2]=Array("field","超萌90后美女 甜美超猛户外写真图片",167,238);
$z[2][4]['name']="title";
$z[3]=Array("field","",240,279);
$z[3][4]['name']="writer";
$z[4]=Array("field","",281,320);
$z[4][4]['name']="source";
$z[5]=Array("field","",322,362);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",364,401);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B1495H60-1LY5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B1500-1R550.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B15031050-196294.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B1505K40-2060D.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629B150Z5Z-21IP.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629B1512OZ-2293G.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629B151625P-23V24.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629B15192360-245306.jpg{/dede:img}",403,1355);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629B1495H60-1LY5_lit.jpg",1357,1446);
$z[8][4]['name']="litpic";

?>