{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423Z1460430-1Y096.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423Z1A550-194917.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423Z1FBF-20N19.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423Z1M3640-216307.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423Z1S64Z-22A61.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423Z1Z01F-2391c.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423Z1952220-244U5.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423Z20222Z-25Q08.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/135423Z2092260-264035.jpg{/dede:img}