{dede:field name='keywords'}蓝色风暴黒沢美怜{/dede:field}
{dede:field name='description'}提供最漂亮的蓝色风暴黒沢美怜{/dede:field}
{dede:field name='title'}蓝色风暴黒沢美怜{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334054141H340-133U7.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334054143R2Z-149514.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340541453a20-154519.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133405414F3210-1A442.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133405414W1W0-1O5Q.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334054150241P-1X929.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334054151QN0-1c5Z.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133405415339420-20LY.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133405415494C0-21C06.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133405415C0a0-223051.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133405415Q6430-23P54.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/1334054141H340-133U7_lit.jpg{/dede:field}
