<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="150";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","http://img.qqsisi.com/allimg/111121/10-111121161Z7.jpg",187,283);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","http://img.qqsisi.com/allimg/111121/10-111121161Z9.jpg",285,381);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","http://img.qqsisi.com/allimg/111121/10-111121161912.jpg",383,480);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","http://img.qqsisi.com/allimg/111121/10-111121161915.jpg",482,579);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","http://img.qqsisi.com/allimg/111121/10-111121161918.jpg",581,678);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","http://img.qqsisi.com/allimg/111121/10-111121161921.jpg",680,777);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";
$z[8]=Array("img","http://img.qqsisi.com/allimg/111121/10-111121161924.jpg",779,876);
$z[8][4]['ddimg']="";
$z[8][4]['text']="图 7";
$z[9]=Array("img","http://img.qqsisi.com/allimg/111121/10-111121161928.jpg",878,975);
$z[9][4]['ddimg']="";
$z[9][4]['text']="图 8";

?>