<?php
$z[0]=Array("field","日本美女新垣结衣",0,57);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的日本美女新垣结衣",59,131);
$z[1][4]['name']="description";
$z[2]=Array("field","日本美女新垣结衣",133,187);
$z[2][4]['name']="title";
$z[3]=Array("field","",189,228);
$z[3][4]['name']="writer";
$z[4]=Array("field","",230,269);
$z[4][4]['name']="source";
$z[5]=Array("field","",271,308);
$z[5][4]['name']="body";
$z[6]=Array("field","",310,350);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405S0422Z-4GB9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133405S0561540-4T351.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133405S0B3X0-4a051.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133405S0L1020-505958.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133405S0X6030-511408.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133405S1055260-525246.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133405S1193220-534639.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133405S1291010-541555.jpg{/dede:img}",352,1313);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133405S0422Z-4GB9_lit.jpg",1315,1403);
$z[8][4]['name']="litpic";

?>