{dede:field name='keywords'}秀色可餐，美女{/dede:field}
{dede:field name='description'}秀色可餐的养眼美女。{/dede:field}
{dede:field name='title'}秀色可餐的美女{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402J2H4D0-1N512.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402J2TC20-1XR5.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402J2959530-191P8.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402J30H160-204Z7.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402J3160430-21W37.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402J326060-22bK.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402J33Bb0-231501.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133402J34W130-243U5.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133402J35WI0-25F93.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133402J3E3L0-262961.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133402J3M5310-2Ga9.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133402J3WB20-2X307.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133402J3cQ0-2bW2.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133402J410C10-3021A.jpg{/dede:field}
