<?php
$z[0]=Array("field","性感美女,美女图片,高清美女,美",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",72,116);
$z[1][4]['name']="description";
$z[2]=Array("field","媛媛女神俏皮动人",118,172);
$z[2][4]['name']="title";
$z[3]=Array("field","",174,213);
$z[3][4]['name']="writer";
$z[4]=Array("field","",215,254);
$z[4][4]['name']="source";
$z[5]=Array("field","",256,296);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",298,335);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2W5S2420-31I40.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2W5U36320-325964.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2W5W2b30-332a1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2W5Y22040-3421L.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2W5912T50-351124.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2W59241V0-363445.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2W594VM0-3I340.jpg{/dede:img}",337,1194);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2W5S2420-31I40_lit.jpg",1196,1284);
$z[8][4]['name']="litpic";

?>