<?php
$z[0]=Array("field","日本美女，韩国美女，日韩性感美",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","每天为网友提供各类---日本高清美女，韩国性感美女，明星美女，丝袜美腿，人体艺术，明星专辑等高清图片",73,214);
$z[1][4]['name']="description";
$z[2]=Array("field","性感熟妇大尺度诱惑&nbsp&nbsp&nbsp&nbsp<script language=\"javascript\" src=\"/js/85030.js\"></script>",216,350);
$z[2][4]['name']="title";
$z[3]=Array("field","",352,391);
$z[3][4]['name']="writer";
$z[4]=Array("field","",393,432);
$z[4][4]['name']="source";
$z[5]=Array("field","",434,474);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",476,513);
$z[6][4]['name']="body";
$z[7]=Array("field","",515,554);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135425Y3PR10-343220.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135425910X5110-35O36.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354259111D420-3C110.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542591Q94440-3K353.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542591T40340-3TD7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542591VP510-392632.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/13542591Y040F-40N30.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135425919131950-414395.jpg{/dede:img}",556,1518);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135425Y3PR10-343220_lit.jpg",1520,1610);
$z[9][4]['name']="litpic";

?>