<?php
$z[0]=Array("field","性感美女,美女私房,美女,浴室诱",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",72,116);
$z[1][4]['name']="description";
$z[2]=Array("field","金美辛内衣抖出傲人双峰",118,178);
$z[2][4]['name']="title";
$z[3]=Array("field","",180,219);
$z[3][4]['name']="writer";
$z[4]=Array("field","",221,260);
$z[4][4]['name']="source";
$z[5]=Array("field","",262,302);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",304,341);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2a964451P-225613.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2a9A3QZ-235958.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2a9B415Z-246123.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2a9C1150-25RW.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2a9ED310-2A4b.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2aa05F20-2GZ3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2aa315130-2Q405.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U2aa3MI0-293K8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 9'}/uploads/allimg/c131124/13U2aa605K0-30J22.jpg{/dede:img}",343,1371);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2a964451P-225613_lit.jpg",1373,1463);
$z[8][4]['name']="litpic";

?>