{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334022O294K0-3W202.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334022O4352Z-3a008.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334022O5B430-40U57.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334022OEM50-419224.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334022ORW10-423458.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334022O950550-43WC.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334022P0PK0-4455I.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334022P20ZZ-454W7.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/1334022P3394P-4B527.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/1334022P4M210-4L957.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/1334022P602530-4Q064.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/1334022PI3520-494629.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/1334022PVC60-502460.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/1334022PcRP-515236.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/1334022Q124910-526417.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/1334022Q2642F-539392.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/1334022Q395910-54C96.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/1334022Q523a0-555O6.jpg{/dede:img}