<?php
$z[0]=Array("field","性感美女,美女图片,高清美女,美",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",72,116);
$z[1][4]['name']="description";
$z[2]=Array("field","性感王丸丸的情趣内衣诱惑",118,180);
$z[2][4]['name']="title";
$z[3]=Array("field","",182,221);
$z[3][4]['name']="writer";
$z[4]=Array("field","",223,262);
$z[4][4]['name']="source";
$z[5]=Array("field","",264,304);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",306,343);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2W4c31H0-1K5a.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2W500F030-1T494.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2W50163T0-195T8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2W5024Q40-209A1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2W504O450-21R60.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2W504c960-22Z92.jpg{/dede:img}",345,1110);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2W4c31H0-1K5a_lit.jpg",1112,1199);
$z[8][4]['name']="litpic";

?>