<?php
$z[0]=Array("field","丝丝心动",0,49);
$z[0][4]['name']="keywords";
$z[1]=Array("field","丝丝心动。",51,105);
$z[1][4]['name']="description";
$z[2]=Array("field","丝丝心动",107,153);
$z[2][4]['name']="title";
$z[3]=Array("field","",155,194);
$z[3][4]['name']="writer";
$z[4]=Array("field","",196,235);
$z[4][4]['name']="source";
$z[5]=Array("field","",237,277);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",279,316);
$z[6][4]['name']="body";
$z[7]=Array("field","",318,357);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423bM03550-16396.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423bM600F-25a8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423bN10220-34964.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423bN61F-49506.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423bO0Z30-54Z3.jpg{/dede:img}",359,1035);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423bM03550-16396_lit.jpg",1037,1127);
$z[9][4]['name']="litpic";

?>