{dede:field name='keywords'}网络,妹妹,电脑,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}黑丝爆乳电脑妹妹爆红网络{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542405K0O50-1H01.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542405KZY0-22S1.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542405L50W0-361O.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542405M10250-413C.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542405MN10-5KC.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542405N5Z-62213.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/13542405O39610-O150.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/13542405ONO0-YW7.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/13542405P403P-952B.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/13542405PZ2Z-10E56.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/13542405Q55510-112602.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/13542405R2S10-122919.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/13542405R915P-134931.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/13542405K0O50-1H01.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/13542405K0O50-1H01_lit.jpg{/dede:field}
