<?php
$z[0]=Array("field","美女自拍",0,49);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",51,95);
$z[1][4]['name']="description";
$z[2]=Array("field","小凌游艇展旁自拍",97,151);
$z[2][4]['name']="title";
$z[3]=Array("field","",153,192);
$z[3][4]['name']="writer";
$z[4]=Array("field","",194,233);
$z[4][4]['name']="source";
$z[5]=Array("field","",235,275);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",277,314);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U29262634A0-3212V.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U29262I1250-3324O.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U29262TQ60-34C41.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U29262961W0-35MM.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U29263052C0-3B645.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U29263310c0-3Lc3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U292633IO0-3TZ4.jpg{/dede:img}",316,1175);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U29262634A0-3212V_lit.jpg",1177,1267);
$z[8][4]['name']="litpic";

?>