{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403GI61420-14c09.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403GJ63Y0-153056.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403GK53550-1E317.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403GL33420-1MY8.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403GM14130-1Y263.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403GN01320-192c8.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403GNU0F-204F1.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403GO64460-213629.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133403GP43220-22GO.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133403GQ53460-234A8.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133403GR262Z-2455Q.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133403GR9C40-253914.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133403GSM450-2625X.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133403GTM4P-2J528.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133403GU61920-2SJ2.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133403GV34E0-2943H.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/133403GI61420-14c09.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/133403GJ63Y0-153056.jpg{/dede:img}