{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}午后阳光{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/13341222Q120P-215Q0.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/13341222TP40-22B01.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/13341222X41220-23RR.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/133412229192Q0-244D3.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/1334122295334F-256314.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/13341222bKS0-2AX2.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/133412230225320-2N346.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/1334122305I110-2R452.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/133412230W6340-2aN5.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120411/133412231243U0-302b7.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/13341222Q120P-215Q0_lit.jpg{/dede:field}
