{dede:field name='keywords'}宾馆写真山本梓{/dede:field}
{dede:field name='description'}提供最漂亮的宾馆写真山本梓{/dede:field}
{dede:field name='title'}宾馆写真山本梓{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405412410a0-161U.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133405412525910-21W2.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340541262V0-3W15.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133405412H33F-45S6.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133405412Ra40-51613.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340541293IZ-A327.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133405413053260-MA5.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/13340541315L10-UR5.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133405413260520-94605.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/13340541335N50-104250.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133405413464110-113D0.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/1334054135K250-12c22.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133405412410a0-161U_lit.jpg{/dede:field}
