<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","阳台上的女孩",89,139);
$z[2][4]['name']="title";
$z[3]=Array("field","",141,180);
$z[3][4]['name']="writer";
$z[4]=Array("field","",182,221);
$z[4][4]['name']="source";
$z[5]=Array("field","",223,263);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",265,302);
$z[6][4]['name']="body";
$z[7]=Array("field","",304,343);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}http://img.qqsisi.com/allimg/111116/10-1111161A159.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}http://img.qqsisi.com/allimg/111116/10-1111161A201.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}http://img.qqsisi.com/allimg/111116/10-1111161A203.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}http://img.qqsisi.com/allimg/111116/10-1111161A205.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}http://img.qqsisi.com/allimg/111116/10-1111161A207.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}http://img.qqsisi.com/allimg/111116/10-1111161A209.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}http://img.qqsisi.com/allimg/111116/10-1111161A211.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}http://img.qqsisi.com/allimg/111116/10-1111161A213.jpg{/dede:img}",345,1356);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","",1358,1397);
$z[9][4]['name']="litpic";

?>