<?php
$z[0]=Array("field","美眉,眼睛,白色,,",0,57);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",59,103);
$z[1][4]['name']="description";
$z[2]=Array("field","黑白色系的大眼睛美眉",105,163);
$z[2][4]['name']="title";
$z[3]=Array("field","",165,204);
$z[3][4]['name']="writer";
$z[4]=Array("field","",206,245);
$z[4][4]['name']="source";
$z[5]=Array("field","",247,287);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",289,326);
$z[6][4]['name']="body";
$z[7]=Array("field","",328,367);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542405B55O0-C62Z.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542405C155Z-Db25.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542405C622P-E1193.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542405D12610-F5551.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542405D62Y0-G9422.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542405B55O0-C62Z.jpg{/dede:img}",369,1140);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/13542405B55O0-C62Z_lit.jpg",1142,1231);
$z[9][4]['name']="litpic";

?>