<?php
$z[0]=Array("field","清纯美少女艾希,清纯mm可爱迷人",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供清纯美少女艾希 清纯mm可爱迷人。",72,161);
$z[1][4]['name']="description";
$z[2]=Array("field","清纯美少女艾希  清纯mm可爱迷人",163,231);
$z[2][4]['name']="title";
$z[3]=Array("field","",233,272);
$z[3][4]['name']="writer";
$z[4]=Array("field","",274,313);
$z[4][4]['name']="source";
$z[5]=Array("field","",315,355);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",357,394);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B2J3JP-4024U.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B2J3JP-4024U.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B2K001F-412E9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B2K45220-424563.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629B2KZF-43a35.jpg{/dede:img}",396,1071);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629B2J3JP-4024U_lit.jpg",1073,1161);
$z[8][4]['name']="litpic";

?>