{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334041959542P-1X951.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334041960361F-1954c.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334041960U0Z-2052a.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340419614L30-212237.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334041961XM0-221164.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334041962453Z-23DY.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133404196321H0-24F23.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334041963945Z-25ZF.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133404196453L0-264496.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/13340419A15210-2M936.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/13340419AY0Z-2Y0O.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/13340419B4J60-295G7.jpg{/dede:img}