<?php
$z[0]=Array("field","日本美女松中みなみ",0,59);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的日本美女松中みなみ",61,135);
$z[1][4]['name']="description";
$z[2]=Array("field","日本美女松中みなみ",137,193);
$z[2][4]['name']="title";
$z[3]=Array("field","",195,234);
$z[3][4]['name']="writer";
$z[4]=Array("field","",236,275);
$z[4][4]['name']="source";
$z[5]=Array("field","",277,314);
$z[5][4]['name']="body";
$z[6]=Array("field","",316,356);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/13340545K2T30-212044.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340545LU5Z-221542.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340545N00330-231H4.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340545N9EP-2494J.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340545P11W0-254646.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340545Q50110-2DL1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340545RA220-2NQ0.jpg{/dede:img}",358,1223);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/13340545K2T30-212044_lit.jpg",1225,1316);
$z[8][4]['name']="litpic";

?>