{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542405B55O0-C62Z.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542405C155Z-Db25.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542405C622P-E1193.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542405D12610-F5551.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542405D62Y0-G9422.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542405B55O0-C62Z.jpg{/dede:img}