{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A2961P-11P4.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A29A250-251U.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A29DRZ-33L5.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A2a262F-4F60.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A2a60110-54212.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A2aY2P-630B.jpg{/dede:img}