<?php
$z[0]=Array("field","台湾清纯MM果子",0,55);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供台湾清纯MM果子。",57,131);
$z[1][4]['name']="description";
$z[2]=Array("field","台湾清纯MM果子",133,185);
$z[2][4]['name']="title";
$z[3]=Array("field","",187,226);
$z[3][4]['name']="writer";
$z[4]=Array("field","",228,267);
$z[4][4]['name']="source";
$z[5]=Array("field","",269,309);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",311,348);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A330I260-1B58.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A3311J60-2K33.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A33161550-351N.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A331ZZ-491A.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A3323CF-51L1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A332T210-BJ8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629A333303F-OE9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629A333MO0-RS8.jpg{/dede:img}",350,1291);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A330I260-1B58_lit.jpg",1293,1382);
$z[8][4]['name']="litpic";

?>