<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","阳光时尚",89,135);
$z[2][4]['name']="title";
$z[3]=Array("field","",137,176);
$z[3][4]['name']="writer";
$z[4]=Array("field","",178,217);
$z[4][4]['name']="source";
$z[5]=Array("field","",219,256);
$z[5][4]['name']="body";
$z[6]=Array("field","",258,298);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334121933C430-102M3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/133412193914c0-114200.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/1334121944LV0-122228.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334121950053Z-13T11.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/13341219544b10-145B7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/13341219591I0-152625.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/1334121964BU0-1B353.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/13341219EMT0-1LX6.jpg{/dede:img}",300,1260);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120411/1334121933C430-102M3_lit.jpg",1262,1353);
$z[8][4]['name']="litpic";

?>