{dede:pagestyle maxwidth='600' pagepicnum='12' ddmaxwidth='200' row='0' col='0' value='2'/}
{dede:img ddimg='/uploads/allimg/c131124/13U2cKT3040-115H.jpg' text='ͼ 1' width='940' height='1410'} /uploads/allimg/c131124/13U2cKT3040-115H.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2cK914450-2S43.jpg' text='ͼ 2' width='940' height='1410'} /uploads/allimg/c131124/13U2cK914450-2S43.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2cK9A350-35527.jpg' text='ͼ 3' width='940' height='1410'} /uploads/allimg/c131124/13U2cK9A350-35527.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2cL11M60-4M53.jpg' text='ͼ 4' width='940' height='1410'} /uploads/allimg/c131124/13U2cL11M60-4M53.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2cL1B160-5R45.jpg' text='ͼ 5' width='940' height='1410'} /uploads/allimg/c131124/13U2cL1B160-5R45.jpg {/dede:img}
