<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="600";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/c131124/13U2cKT3040-115H.jpg ",93,251);
$z[1][4]['ddimg']="/uploads/allimg/c131124/13U2cKT3040-115H.jpg";
$z[1][4]['text']="ͼ 1";
$z[1][4]['width']="940";
$z[1][4]['height']="1410";
$z[2]=Array("img"," /uploads/allimg/c131124/13U2cK914450-2S43.jpg ",253,413);
$z[2][4]['ddimg']="/uploads/allimg/c131124/13U2cK914450-2S43.jpg";
$z[2][4]['text']="ͼ 2";
$z[2][4]['width']="940";
$z[2][4]['height']="1410";
$z[3]=Array("img"," /uploads/allimg/c131124/13U2cK9A350-35527.jpg ",415,575);
$z[3][4]['ddimg']="/uploads/allimg/c131124/13U2cK9A350-35527.jpg";
$z[3][4]['text']="ͼ 3";
$z[3][4]['width']="940";
$z[3][4]['height']="1410";
$z[4]=Array("img"," /uploads/allimg/c131124/13U2cL11M60-4M53.jpg ",577,735);
$z[4][4]['ddimg']="/uploads/allimg/c131124/13U2cL11M60-4M53.jpg";
$z[4][4]['text']="ͼ 4";
$z[4][4]['width']="940";
$z[4][4]['height']="1410";
$z[5]=Array("img"," /uploads/allimg/c131124/13U2cL1B160-5R45.jpg ",737,895);
$z[5][4]['ddimg']="/uploads/allimg/c131124/13U2cL1B160-5R45.jpg";
$z[5][4]['text']="ͼ 5";
$z[5][4]['width']="940";
$z[5][4]['height']="1410";

?>