{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403S2T1230-423X9.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403S291L40-433A2.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403S2bF20-445X2.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403S30FP-4563F.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403S3141540-4635G.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403S3213360-4N957.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403S32S060-4S208.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403S334V20-4b947.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133403S3411160-50L08.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133403S34U260-519164.jpg{/dede:img}