<?php
$z[0]=Array("field","知知美眉,私房自拍",0,58);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供知知美眉,私房自拍。",60,137);
$z[1][4]['name']="description";
$z[2]=Array("field","知知美眉,私房自拍",139,194);
$z[2][4]['name']="title";
$z[3]=Array("field","",196,235);
$z[3][4]['name']="writer";
$z[4]=Array("field","",237,276);
$z[4][4]['name']="source";
$z[5]=Array("field","",278,318);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",320,357);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A1WH130-U4Y.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A1X063F-9E06.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A1X3a40-102003.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A1XI110-11FR.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A1Y06360-124c0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A1Y3960-13BP.jpg{/dede:img}",359,1123);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A1WH130-U4Y_lit.jpg",1125,1212);
$z[8][4]['name']="litpic";

?>