<?php
$z[0]=Array("noteinfo","",0,171);
$z[0][4]['notename']="Íøµê»õÔ´ www.taoqao.com";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="regex";
$z[0][4]['refurl']="";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div class=\"news_list\">	{/dede:areastart}\r\n    {dede:areaend}<div class=\"pagenum\">{/dede:areaend}\r\n",173,661);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://fknet.cn/chanjilink.html";
$z[1][4]['regxurl']="http://www.taoqao.com/wangshangkaidian/wdhy/list_6_(*).html";
$z[1][4]['startid']="1";
$z[1][4]['endid']="27";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="0";
$z[1][4]['usemore']="0";

?>