<?php
$z[0]=Array("field","清纯大眼美女晶莹剔透",0,61);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供清纯大眼美女晶莹剔透。",63,143);
$z[1][4]['name']="description";
$z[2]=Array("field","清纯大眼美女晶莹剔透",145,203);
$z[2][4]['name']="title";
$z[3]=Array("field","",205,244);
$z[3][4]['name']="writer";
$z[4]=Array("field","",246,285);
$z[4][4]['name']="source";
$z[5]=Array("field","",287,327);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",329,366);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A30W6120-13H38.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A3092C20-145195.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A30963160-151233.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A31024M0-1E127.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A310G310-1O2S.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A31110460-1Q2H.jpg{/dede:img}",368,1143);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A30W6120-13H38_lit.jpg",1145,1235);
$z[8][4]['name']="litpic";

?>