{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424051CKP-15911.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424051I6460-29A5.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135424051N2930-34261.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424051R4210-46205.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424051VOF-5Y60.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135424051911910-C560.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424051955460-O930.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135424051cP-W013.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/13542405202aP-96129.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354240520MG0-10CI.jpg{/dede:img}