{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334043202F320-1Ta7.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133404320342110-1943F.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133404320410520-20KY.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334043204L450-21DE.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404320552E0-229293.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133404320632F-23Ic.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133404320FB20-2414S.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133404320LF20-254Z0.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133404320SDF-261031.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133404320Z9B0-2M2B.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133404320aX0-2Q623.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133404321041050-291420.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/13340432109A50-30UF.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/13340432115X10-315123.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133404321235960-324H7.jpg{/dede:img}