<?php
$z[0]=Array("field","清纯美女,甜美初夏户外甜美写真",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供清纯美女 甜美初夏户外甜美写真。",72,161);
$z[1][4]['name']="description";
$z[2]=Array("field","清纯美女 甜美初夏户外甜美写真",163,230);
$z[2][4]['name']="title";
$z[3]=Array("field","",232,271);
$z[3][4]['name']="writer";
$z[4]=Array("field","",273,312);
$z[4][4]['name']="source";
$z[5]=Array("field","",314,354);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",356,393);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B0Q0FZ-312960.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B0Q561Z-3245c.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B0R05B0-33N41.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B0R4W20-346096.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629B0RT460-35D96.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629B0S16030-361115.jpg{/dede:img}",395,1165);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629B0Q0FZ-312960_lit.jpg",1167,1256);
$z[8][4]['name']="litpic";

?>