{dede:pagestyle maxwidth='600' pagepicnum='12' ddmaxwidth='200' row='0' col='0' value='2'/}
{dede:img ddimg='/uploads/allimg/c131124/13U2UP23B20-22Z50.jpg' text='ͼ 1' width='610' height='939'} /uploads/allimg/c131124/13U2UP23B20-22Z50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2UP532330-236054.jpg' text='ͼ 2' width='610' height='939'} /uploads/allimg/c131124/13U2UP532330-236054.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2UPU0050-242640.jpg' text='ͼ 3' width='610' height='939'} /uploads/allimg/c131124/13U2UPU0050-242640.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2UP962160-25S25.jpg' text='ͼ 4' width='610' height='939'} /uploads/allimg/c131124/13U2UP962160-25S25.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2UQ122M0-2D219.jpg' text='ͼ 5' width='915' height='634'} /uploads/allimg/c131124/13U2UQ122M0-2D219.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2UQ23FF-2J1c.jpg' text='ͼ 6' width='610' height='939'} /uploads/allimg/c131124/13U2UQ23FF-2J1c.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2UQ3E5P-2SS8.jpg' text='ͼ 7' width='610' height='939'} /uploads/allimg/c131124/13U2UQ3E5P-2SS8.jpg {/dede:img}
