<?php
$z[0]=Array("field","小龙女彤彤",0,51);
$z[0][4]['name']="keywords";
$z[1]=Array("field","她，唯美而清新，气质超凡脱俗，拥有天使的面孔魔鬼的身材，是中国新生代广告模特界无与伦比的最有影响力的完美女神！传说中的网络美女--林柯彤",53,231);
$z[1][4]['name']="description";
$z[2]=Array("field","小龙女彤彤妩媚风情无法挡",233,295);
$z[2][4]['name']="title";
$z[3]=Array("field","",297,336);
$z[3][4]['name']="writer";
$z[4]=Array("field","",338,377);
$z[4][4]['name']="source";
$z[5]=Array("field","",379,419);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",421,458);
$z[6][4]['name']="body";
$z[7]=Array("field","",460,499);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354241QZB20-143Y.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354241Q95610-23F1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354241QcQF-342H.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354241R041E0-43A4.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354241R0QL0-5XR.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354241R110S0-62163.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354241R14LP-G5W.jpg{/dede:img}",501,1352);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/1354241QZB20-143Y_lit.jpg",1354,1442);
$z[9][4]['name']="litpic";

?>