<?php
$z[0]=Array("field","清纯美女,美女图片,性感美女,高",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",72,116);
$z[1][4]['name']="description";
$z[2]=Array("field","韩版风格艺术小清新",118,174);
$z[2][4]['name']="title";
$z[3]=Array("field","",176,215);
$z[3][4]['name']="writer";
$z[4]=Array("field","",217,256);
$z[4][4]['name']="source";
$z[5]=Array("field","",258,298);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",300,337);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2W409A210-H511.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2W41092120-W923.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2W411c320-b1E.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2W412c230-1061F.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2W413a140-114511.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2W41464T0-12U14.jpg{/dede:img}",339,1104);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2W409A210-H511_lit.jpg",1106,1194);
$z[8][4]['name']="litpic";

?>