<?php
$z[0]=Array("field","90后美女,性感甜美数码宝贝",0,66);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供90后美女 性感甜美数码宝贝。",68,153);
$z[1][4]['name']="description";
$z[2]=Array("field","90后美女 性感甜美数码宝贝",155,218);
$z[2][4]['name']="title";
$z[3]=Array("field","",220,259);
$z[3][4]['name']="writer";
$z[4]=Array("field","",261,300);
$z[4][4]['name']="source";
$z[5]=Array("field","",302,342);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",344,381);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B0JK0F-261E6.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B0K19310-2M514.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B0K45920-2Q315.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B0KH620-296026.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629B0K94140-3054T.jpg{/dede:img}",383,1063);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629B0JK0F-261E6_lit.jpg",1065,1153);
$z[8][4]['name']="litpic";

?>