{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135425Wb0P40-14O2.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135425X00A60-22953.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135425X03105P-31P7.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135425X0549140-455T.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135425X0M35F-5EZ.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135425X1013510-642R.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135425X12HE0-IH1.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135425X1512O0-V243.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/135425X1K33Z-9A54.jpg{/dede:img}