<?php
$z[0]=Array("field","日本女生",0,49);
$z[0][4]['name']="keywords";
$z[1]=Array("field","漂亮日本女生",51,107);
$z[1][4]['name']="description";
$z[2]=Array("field","漂亮日本女生",109,159);
$z[2][4]['name']="title";
$z[3]=Array("field","",161,200);
$z[3][4]['name']="writer";
$z[4]=Array("field","",202,241);
$z[4][4]['name']="source";
$z[5]=Array("field","",243,283);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",285,322);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402H0050G0-95927.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402H0254360-10a37.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402H0442250-112356.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402H06305P-124O9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402H0NP60-13Z40.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402H09443P-146144.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402H10X040-156440.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133402H12452F-1Ab3.jpg{/dede:img}",324,1282);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133402H1363510-1LN0.jpg",1284,1370);
$z[8][4]['name']="litpic";

?>