<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","萨萨的比基尼装",89,141);
$z[2][4]['name']="title";
$z[3]=Array("field","",143,182);
$z[3][4]['name']="writer";
$z[4]=Array("field","",184,223);
$z[4][4]['name']="source";
$z[5]=Array("field","",225,265);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",267,304);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2Z111V5F-144I2.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2Z113464P-154021.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2Z11424N0-162633.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2Z11ZH10-1L147.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2Z11a3G0-1TZ0.jpg{/dede:img}",306,981);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2Z111V5F-144I2_lit.jpg",983,1071);
$z[8][4]['name']="litpic";

?>