<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","亲纯MM自拍",89,137);
$z[2][4]['name']="title";
$z[3]=Array("field","",139,178);
$z[3][4]['name']="writer";
$z[4]=Array("field","",180,219);
$z[4][4]['name']="source";
$z[5]=Array("field","",221,261);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",263,300);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U292500E130-1424A.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2925021G40-1521P.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U29250B4L0-1A3M.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U29250Q52F-1OI1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U29250c35P-1XA9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U292513D60-1bH0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U29251502G0-202B7.jpg{/dede:img}",302,1158);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U292500E130-1424A_lit.jpg",1160,1250);
$z[8][4]['name']="litpic";

?>