{dede:field name='keywords'}美图,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}轻熟女正妹爱唱KTV美图{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403P5B22P-1H36.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403P5L3Y0-25352.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403P5U4L0-310Z.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403P59505Z-45244.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403P603010-55118.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403P611V20-63119.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403P6203Q0-I029.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403P62N930-Rb4.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133403P63CD0-912L.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133403P6450-101537.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133403PA52Q0-1143F.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133403PB40460-121O9.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133403PC3Q0-134593.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133403PD4640-1442Y.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133403PE33V0-154E4.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133403PF2T0-1E503.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/133403P5B22P-1H36.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/133403P5L3Y0-25352.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133403PG0I30-1H022.jpg{/dede:field}
