<?php
$z[0]=Array("field","身边,美女",0,50);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",52,96);
$z[1][4]['name']="description";
$z[2]=Array("field","当你不在我身边",98,150);
$z[2][4]['name']="title";
$z[3]=Array("field","",152,191);
$z[3][4]['name']="writer";
$z[4]=Array("field","",193,232);
$z[4][4]['name']="source";
$z[5]=Array("field","",234,274);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",276,313);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2V023495P-M2R.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2V023M5P-Q604.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2V0260160-96259.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2V0262G0-103133.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2V02H350-1122P.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2V02QI10-1231J.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2V030ER0-135319.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U2V03120030-146261.jpg{/dede:img}",315,1258);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2V023495P-M2R_lit.jpg",1260,1347);
$z[8][4]['name']="litpic";

?>