<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",2,79);
$z[0][4]['runphp']="yes";
$z[1]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",115,200);
$z[1][4]['runphp']="yes";
$z[2]=Array("imgsrc","",211,226);
$z[3]=Array("title","",309,324);
$z[4]=Array("imgsrc","",349,364);
$z[5]=Array("title","",389,404);
$z[6]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",413,493);
$z[6][4]['runphp']="yes";

?>