{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133404E1045250-412012.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133404E142W30-422508.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133404E1GK60-4313F.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133404E1c4Z-44c91.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404E22K910-454959.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133404E25c4Z-4641B.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133404E2Y3630-4KO5.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133404E315bF-4X002.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133404E34MM0-494V4.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133404E3L2130-502555.jpg{/dede:img}