{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334123040NY0-141N.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/133412304361440-29354.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/133412304643010-36255.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/133412305033E0-49335.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/1334123053600P-54156.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/133412305634S0-B157.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/133412305XG30-J354.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/1334123061ba0-TL6.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/1334123064C220-b523.jpg{/dede:img}