<?php
$z[0]=Array("field","内衣,浴室,写真,美女",0,60);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",62,106);
$z[1][4]['name']="description";
$z[2]=Array("field","镂空吊带性感写真",108,162);
$z[2][4]['name']="title";
$z[3]=Array("field","",164,203);
$z[3][4]['name']="writer";
$z[4]=Array("field","",205,244);
$z[4][4]['name']="source";
$z[5]=Array("field","",246,286);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",288,325);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",327,554);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","",556,595);
$z[8][4]['name']="litpic";

?>