{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334122361BW0-41E34.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/13341223633TP-429545.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/13341223A02c0-433510.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/13341223BS940-4433b.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/13341223E22Z-453940.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/13341223I394F-462918.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/13341223L40460-4IE5.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/13341223P20S0-4V103.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/13341223T22430-4b154.jpg{/dede:img}