<?php
$z[0]=Array("field","性感美女,美女私房,美女",0,63);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",65,109);
$z[1][4]['name']="description";
$z[2]=Array("field","性感女神",111,157);
$z[2][4]['name']="title";
$z[3]=Array("field","",159,198);
$z[3][4]['name']="writer";
$z[4]=Array("field","",200,239);
$z[4][4]['name']="source";
$z[5]=Array("field","",241,281);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",283,320);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2UI41T30-11b5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2UISF50-2C37.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2UJ1B4F-31335.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2UJ622P-45321.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2UJ929110-5J59.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2UK224430-A415.jpg{/dede:img}",322,1078);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2UI41T30-11b5_lit.jpg",1080,1167);
$z[8][4]['name']="litpic";

?>