<?php
$z[0]=Array("field","幽然花园",0,49);
$z[0][4]['name']="keywords";
$z[1]=Array("field","幽然花园",51,103);
$z[1][4]['name']="description";
$z[2]=Array("field","幽然花园",105,151);
$z[2][4]['name']="title";
$z[3]=Array("field","",153,192);
$z[3][4]['name']="writer";
$z[4]=Array("field","",194,233);
$z[4][4]['name']="source";
$z[5]=Array("field","",235,275);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",277,314);
$z[6][4]['name']="body";
$z[7]=Array("field","",316,355);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423c2321Y0-95a3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423c23OD0-101A8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423c243P20-1132L.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423c24W2F-12AC.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423c2531630-1313E.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423c2592P-145513.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423c264W10-159556.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423c2F4140-1B924.jpg{/dede:img}",357,1310);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423c2321Y0-95a3_lit.jpg",1312,1401);
$z[9][4]['name']="litpic";

?>