<?php
$z[0]=Array("field","风俗娘室内性感诱惑摄影,性感诱",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供风俗娘室内性感诱惑摄影 性感诱惑美女。",72,167);
$z[1][4]['name']="description";
$z[2]=Array("field","风俗娘室内性感诱惑摄影  性感诱惑美女",169,243);
$z[2][4]['name']="title";
$z[3]=Array("field","",245,284);
$z[3][4]['name']="writer";
$z[4]=Array("field","",286,325);
$z[4][4]['name']="source";
$z[5]=Array("field","",327,367);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",369,406);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B23533110-193O.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B235B640-24G5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B2359B10-36411.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B2361c60-415D.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629B2364I40-5c12.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629B23G520-A452.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629B23OM10-O309.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629B23Y910-YK6.jpg{/dede:img}",408,1353);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629B23533110-193O_lit.jpg",1355,1445);
$z[8][4]['name']="litpic";

?>