{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424064QN20-1323Z.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424064XWZ-141313.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354240649240-154N8.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354240A0364P-163c6.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354240A0YV0-1N458.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354240A14I30-1Q213.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354240A19CZ-191D4.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354240A25XF-204326.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354240A2921P-2143b.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354240A3J4F-2231c.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/135424064QN20-1323Z.jpg{/dede:img}