{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402F235330-111040.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402F2439410-123194.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402F24964Z-131340.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402F25451Z-1433B.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402F2602350-152342.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402F2A3310-163214.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402F2F4O0-1I044.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133402F2L02F-1S559.jpg{/dede:img}