{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}http://img.qqsisi.com/allimg/120109/10-120109162Q5.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}http://img.qqsisi.com/allimg/120109/10-120109162Q7.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}http://img.qqsisi.com/allimg/120109/10-120109162Q9.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}http://img.qqsisi.com/allimg/120109/10-120109162R2.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}http://img.qqsisi.com/allimg/120109/10-120109162R5.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}http://img.qqsisi.com/allimg/120109/10-120109162R8.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}http://img.qqsisi.com/allimg/120109/10-120109162S1.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}http://img.qqsisi.com/allimg/120109/10-120109162S4.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}http://img.qqsisi.com/allimg/120109/10-120109162S6.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}http://img.qqsisi.com/allimg/120109/10-120109162S9.jpg{/dede:img}