<?php
$z[0]=Array("field","女生,休闲,,",0,52);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",54,98);
$z[1][4]['name']="description";
$z[2]=Array("field","休闲女生",100,146);
$z[2][4]['name']="title";
$z[3]=Array("field","",148,187);
$z[3][4]['name']="writer";
$z[4]=Array("field","",189,228);
$z[4][4]['name']="source";
$z[5]=Array("field","",230,270);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",272,309);
$z[6][4]['name']="body";
$z[7]=Array("field","",311,350);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354240T954630-2C392.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354240U026320-2JL0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354240U091L0-2R245.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354240U1K620-2910b.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354240U219510-30P22.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354240U2N3F-313Y8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354240U34910-3243X.jpg{/dede:img}",352,1217);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/1354240T954630-2C392_lit.jpg",1219,1310);
$z[9][4]['name']="litpic";

?>