<?php
$z[0]=Array("field","花瓣,美女,美女图片,私房",0,64);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",66,110);
$z[1][4]['name']="description";
$z[2]=Array("field","花瓣沐浴",112,158);
$z[2][4]['name']="title";
$z[3]=Array("field","",160,199);
$z[3][4]['name']="writer";
$z[4]=Array("field","",201,240);
$z[4][4]['name']="source";
$z[5]=Array("field","",242,282);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",284,321);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2aZMW60-12W3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2a91001W0-23c0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2a9104SF-393K.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2a911042F-4Q32.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2a9115RP-530Z.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2a9124WP-E202.jpg{/dede:img}",323,1079);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2aZMW60-12W3_lit.jpg",1081,1167);
$z[8][4]['name']="litpic";

?>