{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423cX55U0-322648.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423cY0040-3345H.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423cY3J50-342235.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423cYT320-359526.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423cZ25060-361329.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423cZF60-3J212.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423c910c10-3UV9.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423c91523P-3b515.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/135423c91P440-404108.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/135423c921J60-41E16.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/135423c9262460-422317.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/135423c929B20-434494.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/135423c932J60-444631.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/135423c9360450-451927.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/135423c9391220-461351.jpg{/dede:img}