<?php
$z[0]=Array("field","街拍美女,90后mm长裙街拍清纯写",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供街拍美女 90后mm长裙街拍清纯写真。",72,163);
$z[1][4]['name']="description";
$z[2]=Array("field","街拍美女 90后mm长裙街拍清纯写真",165,234);
$z[2][4]['name']="title";
$z[3]=Array("field","",236,275);
$z[3][4]['name']="writer";
$z[4]=Array("field","",277,316);
$z[4][4]['name']="source";
$z[5]=Array("field","",318,358);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",360,397);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B0B42X0-196147.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B0BY2P-209556.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B0C21420-213205.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B0C53J0-2210C.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629B0CU360-236443.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629B0D12I0-242Z0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629B0D45120-2523F.jpg{/dede:img}",399,1261);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629B0B42X0-196147_lit.jpg",1263,1353);
$z[8][4]['name']="litpic";

?>