{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美腿模特第380期Miya{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133404LJ440Z-16358.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133404LN13c0-23L0.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133404LQGC0-3F12.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133404LW4ZF-4J28.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404LZKB0-52107.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133404L935J60-63041.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133404Lc63350-L4b.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133404M0406430-S248.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133404M11X0F-95348.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133404M1N2c0-104S8.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133404LJ440Z-16358_lit.jpg{/dede:field}
