<?php
$z[0]=Array("field","宋伊娜",0,47);
$z[0][4]['name']="keywords";
$z[1]=Array("field","韩国女模特宋伊娜个人写真集",49,119);
$z[1][4]['name']="description";
$z[2]=Array("field","韩国女模特宋伊娜个人写真集",121,185);
$z[2][4]['name']="title";
$z[3]=Array("field","",187,226);
$z[3][4]['name']="writer";
$z[4]=Array("field","",228,267);
$z[4][4]['name']="source";
$z[5]=Array("field","",269,309);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",311,348);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402GO50030-1TG.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402GQ444P-262T.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402GS30C0-34135.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402GTV5F-441P.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402GV3Y10-51396.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402GX40a0-61510.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402GZ13120-O940.jpg{/dede:img}",350,1203);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133402G91910Z-XR6.jpg",1205,1289);
$z[8][4]['name']="litpic";

?>