{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135425X364GZ-103J5.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135425X3Q2060-1133c.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135425X3c0540-12K11.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135425X41S260-13ZI.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135425X43P2Z-145563.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135425X4594950-156022.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135425X4LFZ-163463.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135425X4942250-1M300.jpg{/dede:img}