{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405416291620-242162.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334054164F030-253158.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340541A93Y0-2Bc7.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340541C45560-2L045.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340541D92320-2T151.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340541F392Z-295a4.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340541G625P-30U39.jpg{/dede:img}