{dede:field name='keywords'}美女吃胡萝卜求喂养{/dede:field}
{dede:field name='description'}7月28日至7月31日，第九届中国国际数码互动娱乐展览会即2011年ChinaJoy在上海拉开帷幕。展会内容丰富多彩，涵盖了包括新游戏及周边产品发布、真人Cosplay表演、高峰论坛等，已成为中国游戏娱乐产业高速发展的一大缩影。 其中最受欢迎的要数，各个展商带来的sh{/dede:field}
{dede:field name='title'}ChinaJoy美女吃胡萝卜求喂养{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/13340433H01350-1I207.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340433HQ610-1T944.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340433I9A50-1955W.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340433JJI0-203b9.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340433KES0-21K08.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340433L35060-221052.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340433M62940-2343B.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/13340433NG60-2424I.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/13340433OO1Z-251A8.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/13340433Q0W10-2625G.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/13340433R5450-2J418.jpg{/dede:field}
