<?php
$z[0]=Array("field","月色朦胧,美乳唯美人儿 清楚动人",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供月色朦胧,美乳唯美人儿 清楚动人。",73,163);
$z[1][4]['name']="description";
$z[2]=Array("field","月色朦胧,美乳唯美人儿 清楚动人",165,233);
$z[2][4]['name']="title";
$z[3]=Array("field","",235,274);
$z[3][4]['name']="writer";
$z[4]=Array("field","",276,315);
$z[4][4]['name']="source";
$z[5]=Array("field","",317,357);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",359,396);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629Ab1613Z-263507.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629Ab232b0-2J248.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629Ab3541F-2W225.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629Ab41110-292V1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629Ab4IQ0-30I42.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629Ab526360-31GB.jpg{/dede:img}",398,1165);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629Ab1613Z-263507_lit.jpg",1167,1257);
$z[8][4]['name']="litpic";

?>