{dede:field name='keywords'}蝴蝶,情人,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}粉色情人蝴蝶飞，翩翩丽影入梦来{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334022D9145P-245503.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334022E0612P-2514V.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334022E1964P-261102.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334022E326040-2L2Z.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334022E43E40-2T929.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/1334022E5602F-292I8.jpg{/dede:field}
