{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}http://img.qqsisi.com/allimg/111130/10-111130100233.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}http://img.qqsisi.com/allimg/111130/10-111130100235.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}http://img.qqsisi.com/allimg/111130/10-111130100237.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}http://img.qqsisi.com/allimg/111130/10-111130100240.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}http://img.qqsisi.com/allimg/111130/10-111130100242.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}http://img.qqsisi.com/allimg/111130/10-111130100245.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}http://img.qqsisi.com/allimg/111130/10-111130100248.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}http://img.qqsisi.com/allimg/111130/10-111130100251.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}http://img.qqsisi.com/allimg/111130/10-111130100253.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}http://img.qqsisi.com/allimg/111130/10-111130100256.jpg{/dede:img}