{dede:noteinfo notename="日韩美女" channelid="2" macthtype="string"
refurl="http://www.mypcera.com/star/mm/rihanmeinv/" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.mypcera.com/star/mm/rihanmeinv/page_(*).html"
startid="1" endid="2" addv="1" urlrule="area"
 musthas="" nothas="" listpic="0" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<li class="piclist_title"><span>日韩美女</span></li>{/dede:areastart}
    {dede:areaend}<li class="page">{/dede:areaend}
{/dede:listrule}
