<?php
$z[0]=Array("field","爱情故事,,",0,51);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",53,97);
$z[1][4]['name']="description";
$z[2]=Array("field","日系爱情故事",99,149);
$z[2][4]['name']="title";
$z[3]=Array("field","",151,190);
$z[3][4]['name']="writer";
$z[4]=Array("field","",192,231);
$z[4][4]['name']="source";
$z[5]=Array("field","",233,273);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",275,312);
$z[6][4]['name']="body";
$z[7]=Array("field","",314,353);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423912b52Z-30N18.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542391311ZP-3123C.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354239131c450-329614.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542391326260-33Sc.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354239133502F-343P8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542391345B0-354631.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423913514930-3CU3.jpg{/dede:img}",355,1224);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423912b52Z-30N18_lit.jpg",1226,1316);
$z[9][4]['name']="litpic";

?>