<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","清纯玉女甜美装扮",89,143);
$z[2][4]['name']="title";
$z[3]=Array("field","",145,184);
$z[3][4]['name']="writer";
$z[4]=Array("field","",186,225);
$z[4][4]['name']="source";
$z[5]=Array("field","",227,264);
$z[5][4]['name']="body";
$z[6]=Array("field","",266,306);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334121141961Z-12233.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334121145N160-2S02.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/133412115002030-34R0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/133412115632950-442Z.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/13341211A04310-53S8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/13341211JF930-62015.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/13341211TD560-I055.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/13341211Z95H0-V000.jpg{/dede:img}",308,1264);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120411/1334121141961Z-12233_lit.jpg",1266,1357);
$z[8][4]['name']="litpic";

?>