{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629AH1355F-162131.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629AH1P940-1I364.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629AH21Y0-1X609.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629AH249340-19CL.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629AH2T520-20M18.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629AH3263F-213915.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629AH3D0-22LK.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629AH4042F-23Q46.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c130311/13629AH435I0-244206.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c130311/13629AH4I040-253L1.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c130311/13629AH50G50-2AD8.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c130311/13629AH544S0-2K229.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c130311/13629AH5K130-2Q618.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c130311/13629AH6013F-292M2.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c130311/13629AH640510-30cY.jpg{/dede:img}