<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","MOON嘉依写真",89,139);
$z[2][4]['name']="title";
$z[3]=Array("field","",141,180);
$z[3][4]['name']="writer";
$z[4]=Array("field","",182,221);
$z[4][4]['name']="source";
$z[5]=Array("field","",223,263);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",265,302);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2cH2F140-G1b.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2cH329540-UY6.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2cH416450-b413.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2cH44K50-103K5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2cH511950-113I1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2cHAR60-123P8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2cHC1L0-13V43.jpg{/dede:img}",304,1150);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2cH2F140-G1b_lit.jpg",1152,1238);
$z[8][4]['name']="litpic";

?>