{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/133412311961E0-201D8.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/133412312232460-212140.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/13341231250R50-221S4.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/133412312J12Z-235305.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/13341231302MP-24E29.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/133412313301N0-259146.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/133412313563560-2E923.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/133412313c61P-2J333.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/1334123144Q320-2X239.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120411/133412314940530-294M9.jpg{/dede:img}