{dede:noteinfo notename="高清美女 xgmm" channelid="2" macthtype="string"
    refurl="http://" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.xgmm.cc/mm/gaoqingmeinv/list_2_(*).html"
startid="1" endid="4" addv="1" urlrule="area" musthas=""
 nothas="" listpic="0" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="main">{/dede:areastart}
    {dede:areaend}<div class="pages">{/dede:areaend}
{/dede:listrule}
