<?php
$z[0]=Array("field","董璇",0,45);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",47,91);
$z[1][4]['name']="description";
$z[2]=Array("field","董璇变身成最闪耀的足球宝贝",93,157);
$z[2][4]['name']="title";
$z[3]=Array("field","",159,198);
$z[3][4]['name']="writer";
$z[4]=Array("field","",200,239);
$z[4][4]['name']="source";
$z[5]=Array("field","",241,281);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",283,320);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403Q4260I0-5I211.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403Q4319230-5Y647.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403Q43B460-5cA4.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403Q44234P-60Q61.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403Q44X220-613555.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403Q4542Q0-62a63.jpg{/dede:img}",322,1096);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133403Q45Tc0-63Wa.jpg",1098,1182);
$z[8][4]['name']="litpic";

?>