{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/13341231I59340-30LX.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/13341231N230Z-313612.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/13341231SE250-324K9.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/13341231XD630-334202.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/133412319329A0-349418.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/13341231bL130-3512Z.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/1334123203333P-3E348.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/133412320624Q0-3G2P.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/133412320S5120-3TZ7.jpg{/dede:img}