{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135425935415630-3340V.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135425935P6150-342935.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542594245U10-359291.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135425942LC0-362K5.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354259431M20-3I056.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354259524434P-3T492.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135425952B31Z-3c549.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135425952YQP-40KY.jpg{/dede:img}