{dede:field name='keywords'}韩国美女模特秀春装{/dede:field}
{dede:field name='description'}提供最漂亮的韩国美女模特秀春装{/dede:field}
{dede:field name='title'}韩国美女模特秀春装{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424414500R0-25Y01.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354244145960P-2C960.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135424414D1240-2J133.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424414L9340-2SX0.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424414UE10-2955L.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135424414944240-303b7.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354244152W120-31MG.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354244153C3F-3232I.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/13542441545S20-332a7.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/13542441554HF-343Z1.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135424414500R0-25Y01_lit.jpg{/dede:field}
