<?php
$z[0]=Array("sppage","",0,59);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.zcool.com.cn/article/ZMTU4OTI=.html",61,142);
$z[2]=Array("keywordtrim","",144,181);
$z[3]=Array("descriptiontrim","",183,228);
$z[4]=Array("item","\r\n   {dede:match}<title>[内容]_{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",230,383);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}（作者：@站酷网 - [内容]）{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",383,549);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}Powered By [内容]（ZCOOL）</title>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",549,723);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",723,864);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div class=\"tutorial_show_min font14 u\">[内容]<p class=\"u\">本文由{/dede:match}\r\n   {dede:trim replace=\"\"}<a(.*)>{/dede:trim}\r\n{dede:trim replace=\"\"}<div(.*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</div>{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",864,1197);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>