<?php
$z[0]=Array("sppage","",0,59);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.neihan8.com/article/20461.html",61,137);
$z[2]=Array("keywordtrim","",139,176);
$z[3]=Array("descriptiontrim","",178,223);
$z[4]=Array("item","\r\n   {dede:match}<h1>[ÄÚÈÝ]</h1>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",225,379);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",379,519);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",519,659);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",659,800);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div id=\"content\">[ÄÚÈÝ]<div id=\"tishibox\">{/dede:match}\r\n   {dede:trim replace=\"\"}<a([^>]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</a>{/dede:trim}\r\n{dede:trim replace=\"\"}<script([^>]*)>(.*)</script>{/dede:trim}\r\n{dede:trim replace=\"\"}<ins([^>]*)>(.*)</ins>{/dede:trim}\r\n{dede:trim replace=\"\"}<!--(.*)-->{/dede:trim}\r\n{dede:trim replace=\"\"}<div([^.]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</div>{/dede:trim}\r\n{dede:trim replace=\"\"}<span([^.]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</span>{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",800,1418);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>