{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423aA0B60-394633.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423aA54260-402014.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423aA93050-4150Z.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423aB40a0-422937.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423aBTO0-435H6.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423aC242F-441W5.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423aCBT0-456005.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423aD095P-462c4.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/135423aD491P-4J204.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/135423aDQ940-4T332.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/135423aE1X40-4a600.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/135423aE4X0-504135.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/135423aE9A0-512D5.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/135423aF411P-52W47.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/135423aF93020-533B0.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/135423aG313P-5423A.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c121130/135423aGC110-553016.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c121130/135423aGc960-564544.jpg{/dede:img}