<?php
$z[0]=Array("field","性感美女星野亚希",0,57);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的性感美女星野亚希",59,131);
$z[1][4]['name']="description";
$z[2]=Array("field","性感美女星野亚希",133,187);
$z[2][4]['name']="title";
$z[3]=Array("field","",189,228);
$z[3][4]['name']="writer";
$z[4]=Array("field","",230,269);
$z[4][4]['name']="source";
$z[5]=Array("field","",271,308);
$z[5][4]['name']="body";
$z[6]=Array("field","",310,350);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405311VbP-412D3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133405311c9140-424233.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133405312110D0-4325O.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133405312219260-44Y40.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340531231I10-45Y01.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133405312423V0-464495.jpg{/dede:img}",352,1132);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133405311VbP-412D3_lit.jpg",1134,1223);
$z[8][4]['name']="litpic";

?>