<?php
$z[0]=Array("field","清纯美女,美女图片,性感美女,小",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",72,116);
$z[1][4]['name']="description";
$z[2]=Array("field","简洁的审美",118,166);
$z[2][4]['name']="title";
$z[3]=Array("field","",168,207);
$z[3][4]['name']="writer";
$z[4]=Array("field","",209,248);
$z[4][4]['name']="source";
$z[5]=Array("field","",250,290);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",292,329);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U293K4F60-134U.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U293KO2520-2X96.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U293KS3320-32P3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U293L211040-4R96.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U293L2P550-51H9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U293L5TW0-625V.jpg{/dede:img}",331,1091);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U293K4F60-134U_lit.jpg",1093,1180);
$z[8][4]['name']="litpic";

?>