{dede:field name='keywords'}私立女学馆体育课{/dede:field}
{dede:field name='description'}提供最漂亮的私立女学馆体育课{/dede:field}
{dede:field name='title'}私立女学馆体育课{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354244Y510P-20F58.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354244Y626020-2154S.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354244YH9240-22YY.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354244YR0150-23a42.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354244YZ960-2462X.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354244YcY50-251O8.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354244Z0U2Z-2BS1.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354244Z1HH0-2I110.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354244Z260110-2XG9.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354244Z3554F-293559.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354244Z403960-3034R.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/1354244Z4aJ0-312645.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/1354244Z5X540-32GI.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/1354244ZC5Y0-331C5.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/1354244ZM0c0-34KR.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/1354244ZV2020-353431.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c121130/1354244Z949610-3DS6.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c121130/135424491026340-3H602.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c121130/135424491113050-3Y4P.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c121130/13542449120X50-393R7.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c121130/1354244912c340-40PK.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c121130/1354244913W340-419245.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c121130/1354244914R630-423395.jpg{/dede:img}
{dede:img ddimg='' text='图 24'}/uploads/allimg/c121130/135424491541U0-433W5.jpg{/dede:img}
{dede:img ddimg='' text='图 25'}/uploads/allimg/c121130/135424492092410-443010.jpg{/dede:img}
{dede:img ddimg='' text='图 26'}/uploads/allimg/c121130/1354244921R260-4525Y.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/1354244Y510P-20F58_lit.jpg{/dede:field}
