
      </div> 
      <div class="photo_prev"><a id="photoPrev" title="上一张" class="btn_pphoto" target="_self" hidefocus="true" href="javascript:showpic('pre');;"></a></div>
      <div class="photo_next"><a id="photoNext" title="下一张"class="btn_nphoto" target="_self" hidefocus="true" href="javascript:showpic('next');"></a></div>
      <div id="endSelect" style="display:none;">
        <div id="endSelClose" onclick="$('#endSelect').hide();"></div>
        <div class="bg"></div>
      </div>
    </div>
    
    <div class="type">
    <div class="dingyue">
    <strong>所属图集:<a href="http://www.xgmm.cc/mm/xingganmeinv/" title="性感美女">性感美女</a></strong>
    </div>
    <div class="share"><!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_b" style="line-height: 12px;">
<img src="http://bdimg.share.baidu.com/static/images/type-button-7.jpg?cdnversion=20120831" />
<a class="shareCount"></a>
</div>
<script type="text/javascript" id="bdshare_js" data="type=button&amp;uid=0" ></script>
<script type="text/javascript" id="bdshell_js"></script>
<script type="text/javascript">
document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + Math.ceil(new Date()/3600000);
</script>
<!-- Baidu Button END --></div>
    </div>
    <div class="list-pic">
      <div class="pre picbig">
        <div class="img-wrap"><a href='http://www.xgmm.cc/mm/xingganmeinv/20130829/670.html'><img src="/pic/2013-08-29/1-130R91G2580-L.jpg" title="性感的王丸丸"/><span>上一组</span></a> </div>
      </div>
      <a href="javascript:showpic('pre');" class="pre-bnt"><span></span></a>
      <div class="cont" style="position:relative">
        <ul class="cont picbig" id="pictureurls"  style="position:absolute">
          <li>
            <div class="img-wrap"><a href="javascript:;" hidefocus="true"><img src="http://img02.xgmm.cc/pic/2013-08-28/1-130RQ10544.jpg" title="第1张" rel="http://img02.xgmm.cc/pic/2013-08-28/1-130RQ10544.jpg"/><span>1</span></a></div>
          </li><li>
            <div class="img-wrap"><a href="javascript:;" hidefocus="true"><img src="http://img01.xgmm.cc/pic/2013-08-28/1-130RQ10548.jpg" title="第2张" rel="http://img01.xgmm.cc/pic/2013-08-28/1-130RQ10548.jpg"/><span>2</span></a></div>
          </li><li>
            <div class="img-wrap"><a href="javascript:;" hidefocus="true"><img src="http://img02.xgmm.cc/pic/2013-08-28/1-130RQ10554.jpg" title="第3张" rel="http://img02.xgmm.cc/pic/2013-08-28/1-130RQ10554.jpg"/><span>3</span></a></div>
          </li><li>
            <div class="img-wrap"><a href="javascript:;" hidefocus="true"><img src="http://img01.xgmm.cc/pic/2013-08-28/1-130RQ10557.jpg" title="第4张" rel="http://img01.xgmm.cc/pic/2013-08-28/1-130RQ10557.jpg"/><span>4</span></a></div>
          </li><li>
            <div class="img-wrap"><a href="javascript:;" hidefocus="true"><img src="http://img02.xgmm.cc/pic/2013-08-28/1-130RQ10600.jpg" title="第5张" rel="http://img02.xgmm.cc/pic/2013-08-28/1-130RQ10600.jpg"/><span>5</span></a></div>
          </li><li>
            <div class="img-wrap"><a href="javascript:;" hidefocus="true"><img src="http://img01.xgmm.cc/pic/2013-08-28/1-130RQ10602.jpg" title="第6张" rel="http://img01.xgmm.cc/pic/2013-08-28/1-130RQ10602.jpg"/><span>6</span></a></div>
          </li>
        </ul>
      </div>
      <a href="javascript:showpic('next');" class="next-bnt"><span></span></a>
      <div class="next picbig">
        <div class="img-wrap"><a href='http://www.xgmm.cc/mm/xingganmeinv/20130828/666.html'><img src="/pic/2013-08-28/1-130RQ04U10-L.jpg" title="维也纳的阳光"/><span>下一组</span></a> </div>
      </div>
    </div>
  </div>
  <script type="text/javascript" >BAIDU_CLB_SLOT_ID = "775250";</script>
  <script type="text/javascript" src="http://cbjs.baidu.com/js/o.js"></script>
  <div class="title-a mt20">
    <h2>编辑推荐</h2>
  </div>
  <div class="pic-list mb7">
    <ul>
      <li>
        <div class="picbox"><img data-original="/pic/2013-07-08/1-130FQ026330-L.jpg" alt="比基尼女郎白思宜" width="235" height="350" />
          <div><b><a href="http://www.xgmm.cc/mm/bijini/20130708/590.html"></a></b></div>
        </div>
        <div class="name"><a href="http://www.xgmm.cc/mm/bijini/20130708/590.html" title="比基尼女郎白思宜">比基尼女郎白思宜</a></div>
      </li>

      <li>
        <div class="picbox"><img data-original="/pic/2013-07-10/1-130G00921540-L.jpg" alt="混血嫩模龙星妍性感写真" width="235" height="350" />
          <div><b><a href="http://www.xgmm.cc/mm/meinvzipai/20130710/592.html"></a></b></div>
        </div>
        <div class="name"><a href="http://www.xgmm.cc/mm/meinvzipai/20130710/592.html" title="混血嫩模龙星妍性感写真">混血嫩模龙星妍性感写真</a></div>
      </li>

      <li>
        <div class="picbox"><img data-original="/pic/2013-06-14/1-1306141J3520-L.jpg" alt="王晓丹私房" width="235" height="350" />
          <div><b><a href="http://www.xgmm.cc/mm/mingxingmeinv/20130614/469.html"></a></b></div>
        </div>
        <div class="name"><a href="http://www.xgmm.cc/mm/mingxingmeinv/20130614/469.html" title="王晓丹私房">王晓丹私房</a></div>
      </li>

      <li>
        <div class="picbox"><img data-original="/pic/2013-07-18/1-130GQ333300-L.jpg" alt="宅男必备" width="235" height="350" />
          <div><b><a href="http://www.xgmm.cc/mm/meinvtuijian/20130718/623.html"></a></b></div>
        </div>
        <div class="name"><a href="http://www.xgmm.cc/mm/meinvtuijian/20130718/623.html" title="宅男必备">宅男必备</a></div>
      </li>

    </ul>
  </div>
  <div class="title-a">
    <h2>外部精彩推荐</h2>
  </div>
  <div class="pic-list">
    <ul>
            <li>
        <div class="picbox"><img data-original="/pic/130821/1_1611022141.jpg" alt="阳光下透漏完美躯体" width="235" height="350" />
          <div><b><a target="_blank" href="http://cnrdn.com/ocM8"></a></b></div>
        </div>
        <div class="name"><a target="_blank" href="http://cnrdn.com/ocM8" title="阳光下透漏完美躯体">阳光下透漏完美躯体</a></div>
      </li>
      <li>
        <div class="picbox"><img data-original="/pic/2013-06-14/1-1306141H6070-L.jpg" alt="纯白性感私房" width="235" height="350" />
          <div><b><a target="_blank" href="http://cnrdn.com/ocM8"></a></b></div>
        </div>
        <div class="name"><a target="_blank"http://cnrdn.com/ocM8" title="纯白性感私房">纯白性感私房</a></div>
      </li>
      <li>
        <div class="picbox"><img data-original="/pic/2013-06-09/1-1306091A2580-L.jpg" alt="90后卖萌女女" width="235" height="350" />
          <div><b><a target="_blank" href="http://cnrdn.com/ocM8"></a></b></div>
        </div>
        <div class="name"><a target="_blank" href="http://cnrdn.com/ocM8" title="90后卖萌女女">90后卖萌女女</a></div>
      </li>
      <li>
        <div class="picbox"><img data-original="/pic/2013-06-08/1-13060Q519330-L.jpg" alt="麻吉各种性感写真" width="235" height="350" />
          <div><b><a target="_blank" href="http://cnrdn.com/ocM8"></a></b></div>
        </div>
        <div class="name"><a target="_blank" href="http://cnrdn.com/ocM8" title="麻吉各种性感写真">麻吉各种性感写真</a></div>
      </li> 
    </ul>
  </div>
</div>
{dede:include filename="f.htm"