<?php
$z[0]=Array("field","辣妹,时尚,个性,主流,,",0,62);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",64,108);
$z[1][4]['name']="description";
$z[2]=Array("field","非主流夜店个性时尚辣妹",110,170);
$z[2][4]['name']="title";
$z[3]=Array("field","",172,211);
$z[3][4]['name']="writer";
$z[4]=Array("field","",213,252);
$z[4][4]['name']="source";
$z[5]=Array("field","",254,294);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",296,333);
$z[6][4]['name']="body";
$z[7]=Array("field","",335,374);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354240U4460P-333117.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354240U4TL0-342250.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354240U510350-353A5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354240U54320-3CA4.jpg{/dede:img}",376,968);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/1354240U4460P-333117_lit.jpg",970,1061);
$z[9][4]['name']="litpic";

?>