<?php
$z[0]=Array("field","美女,春天,,",0,52);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",54,98);
$z[1][4]['name']="description";
$z[2]=Array("field","春天的美女",100,148);
$z[2][4]['name']="title";
$z[3]=Array("field","",150,189);
$z[3][4]['name']="writer";
$z[4]=Array("field","",191,230);
$z[4][4]['name']="source";
$z[5]=Array("field","",232,272);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",274,311);
$z[6][4]['name']="body";
$z[7]=Array("field","",313,352);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423Z2bWZ-351530.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423Z30E450-3E241.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423Z3161E0-3J5R.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423Z3242M0-3RD7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423Z3323420-3a537.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423Z3392910-402634.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423Z34I330-415R1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423Z3551150-42E05.jpg{/dede:img}",354,1310);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423Z2bWZ-351530_lit.jpg",1312,1401);
$z[9][4]['name']="litpic";

?>