{dede:field name='keywords'}美女,春天,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}春天的美女{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423Z2bWZ-351530.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423Z30E450-3E241.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423Z3161E0-3J5R.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423Z3242M0-3RD7.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423Z3323420-3a537.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423Z3392910-402634.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423Z34I330-415R1.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423Z3551150-42E05.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135423Z2bWZ-351530_lit.jpg{/dede:field}
