<?php
$z[0]=Array("field",",",0,42);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",44,88);
$z[1][4]['name']="description";
$z[2]=Array("field","Hello!MyBaby",90,140);
$z[2][4]['name']="title";
$z[3]=Array("field","",142,181);
$z[3][4]['name']="writer";
$z[4]=Array("field","",183,222);
$z[4][4]['name']="source";
$z[5]=Array("field","",224,264);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",266,303);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334041Y422A0-1XF2.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334041Y5014P-1a9D.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334041Y5521F-201O8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334041Y6091P-219330.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334041YBO10-224D5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334041YGZ10-231038.jpg{/dede:img}",305,1076);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/1334041YM410-24O05.jpg",1078,1163);
$z[8][4]['name']="litpic";

?>