<?php
$z[0]=Array("field","美女,美女图片,性感美女,私房",0,68);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",70,114);
$z[1][4]['name']="description";
$z[2]=Array("field","浴室内私房",116,164);
$z[2][4]['name']="title";
$z[3]=Array("field","",166,205);
$z[3][4]['name']="writer";
$z[4]=Array("field","",207,246);
$z[4][4]['name']="source";
$z[5]=Array("field","",248,288);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",290,327);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2aX412H0-1H92.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2aX44V20-24148.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2aX4N520-3KT.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2aX505430-45095.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2aX540130-54317.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2aX5Z130-62011.jpg{/dede:img}",329,1089);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2aX412H0-1H92_lit.jpg",1091,1178);
$z[8][4]['name']="litpic";

?>