{dede:field name='keywords'}90后美女{/dede:field}
{dede:field name='description'}惊艳十足90后美女。{/dede:field}
{dede:field name='title'}惊艳十足90后美女{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423bS151P-621a.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423bSGA0-L605.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423bT115P-X038.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423bT4RZ-92937.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423bTVM0-1093V.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423bU25430-11PJ.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423bUL340-1242P.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423bV13R0-13B96.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/135423bV63520-1451C.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/135423bW0D50-153S4.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/135423bW4020-1B928.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135423bS151P-621a_lit.jpg{/dede:field}
