{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402315541V0-1W37.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402315DO40-2bO.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402315R0M0-3GI.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402315943c0-43307.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334023160Q220-59514.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334023162064P-62423.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334023163454Z-N3W.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334023164J3Z-R1K.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/13340231B05630-95156.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/13340231C41F-1021B.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/13340231DK640-1110O.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/13340231F13040-121615.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/13340231G4E40-131V6.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/13340231Ha120-14Y26.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/13340231J3G50-151025.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/13340231K50040-1B146.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/13340231L925F-1NA0.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/13340231N52930-1V108.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c120410/13340231OJ420-1cY6.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c120410/13340231P91010-205F4.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c120410/13340231R2510-21X02.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c120410/13340231SO2F-2264E.jpg{/dede:img}