{dede:noteinfo notename="«Â¥ø√¿≈Æ" channelid="2" macthtype="string"
    refurl="http://" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.win4000.com/meinvtag3_(*).html"
startid="2" endid="4" addv="1" urlrule="area" musthas=""
 nothas="tag" listpic="0" usemore="0"}
    {dede:addurls}http://www.win4000.com/meinvtag3.html{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<ul class="pic-list" id="pic-list">{/dede:areastart}
    {dede:areaend}<div id="page_warp"{/dede:areaend}
{/dede:listrule}
