<?php
$z[0]=Array("noteinfo","",0,163);
$z[0][4]['notename']="Çå´¿ÃÀÅ®";
$z[0][4]['channelid']="2";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}http://www.win4000.com/meinvtag3.html{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<ul class=\"pic-list\" id=\"pic-list\">{/dede:areastart}\r\n    {dede:areaend}<div id=\"page_warp\"{/dede:areaend}\r\n",165,659);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.win4000.com/meinvtag3_(*).html";
$z[1][4]['startid']="2";
$z[1][4]['endid']="4";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="tag";
$z[1][4]['listpic']="0";
$z[1][4]['usemore']="0";

?>