<?php
$z[0]=Array("field","小龙女彤彤",0,51);
$z[0][4]['name']="keywords";
$z[1]=Array("field","她，唯美而清新，气质超凡脱俗，拥有天使的面孔魔鬼的身材，是中国新生代广告模特界无与伦比的最有影响力的完美女神！传说中的网络美女--林柯彤",53,231);
$z[1][4]['name']="description";
$z[2]=Array("field","小龙女彤彤妩媚风情无法挡",233,295);
$z[2][4]['name']="title";
$z[3]=Array("field","",297,336);
$z[3][4]['name']="writer";
$z[4]=Array("field","",338,377);
$z[4][4]['name']="source";
$z[5]=Array("field","",379,419);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",421,458);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/13340430NW50-15622.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340430OBN0-2c32.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340430P44V0-31126.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340430Q094Z-429B.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340430QX010-5aU.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340430R42640-644E.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340430S04V0-O950.jpg{/dede:img}",460,1317);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/13340430SZ510-R208.jpg",1319,1404);
$z[8][4]['name']="litpic";

?>