<?php
$z[0]=Array("field","刘雨欣,半秀香肩性感动人",0,64);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供刘雨欣 半秀香肩性感动人。",66,149);
$z[1][4]['name']="description";
$z[2]=Array("field","刘雨欣 半秀香肩性感动人",151,212);
$z[2][4]['name']="title";
$z[3]=Array("field","",214,253);
$z[3][4]['name']="writer";
$z[4]=Array("field","",255,294);
$z[4][4]['name']="source";
$z[5]=Array("field","",296,336);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",338,375);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629AcbH40-3I342.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B00022220-3YP8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B0005N40-3964a.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B000X30-4052U.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629B0012L20-41A35.jpg{/dede:img}",377,1056);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629AcbH40-3I342_lit.jpg",1058,1146);
$z[8][4]['name']="litpic";

?>