{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}清纯无敌{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/133412063FW60-15Cb.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/133412063bQ30-1A214.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/133412064250310-1O417.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/133412064523940-1W642.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/133412064K64Z-195964.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/1334120A000930-201206.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/1334120A255920-211a9.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/1334120A5291F-229639.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/133412063FW60-15Cb_lit.jpg{/dede:field}
