<?php
$z[0]=Array("field",",",0,42);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",44,88);
$z[1][4]['name']="description";
$z[2]=Array("field","宝杈白冰",90,136);
$z[2][4]['name']="title";
$z[3]=Array("field","",138,177);
$z[3][4]['name']="writer";
$z[4]=Array("field","",179,218);
$z[4][4]['name']="source";
$z[5]=Array("field","",220,260);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",262,299);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334041X43WZ-12C15.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334041X52E40-131264.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334041X5H520-142U1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334041X634410-15b39.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334041XFA20-1AY2.jpg{/dede:img}",301,982);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/1334041XOJ50-1N1O.jpg",984,1068);
$z[8][4]['name']="litpic";

?>