{dede:field name='keywords'}第二,四月,写真,生活,女孩,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美空女孩生活写真四月第二期{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354240BXR10-3K514.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354240Ba310-3Q007.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354240C02L60-393437.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354240C0N30-40YQ.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354240C155550-415548.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354240C20WP-4210Z.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354240C25K20-433D7.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354240C315250-443502.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354240C3I0P-456401.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354240C423240-4BC4.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354240C4B50-4H0R.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/1354240C50WZ-4W1J.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/1354240C560250-491432.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/1354240C610C0-506292.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/1354240CA550-5114S.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/1354240CEJ60-52FJ.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c121130/1354240CISZ-53U18.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c121130/1354240CN2230-545T4.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c121130/1354240CU32P-555C1.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c121130/1354240CZEP-5CL7.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c121130/1354240C9602P-5L293.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c121130/1354240D0101F-5T641.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c121130/1354240D0D610-594319.jpg{/dede:img}
{dede:img ddimg='' text='图 24'}/uploads/allimg/c121130/1354240D11a0-605236.jpg{/dede:img}
{dede:img ddimg='' text='图 25'}/uploads/allimg/c121130/1354240D1P510-615323.jpg{/dede:img}
{dede:img ddimg='' text='图 26'}/uploads/allimg/c121130/1354240D223550-62L47.jpg{/dede:img}
{dede:img ddimg='' text='图 27'}/uploads/allimg/c121130/1354240D2I0-63Vc.jpg{/dede:img}
{dede:img ddimg='' text='图 28'}/uploads/allimg/c121130/1354240D320550-642U6.jpg{/dede:img}
{dede:img ddimg='' text='图 29'}/uploads/allimg/c121130/1354240D3CT0-A1A2.jpg{/dede:img}
{dede:img ddimg='' text='图 30'}/uploads/allimg/c121130/1354240D423b0-Ba16.jpg{/dede:img}
{dede:img ddimg='' text='图 31'}/uploads/allimg/c121130/1354240D494340-C61L.jpg{/dede:img}
{dede:img ddimg='' text='图 32'}/uploads/allimg/c121130/1354240D554910-D4040.jpg{/dede:img}
{dede:img ddimg='' text='图 33'}/uploads/allimg/c121130/1354240D633c0-EI53.jpg{/dede:img}
{dede:img ddimg='' text='图 34'}/uploads/allimg/c121130/1354240DEL30-F5A3.jpg{/dede:img}
{dede:img ddimg='' text='图 35'}/uploads/allimg/c121130/1354240DK1O0-G6054.jpg{/dede:img}
{dede:img ddimg='' text='图 36'}/uploads/allimg/c121130/1354240DP6350-HVF.jpg{/dede:img}
{dede:img ddimg='' text='图 37'}/uploads/allimg/c121130/1354240DU5B0-IY50.jpg{/dede:img}
{dede:img ddimg='' text='图 38'}/uploads/allimg/c121130/1354240DYc0-JI45.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/1354240BXR10-3K514_lit.jpg{/dede:field}
