{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}青春年华{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334120J462510-1HW.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334120JLI10-21049.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/1334120K040620-34R4.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334120K31D10-4D49.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/1334120K592250-53947.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/1334120KVV20-62L2.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/1334120L152220-N2a.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/1334120L439640-V3O.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/1334120J462510-1HW_lit.jpg{/dede:field}
