<?php
$z[0]=Array("field","寂寞女孩思念",0,53);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供寂寞女孩思念。",55,127);
$z[1][4]['name']="description";
$z[2]=Array("field","寂寞女孩思念",129,179);
$z[2][4]['name']="title";
$z[3]=Array("field","",181,220);
$z[3][4]['name']="writer";
$z[4]=Array("field","",222,261);
$z[4][4]['name']="source";
$z[5]=Array("field","",263,303);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",305,342);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A1P55W0-12951.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A1Q50A0-24R1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A1QL1F-32Q6.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A1R00520-4Tb.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A1R301Z-52191.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A1R643Z-62444.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629A1RK410-K395.jpg{/dede:img}",344,1196);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A1P55W0-12951_lit.jpg",1198,1287);
$z[8][4]['name']="litpic";

?>