<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="235";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","/uploads/allimg/c131124/13U2U553C5Z-V257.jpg",187,273);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","/uploads/allimg/c131124/13U2U5551310-91058.jpg",275,363);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","/uploads/allimg/c131124/13U2U5554250-10M49.jpg",365,453);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","/uploads/allimg/c131124/13U2U55D1110-119223.jpg",455,544);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","/uploads/allimg/c131124/13U2U55J3620-121060.jpg",546,635);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","/uploads/allimg/c131124/13U2U55S1H0-13F09.jpg",637,724);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";

?>