{dede:field name='keywords'}极品私房{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}清晨佳人梦犹在の极品私房系列{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424044424040-I237.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424044463M0-TD5.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354240445023Z-a5I.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542404454A50-10N19.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542404459D50-112096.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135424044635030-123T6.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424044D4130-135145.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135424044I2T0-149562.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/135424044M4030-159314.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/135424044O5V0-1DD1.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/135424044T9510-1N209.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/135424044XY60-1V540.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/13542404492O0-19BT.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/135424044a4D0-20Z09.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135424044424040-I237_lit.jpg{/dede:field}
