{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}嘉依写真{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2cU4041Z-NE0.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2cU4F2Z-S502.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2cU54050-94219.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2cU625Z-101029.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2cUG3010-112D6.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c131124/13U2cU4041Z-NE0_lit.jpg{/dede:field}
