<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","嘉依写真",89,135);
$z[2][4]['name']="title";
$z[3]=Array("field","",137,176);
$z[3][4]['name']="writer";
$z[4]=Array("field","",178,217);
$z[4][4]['name']="source";
$z[5]=Array("field","",219,259);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",261,298);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2cU4041Z-NE0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2cU4F2Z-S502.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2cU54050-94219.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2cU625Z-101029.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2cUG3010-112D6.jpg{/dede:img}",300,968);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2cU4041Z-NE0_lit.jpg",970,1056);
$z[8][4]['name']="litpic";

?>