<?php
$z[0]=Array("field","楚楚",0,45);
$z[0][4]['name']="keywords";
$z[1]=Array("field","楚楚魅惑美图",47,103);
$z[1][4]['name']="description";
$z[2]=Array("field","楚楚魅惑美图",105,155);
$z[2][4]['name']="title";
$z[3]=Array("field","",157,196);
$z[3][4]['name']="writer";
$z[4]=Array("field","",198,237);
$z[4][4]['name']="source";
$z[5]=Array("field","",239,279);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",281,318);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403QY291P-229443.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403QZ4L10-235016.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403Q914IP-243a5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403Q9255520-25KI.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403Q9340150-261a7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403Q9402610-2J422.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403Q94CY0-2Tb9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403Q95B950-293562.jpg{/dede:img}",320,1275);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133403Q9D3U0-30I33.jpg",1277,1362);
$z[8][4]['name']="litpic";

?>