<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="600";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/c131124/13U2aG52F60-94V7.jpg ",93,250);
$z[1][4]['ddimg']="/uploads/allimg/c131124/13U2aG52F60-94V7.jpg";
$z[1][4]['text']="ͼ 1";
$z[1][4]['width']="603";
$z[1][4]['height']="909";
$z[2]=Array("img"," /uploads/allimg/c131124/13U2aG5V360-1062H.jpg ",252,411);
$z[2][4]['ddimg']="/uploads/allimg/c131124/13U2aG5V360-1062H.jpg";
$z[2][4]['text']="ͼ 2";
$z[2][4]['width']="636";
$z[2][4]['height']="915";
$z[3]=Array("img"," /uploads/allimg/c131124/13U2aGL60F-11D03.jpg ",413,570);
$z[3][4]['ddimg']="/uploads/allimg/c131124/13U2aGL60F-11D03.jpg";
$z[3][4]['text']="ͼ 3";
$z[3][4]['width']="615";
$z[3][4]['height']="912";
$z[4]=Array("img"," /uploads/allimg/c131124/13U2aGR1a0-123924.jpg ",572,731);
$z[4][4]['ddimg']="/uploads/allimg/c131124/13U2aGR1a0-123924.jpg";
$z[4][4]['text']="ͼ 4";
$z[4][4]['width']="628";
$z[4][4]['height']="911";
$z[5]=Array("img"," /uploads/allimg/c131124/13U2aH1N3Z-1323U.jpg ",733,890);
$z[5][4]['ddimg']="/uploads/allimg/c131124/13U2aH1N3Z-1323U.jpg";
$z[5][4]['text']="ͼ 5";
$z[5][4]['width']="609";
$z[5][4]['height']="915";

?>