{dede:pagestyle maxwidth='600' pagepicnum='12' ddmaxwidth='200' row='0' col='0' value='2'/}
{dede:img ddimg='/uploads/allimg/c131124/13U2aG52F60-94V7.jpg' text='ͼ 1' width='603' height='909'} /uploads/allimg/c131124/13U2aG52F60-94V7.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2aG5V360-1062H.jpg' text='ͼ 2' width='636' height='915'} /uploads/allimg/c131124/13U2aG5V360-1062H.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2aGL60F-11D03.jpg' text='ͼ 3' width='615' height='912'} /uploads/allimg/c131124/13U2aGL60F-11D03.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2aGR1a0-123924.jpg' text='ͼ 4' width='628' height='911'} /uploads/allimg/c131124/13U2aGR1a0-123924.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c131124/13U2aH1N3Z-1323U.jpg' text='ͼ 5' width='609' height='915'} /uploads/allimg/c131124/13U2aH1N3Z-1323U.jpg {/dede:img}
