{dede:field name='keywords'}俏护士西村纱也禾{/dede:field}
{dede:field name='description'}提供最漂亮的俏护士西村纱也禾{/dede:field}
{dede:field name='title'}俏护士西村纱也禾{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405420645Q0-16362.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133405420KCZ-22048.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133405420TM60-3U27.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340542094Y20-4CJ.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340542103OF-54B6.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340542112aF-C0U.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133405421222940-HZ1.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334054213204F-W955.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/13340542141T20-95A2.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133405421502F-10AM.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133405421610a0-119560.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133405421FB50-124208.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133405421PC60-13H53.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133405421Z2H0-144X1.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133405421c5960-1510B.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/13340542209A60-1C646.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/1334054221cJ0-1I3Z.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/1334054222Za0-1UU8.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c120410/1334054223UI0-1c961.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c120410/1334054224J0-20M42.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c120410/13340542255W10-214120.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c120410/133405422AHZ-224c9.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133405420645Q0-16362_lit.jpg{/dede:field}
