<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","清纯靓小妹",89,137);
$z[2][4]['name']="title";
$z[3]=Array("field","",139,178);
$z[3][4]['name']="writer";
$z[4]=Array("field","",180,219);
$z[4][4]['name']="source";
$z[5]=Array("field","",221,261);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",263,300);
$z[6][4]['name']="body";
$z[7]=Array("field","",302,341);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}http://img.qqsisi.com/allimg/111119/10-11111ZS353.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}http://img.qqsisi.com/allimg/111119/10-11111ZS356.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}http://img.qqsisi.com/allimg/111119/10-11111ZS359.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}http://img.qqsisi.com/allimg/111119/10-11111ZS402.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}http://img.qqsisi.com/allimg/111119/10-11111ZS405.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}http://img.qqsisi.com/allimg/111119/10-11111ZS408.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}http://img.qqsisi.com/allimg/111119/10-11111ZS434.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}http://img.qqsisi.com/allimg/111119/10-11111ZS437.jpg{/dede:img}",343,1346);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","",1348,1387);
$z[9][4]['name']="litpic";

?>