{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354244244552F-13C2.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542442455GP-262M.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542442464D40-3J17.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424424I5040-4T16.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424424Q43F-5K94.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135424424YYF-AP2.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424424aR20-MH0.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135424425063050-W592.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/135424425150O0-95362.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/13542442523R0-101408.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354244253250P-1162J.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/135424425413410-125294.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/13542442550Q30-13KB.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/1354244255961P-1455W.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/135424425DB20-15DW.jpg{/dede:img}