{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334121251W1P-1R613.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/13341212549A10-191V9.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/133412125M5910-20R64.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334121260313Z-21H41.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/133412126322630-221I2.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/13341212B21250-233b0.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/13341212E0140-242M9.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/13341212GT140-25L41.jpg{/dede:img}