<?php
$z[0]=Array("field","性感美女,美女私房,美女",0,63);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",65,109);
$z[1][4]['name']="description";
$z[2]=Array("field","让性感停留",111,159);
$z[2][4]['name']="title";
$z[3]=Array("field","",161,200);
$z[3][4]['name']="writer";
$z[4]=Array("field","",202,241);
$z[4][4]['name']="source";
$z[5]=Array("field","",243,283);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",285,322);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2UZ161X0-246054.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2UZ3303Z-254T8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2UZ39610-2DT0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2UZ505P-2H100.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2UZ60F10-2QG9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2UZL5H0-29AP.jpg{/dede:img}",324,1081);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2UZ161X0-246054_lit.jpg",1083,1172);
$z[8][4]['name']="litpic";

?>