{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354240J503C0-422Z5.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354240J5RD0-435N1.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354240J6210F-4454V.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354240JD4I0-456443.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354240JIa40-4E129.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354240JP0350-4HB9.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354240JV3430-4R2A.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354240JZO10-4920S.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354240J9A160-50X23.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354240K045930-51U44.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354240K0U340-52Y25.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/1354240K1293P-53C21.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/1354240K2210Z-5460K.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/1354240K264A0-551215.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/1354240K334c0-5C331.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/1354240K3J40-5II4.jpg{/dede:img}