{dede:field name='keywords'}楚楚{/dede:field}
{dede:field name='description'}百变美女楚楚{/dede:field}
{dede:field name='title'}百变美女楚楚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403RO61T0-163023.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403RP95140-1L545.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403RQ95620-1R403.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403RR95P-19B16.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403RT03520-2094c.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403RTY550-214642.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403RV2BP-224608.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133403RW22250-2343A.jpg{/dede:field}
