<?php
$z[0]=Array("field","楚楚",0,45);
$z[0][4]['name']="keywords";
$z[1]=Array("field","百变美女楚楚",47,103);
$z[1][4]['name']="description";
$z[2]=Array("field","百变美女楚楚",105,155);
$z[2][4]['name']="title";
$z[3]=Array("field","",157,196);
$z[3][4]['name']="writer";
$z[4]=Array("field","",198,237);
$z[4][4]['name']="source";
$z[5]=Array("field","",239,279);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",281,318);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403RO61T0-163023.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403RP95140-1L545.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403RQ95620-1R403.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403RR95P-19B16.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403RT03520-2094c.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403RTY550-214642.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403RV2BP-224608.jpg{/dede:img}",320,1181);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133403RW22250-2343A.jpg",1183,1269);
$z[8][4]['name']="litpic";

?>