{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423X95b440-35GG.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423X9642240-3C605.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423X9D33P-3OW5.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423Xa23560-3W910.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423Xa433P-3940Y.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423XaWH0-404941.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423Xb164P-4164b.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423Xb510F-424142.jpg{/dede:img}