{dede:field name='keywords'}周秀娜，嫩模{/dede:field}
{dede:field name='description'}7月中旬上映《热浪球爱战》集结了周秀娜、甜美型少女傅颖，性感高雅的Jessica.C等一群青春靓丽的影坛新秀，而沙滩排球戏份更是让一众美女大秀好身材。{/dede:field}
{dede:field name='title'}周秀娜领衔众嫩模力拼沙滩 比基尼齐上阵{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424002F5F-143195.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424002L3940-15G48.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135424002P1c0-1AB0.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424002TL0-1J024.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424002YBZ-1W616.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354240029B10-192R0.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424003054c0-2013V.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354240031111F-214149.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354240031K2Z-221458.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/135424003241010-23R02.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/135424003301Z-245603.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135424002F5F-143195_lit.jpg{/dede:field}
