<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","小妖精角色扮演",89,141);
$z[2][4]['name']="title";
$z[3]=Array("field","",143,182);
$z[3][4]['name']="writer";
$z[4]=Array("field","",184,223);
$z[4][4]['name']="source";
$z[5]=Array("field","",225,265);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",267,304);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2aW0LJ0-2GJ1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2aW24V50-2Q942.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2aW3K960-29C47.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2aW5E4F-302P4.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2aWG4X0-316158.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2aWO94Z-321050.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2aWc50-33IQ.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U2aX10P-349205.jpg{/dede:img}",306,1238);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2aW0LJ0-2GJ1_lit.jpg",1240,1326);
$z[8][4]['name']="litpic";

?>