{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354241W0541F-1a61.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354241W12c10-250b.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354241W160110-3RI.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354241W203460-45A9.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354241W243050-51643.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354241W2D10-61N3.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354241W3123P-K517.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354241W355240-SR7.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354241W40IF-94201.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354241W461960-102I0.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354241W494W0-1110O.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/1354241W542440-1235S.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/1354241W603H0-133119.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/1354241W64K60-145592.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/1354241WF0520-15F24.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/1354241WJ1150-1E137.jpg{/dede:img}