<?php
$z[0]=Array("field","嫩模",0,45);
$z[0][4]['name']="keywords";
$z[1]=Array("field","妖娆嫩模红唇裸香肩。",47,111);
$z[1][4]['name']="description";
$z[2]=Array("field","妖娆嫩模红唇裸香肩",113,169);
$z[2][4]['name']="title";
$z[3]=Array("field","",171,210);
$z[3][4]['name']="writer";
$z[4]=Array("field","",212,251);
$z[4][4]['name']="source";
$z[5]=Array("field","",253,293);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",295,332);
$z[6][4]['name']="body";
$z[7]=Array("field","",334,373);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423ba260Z-2N4V.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423baD640-2T2S.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423bb09540-2a1G.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423bb5530-305054.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423bb96460-311R1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423bc3U40-323U0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423bcW1Z-33MT.jpg{/dede:img}",375,1230);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423ba260Z-2N4V_lit.jpg",1232,1320);
$z[9][4]['name']="litpic";

?>