{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}http://img.qqsisi.com/allimg/111116/10-1111161A159.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}http://img.qqsisi.com/allimg/111116/10-1111161A201.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}http://img.qqsisi.com/allimg/111116/10-1111161A203.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}http://img.qqsisi.com/allimg/111116/10-1111161A205.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}http://img.qqsisi.com/allimg/111116/10-1111161A207.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}http://img.qqsisi.com/allimg/111116/10-1111161A209.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}http://img.qqsisi.com/allimg/111116/10-1111161A211.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}http://img.qqsisi.com/allimg/111116/10-1111161A213.jpg{/dede:img}