{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402JMX1F-439407.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402JNNb0-44K09.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402JP0U10-45Wa.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402JPX020-462060.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402JQ955F-4J141.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402JRbV0-4V354.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402JT03910-492028.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133402JTE5P-50E02.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133402JU514P-515212.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133402JV3E0-5232O.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133402JW40C0-533C0.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133402JX3J20-54J32.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133402JYCA0-55Z47.jpg{/dede:img}