<?php
$z[0]=Array("field","嫩模",0,45);
$z[0][4]['name']="keywords";
$z[1]=Array("field","妖娆嫩模红唇裸香肩。",47,111);
$z[1][4]['name']="description";
$z[2]=Array("field","妖娆嫩模红唇裸香肩",113,169);
$z[2][4]['name']="title";
$z[3]=Array("field","",171,210);
$z[3][4]['name']="writer";
$z[4]=Array("field","",212,251);
$z[4][4]['name']="source";
$z[5]=Array("field","",253,293);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",295,332);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402GAGZ-3X316.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402GB4G40-3b164.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402GC31350-401430.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402GD05W0-4155R.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402GDP410-42WM.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402GE460P-43I43.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402GF2J40-441421.jpg{/dede:img}",334,1191);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133402GFb120-453Q6.jpg",1193,1278);
$z[8][4]['name']="litpic";

?>