{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403P19120-4S2V.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403P2046350-492233.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403P21403P-50DR.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403P225220-514A7.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403P23430F-521X5.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403P2464T0-534J8.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403P2553P-543003.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403P2C4E0-559514.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133403P2L63P-5CE2.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133403P2V9210-5J920.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133403P2bF30-5V228.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133403P3062230-5b126.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133403P3131430-601942.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133403P321930-616000.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133403P3294240-625425.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133403P3395230-633Z9.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/133403P352GZ-642Q9.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/133403P3642450-AC25.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c120410/133403P3LL0-B4V7.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c120410/133403P3W1330-C5359.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c120410/133403P3c9520-DA15.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c120410/133403P4135C0-E4613.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c120410/133403P42591P-F3a5.jpg{/dede:img}
{dede:img ddimg='' text='图 24'}/uploads/allimg/c120410/133403P43BG0-GD28.jpg{/dede:img}
{dede:img ddimg='' text='图 25'}/uploads/allimg/c120410/133403P19120-4S2V.jpg{/dede:img}
{dede:img ddimg='' text='图 26'}/uploads/allimg/c120410/133403P2046350-492233.jpg{/dede:img}