<?php
$z[0]=Array("field","可爱漂亮90后清纯MM",0,59);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供可爱漂亮90后清纯MM。",61,139);
$z[1][4]['name']="description";
$z[2]=Array("field","可爱漂亮90后清纯MM",141,197);
$z[2][4]['name']="title";
$z[3]=Array("field","",199,238);
$z[3][4]['name']="writer";
$z[4]=Array("field","",240,279);
$z[4][4]['name']="source";
$z[5]=Array("field","",281,321);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",323,360);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A2961P-11P4.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A29A250-251U.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A29DRZ-33L5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A2a262F-4F60.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A2a60110-54212.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A2aY2P-630B.jpg{/dede:img}",362,1122);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A2961P-11P4_lit.jpg",1124,1211);
$z[8][4]['name']="litpic";

?>