{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403EO4OZ-1344N8.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403EP5NF-1353147.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403EQT1P-1364I4.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403ES2M10-13K491.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403ET6060-13TX3.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403EUb610-13c932.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403EVE420-140D14.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403EWA530-1419302.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133403EX64A0-142WY.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133403EY60C0-143R08.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133403EZ53320-1444G6.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133403E914250-145T26.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133403E924L60-1464519.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133403E93cF-14K5P.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133403E949E10-14X1M.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133403E9602620-1494113.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/133403Ea5210-150HM.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/133403Eb5330-15144U.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c120410/133403F000H50-1522O7.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c120410/133403F0110520-1534641.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c120410/133403F02523P-1541P0.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c120410/133403F03OT0-155LQ.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c120410/133403F04U540-15C545.jpg{/dede:img}
{dede:img ddimg='' text='图 24'}/uploads/allimg/c120410/133403F05Y010-15N004.jpg{/dede:img}