<?php
$z[0]=Array("field","超大胸美眉诗梓佳性感写真",0,65);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供超大胸美眉诗梓佳性感写真。",67,151);
$z[1][4]['name']="description";
$z[2]=Array("field","超大胸美眉诗梓佳性感写真",153,215);
$z[2][4]['name']="title";
$z[3]=Array("field","",217,256);
$z[3][4]['name']="writer";
$z[4]=Array("field","",258,297);
$z[4][4]['name']="source";
$z[5]=Array("field","",299,339);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",341,378);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A235J120-1a627.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A23605a0-2010Y.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A2362I30-216318.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A2364950-225P0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A23C5360-23P21.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A23E9C0-243328.jpg{/dede:img}",380,1154);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A235J120-1a627_lit.jpg",1156,1246);
$z[8][4]['name']="litpic";

?>