{dede:field name='keywords'}胖胖女优田井中茉莉亜{/dede:field}
{dede:field name='description'}提供最漂亮的胖胖女优田井中茉莉亜{/dede:field}
{dede:field name='title'}胖胖女优田井中茉莉亜{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405444435Z-2O596.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133405444564D0-2S340.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133405444A5D0-295194.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133405444JO60-301491.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133405444U1V0-31TH.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133405444952910-323261.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133405445053560-336455.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334054451Dc0-342V3.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/1334054452B0F-356347.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/1334054453B4P-3EC9.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/13340544545620-3O128.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/13340544554C10-3UN7.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133405445A44F-392140.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133405445L5230-409208.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133405445W2P-411F3.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/1334054459E20-42R28.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/1334054460O030-43W10.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133405444435Z-2O596_lit.jpg{/dede:field}
