{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334042ZX1530-1WV.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334042Z955a0-264O.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133404291023230-32I5.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334042910K3P-42239.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340429124R30-52409.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340429131S40-C096.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334042913T0Z-MW8.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/13340429143M30-U3U.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/13340429150H20-93527.jpg{/dede:img}