{dede:noteinfo notename="性感美女 www.yirenw.com" channelid="2" macthtype="string"
    refurl="http://" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.yirenw.com/pic/more/080506105634646886/(*).html"
startid="1" endid="3" addv="1" urlrule="area" musthas=""
 nothas="" listpic="0" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="picli">{/dede:areastart}
    {dede:areaend}<div class="fenye">{/dede:areaend}
{/dede:listrule}
