{dede:field name='keywords'}女孩,快乐,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}快乐女孩{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402260129240-22M09.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402260260340-232942.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402260392I0-24Oa.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334022605592Z-25V62.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402260DL50-2E007.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402260P4I0-2I308.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340226092RZ-2S549.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/13340226104140-2cX2.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/1334022611L160-30Z94.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133402261331320-314501.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/13340226144a50-32T57.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133402261543960-334F1.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/13340226161cZ-342542.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133402261F0260-35G26.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133402261R2O0-3A446.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133402261942410-3N4C.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133402262051550-3XY8.jpg{/dede:field}
