{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629AL5c5Z-164R8.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629ALA9E0-1M328.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629ALEB50-1R2X.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629ALK35P-1a1N.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629ALPZZ-209200.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629ALV2040-21H54.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629ALZ1020-222445.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629AL9BT0-235032.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c130311/13629AM019B0-243B6.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c130311/13629AM0K510-2513L.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c130311/13629AM115440-2D934.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c130311/13629AM1E4P-2J212.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c130311/13629AM213120-2R208.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c130311/13629AM25L40-292a7.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c130311/13629AM300T0-304158.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c130311/13629AM33YP-3154N.jpg{/dede:img}