{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423912b52Z-30N18.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542391311ZP-3123C.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354239131c450-329614.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542391326260-33Sc.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354239133502F-343P8.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542391345B0-354631.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423913514930-3CU3.jpg{/dede:img}