<?php
$z[0]=Array("field","80后很潮的非主流高挑美女",0,65);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供80后很潮的非主流高挑美女。",67,151);
$z[1][4]['name']="description";
$z[2]=Array("field","80后很潮的非主流高挑美女",153,215);
$z[2][4]['name']="title";
$z[3]=Array("field","",217,256);
$z[3][4]['name']="writer";
$z[4]=Array("field","",258,297);
$z[4][4]['name']="source";
$z[5]=Array("field","",299,339);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",341,378);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A3F55140-229224.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A3FW060-231193.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A3G154P-24Oa.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A3G40O0-25Y31.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A3GAF-2B596.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A3H00050-2O229.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629A3H30L0-2Q435.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629A3H630F-294Y4.jpg{/dede:img}",380,1328);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A3F55140-229224_lit.jpg",1330,1421);
$z[8][4]['name']="litpic";

?>