{dede:field name='keywords'}比基尼写真{/dede:field}
{dede:field name='description'}日本新生代写真女星小泉麻耶带来夏日超性感比基尼写真，小泉麻耶第一本写真集就在当年荣登日本下载量最多的桂冠，这次再次出击带给你既清爽又火辣的盛夏感受。{/dede:field}
{dede:field name='title'}日本女星小泉麻耶夏日性感比基尼写真{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402L2225310-514231.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402L2303K0-5221W.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402L23601P-534021.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402L2435H0-54U41.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402L2501210-551311.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402L2560930-5DK0.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402L262c20-5O148.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133402L2E3Y0-5Q420.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133402L2L21F-5962B.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133402L2T4120-60a13.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133402L2ZXZ-613124.jpg{/dede:field}
