{dede:noteinfo notename="性感美女 www.84420.com" channelid="2" macthtype="string"
    refurl="http://" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.84420.com/xgmn/list_6_(*).html"
startid="1" endid="1" addv="1" urlrule="area" musthas=""
 nothas="" listpic="0" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="grid_4 imgblock">{/dede:areastart}
    {dede:areaend}<ul class="pagelist">{/dede:areaend}
{/dede:listrule}
