<?php
$z[0]=Array("field","爆乳,美女写真,诱人美女",0,63);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",65,109);
$z[1][4]['name']="description";
$z[2]=Array("field","黑子爆乳自拍",111,161);
$z[2][4]['name']="title";
$z[3]=Array("field","",163,202);
$z[3][4]['name']="writer";
$z[4]=Array("field","",204,243);
$z[4][4]['name']="source";
$z[5]=Array("field","",245,285);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",287,324);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U29255R6160-30I38.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U29255W1460-31GW.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U29255Yc60-323G1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U292559AM0-333510.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U29255b62F-342414.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U292560232F-355406.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U29256055C0-364940.jpg{/dede:img}",326,1190);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U29255R6160-30I38_lit.jpg",1192,1282);
$z[8][4]['name']="litpic";

?>