{dede:field name='keywords'}素颜石井香织{/dede:field}
{dede:field name='description'}提供最漂亮的素颜石井香织{/dede:field}
{dede:field name='title'}素颜石井香织{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424420409620-21SI.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424420515310-22W34.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354244205T5P-2342E.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424420B11Z-241145.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424420J4S0-254147.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135424420Q4110-264Z6.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424420Y1160-2IA6.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135424420a44P-2S034.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354244210512P-2935G.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/135424421135A0-30S60.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/13542442122350-311327.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/13542442129DZ-324S5.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/1354244213OM0-339411.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135424420409620-21SI_lit.jpg{/dede:field}
