<?php
$z[0]=Array("field","美女在乡间小路,清纯美女",0,64);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供美女在乡间小路 清纯美女。",66,149);
$z[1][4]['name']="description";
$z[2]=Array("field","美女在乡间小路  清纯美女",151,213);
$z[2][4]['name']="title";
$z[3]=Array("field","",215,254);
$z[3][4]['name']="writer";
$z[4]=Array("field","",256,295);
$z[4][4]['name']="source";
$z[5]=Array("field","",297,337);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",339,376);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629AY1Lc0-3644N.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629AY235360-3I1R.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629AY2GX0-3RW2.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629AY315140-393139.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629AY3530F-402309.jpg{/dede:img}",378,1055);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629AY1Lc0-3644N_lit.jpg",1057,1145);
$z[8][4]['name']="litpic";

?>