<?php
$z[0]=Array("field","日本性感美女田中凉子",0,61);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的日本性感美女田中凉子",63,139);
$z[1][4]['name']="description";
$z[2]=Array("field","日本性感美女田中凉子",141,199);
$z[2][4]['name']="title";
$z[3]=Array("field","",201,240);
$z[3][4]['name']="writer";
$z[4]=Array("field","",242,281);
$z[4][4]['name']="source";
$z[5]=Array("field","",283,320);
$z[5][4]['name']="body";
$z[6]=Array("field","",322,362);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334053160G130-F4612.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133405316201030-G2345.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133405316310X0-H3X3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340531640RZ-IB14.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340531A0S0-JY36.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340531B12G0-K2941.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340531C1Q20-L9111.jpg{/dede:img}",364,1228);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/1334053160G130-F4612_lit.jpg",1230,1321);
$z[8][4]['name']="litpic";

?>