<?php
$z[0]=Array("field","高清:百变美女的精致五官",0,64);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供高清:百变美女的精致五官。",66,149);
$z[1][4]['name']="description";
$z[2]=Array("field","高清:百变美女的精致五官",151,212);
$z[2][4]['name']="title";
$z[3]=Array("field","",214,253);
$z[3][4]['name']="writer";
$z[4]=Array("field","",255,294);
$z[4][4]['name']="source";
$z[5]=Array("field","",296,336);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",338,375);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A302O410-I9B.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A3032Y50-Y2a.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A3033UF-aO3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A30349330-10J04.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A303I920-112947.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A303b240-125534.jpg{/dede:img}",377,1146);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A302O410-I9B_lit.jpg",1148,1236);
$z[8][4]['name']="litpic";

?>