{dede:field name='keywords'}嫩模{/dede:field}
{dede:field name='description'}嫩模性感超火辣内衣大片。{/dede:field}
{dede:field name='title'}嫩模火辣内衣大片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402IG13C0-4DL3.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402IGY5Z-4ML5.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402IH44H0-4UW1.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402II06260-4ba8.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402IIG550-50JD.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402IJ3X20-51WL.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402IK0G10-524Y4.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133402IK5040-532606.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133402IL0a0-54H49.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133402IL603P-5524B.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133402IM2N50-561H7.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133402IMW460-5O418.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133402IN44320-5R247.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133402IO00010-593F8.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133402IO52930-604211.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133402IP23V0-612012.jpg{/dede:field}
