{dede:field name='keywords'}清纯美女,叶熙祺甜甜超薄蕾丝群{/dede:field}
{dede:field name='description'}美桌图片库提供清纯美女 叶熙祺甜甜超薄蕾丝群街拍春装写真。{/dede:field}
{dede:field name='title'}清纯美女 叶熙祺甜甜超薄蕾丝群街拍春装写真{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B1a5EZ-20J44.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B1a5EZ-20J44.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B1b2910-213646.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B1b59530-222445.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629B1c04U0-23aH.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629B1c5DP-24B35.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629B2000W0-25LB.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629B20060530-263264.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c130311/13629B200952Z-2J937.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c130311/13629B2013JZ-2T358.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c130311/13629B201XU0-2945c.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c130311/13629B1a5EZ-20J44_lit.jpg{/dede:field}
