<?php
$z[0]=Array("field","萝莉,清纯美女",0,54);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",56,100);
$z[1][4]['name']="description";
$z[2]=Array("field","可爱小萝莉",102,150);
$z[2][4]['name']="title";
$z[3]=Array("field","",152,191);
$z[3][4]['name']="writer";
$z[4]=Array("field","",193,232);
$z[4][4]['name']="source";
$z[5]=Array("field","",234,274);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",276,313);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2942V21940-2935O.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2942X1T50-30J11.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2942XKV0-319119.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2942bb220-325424.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2942c1S20-332C8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U29430360440-342292.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U29430420340-35Q21.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U29430A5060-3DO4.jpg{/dede:img}",315,1269);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2942V21940-2935O_lit.jpg",1271,1361);
$z[8][4]['name']="litpic";

?>