{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542444BPA0-1Y00.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542444D4UP-22134.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542444L1FP-325b.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542444M45610-42H9.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542444NT1F-5F26.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542444Ob540-E055.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/13542444QC460-L2A.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/13542444Rb5P-UO3.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/13542444Z34520-952L.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/13542444914aZ-10E16.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354244492U040-11A48.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/13542444940N10-12I13.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/135424449534D0-134527.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/13542444c5T50-143191.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/1354244500V4P-152422.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/135424450213a0-161D6.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c121130/135424450360D0-1J0c.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c121130/135424456422140-1S630.jpg{/dede:img}