<?php
$z[0]=Array("field","清纯美女,美女自拍,美女图片",0,67);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",69,113);
$z[1][4]['name']="description";
$z[2]=Array("field","小玥玥闺房自拍",115,167);
$z[2][4]['name']="title";
$z[3]=Array("field","",169,208);
$z[3][4]['name']="writer";
$z[4]=Array("field","",210,249);
$z[4][4]['name']="source";
$z[5]=Array("field","",251,291);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",293,330);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2925U29210-2344G.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2925V30420-24O93.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2925W29620-254916.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2925X39230-2E636.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2925Y3W40-2J014.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2925YJ340-2Ub6.jpg{/dede:img}",332,1103);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2925U29210-2344G_lit.jpg",1105,1195);
$z[8][4]['name']="litpic";

?>