{dede:field name='keywords'}可爱日本麻豆{/dede:field}
{dede:field name='description'}提供最漂亮的可爱日本麻豆{/dede:field}
{dede:field name='title'}可爱日本麻豆{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/13340545345I50-354G0.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334054535X450-3641Y.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133405453G24F-3JV6.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133405453P2620-3R334.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133405453911550-393E7.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133405454023Y0-40N34.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334054541252P-41G91.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133405454233460-421F3.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/13340545345I50-354G0_lit.jpg{/dede:field}
