<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","可爱MM黑白搭配装",89,143);
$z[2][4]['name']="title";
$z[3]=Array("field","",145,184);
$z[3][4]['name']="writer";
$z[4]=Array("field","",186,225);
$z[4][4]['name']="source";
$z[5]=Array("field","",227,264);
$z[5][4]['name']="body";
$z[6]=Array("field","",266,306);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/133412151UW0-24CR.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334121521W4Z-252629.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/133412152494I0-263194.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/133412152P2W0-2LP5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/133412153112310-2Y336.jpg{/dede:img}",308,992);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120411/133412151UW0-24CR_lit.jpg",994,1082);
$z[8][4]['name']="litpic";

?>