{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542592110W50-1U15.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542592133E10-29221.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354259215N10-31b2.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135425921c0610-49557.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542592221LF-5Ta.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542592242UP-A517.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354259226364P-I0E.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135425922V2330-YA8.jpg{/dede:img}