<?php
$z[0]=Array("field","超丰满小妹妹筱崎爱",0,59);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的超丰满小妹妹筱崎爱",61,135);
$z[1][4]['name']="description";
$z[2]=Array("field","超丰满小妹妹筱崎爱",137,193);
$z[2][4]['name']="title";
$z[3]=Array("field","",195,234);
$z[3][4]['name']="writer";
$z[4]=Array("field","",236,275);
$z[4][4]['name']="source";
$z[5]=Array("field","",277,317);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",319,356);
$z[6][4]['name']="body";
$z[7]=Array("field","",358,397);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354244293b530-406137.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424429501360-419B1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354244295ZT0-42J16.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424429CP60-439420.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354244300Y1F-44A42.jpg{/dede:img}",399,1086);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/1354244293b530-406137_lit.jpg",1088,1180);
$z[9][4]['name']="litpic";

?>