<?php
$z[0]=Array("field","性感白衣天使的极品身材护士制服",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供性感白衣天使的极品身材护士制服诱惑。",73,167);
$z[1][4]['name']="description";
$z[2]=Array("field","性感白衣天使的极品身材护士制服诱惑",169,241);
$z[2][4]['name']="title";
$z[3]=Array("field","",243,282);
$z[3][4]['name']="writer";
$z[4]=Array("field","",284,323);
$z[4][4]['name']="source";
$z[5]=Array("field","",325,365);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",367,404);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629AI1F960-315417.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629AI203530-32B03.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629AI213b0-334021.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629AI23GZ-3430W.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629AI25FZ-35O43.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629AI2L2P-3E635.jpg{/dede:img}",406,1173);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629AI1F960-315417_lit.jpg",1175,1265);
$z[8][4]['name']="litpic";

?>