<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","校园女生",89,135);
$z[2][4]['name']="title";
$z[3]=Array("field","",137,176);
$z[3][4]['name']="writer";
$z[4]=Array("field","",178,217);
$z[4][4]['name']="source";
$z[5]=Array("field","",219,256);
$z[5][4]['name']="body";
$z[6]=Array("field","",258,298);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334122I5053Z-3060U.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334122Ia5020-31HX.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/1334122J3Y560-321C9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334122JF1050-3363F.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/1334122K0Y330-343053.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/1334122K51P20-354513.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/1334122KWM50-364910.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/1334122L246260-3O4S.jpg{/dede:img}",300,1256);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120411/1334122I5053Z-3060U_lit.jpg",1258,1348);
$z[8][4]['name']="litpic";

?>