{dede:field name='keywords'}越南人气大胸女{/dede:field}
{dede:field name='description'}曾经在网络上靠自拍爆红的越南人气“大胸”美女，近日代言了内衣。从网络红人到专业演员、模特，这种自我炒作手法似乎在如今的网络上悄然流行起来，众人对此褒贬不一，许多如此途径走红的少男少女在众人眼前只是昙花一现，并没有一直在演艺事业上走下去。{/dede:field}
{dede:field name='title'}越南人气大胸女代言内衣{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133404339455150-2T130.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334043395334F-2b243.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133404339A1950-302343.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340433a64530-315B3.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340433c02K0-321V9.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340434001S0-3315F.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133404340134G0-345421.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133404340191Z-355N7.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/13340434033L10-362K7.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133404340414460-3N335.jpg{/dede:field}
