{dede:field name='keywords'}怎样穿都好看的折川{/dede:field}
{dede:field name='description'}提供最漂亮的怎样穿都好看的折川{/dede:field}
{dede:field name='title'}怎样穿都好看的折川{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334052aC20Z-1295K.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334052aO9110-134639.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334052a92130-14I62.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334052b031Z-156301.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334052b140450-1EA6.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334052b234250-1JN4.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334052b355M0-1W332.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334052b464K0-1cc0.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/1334052b5P240-20D94.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/1334052bCR20-214642.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/1334052bM9420-2252b.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/1334052bVc50-23P62.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/1334052ba3150-24C51.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/1334052c0WQ0-252348.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/1334052c1X3F-2C491.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/1334052c2T140-2I611.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/1334052aC20Z-1295K_lit.jpg{/dede:field}
