{dede:field name='keywords'}黑色诱惑中村静香{/dede:field}
{dede:field name='description'}提供最漂亮的黑色诱惑中村静香{/dede:field}
{dede:field name='title'}黑色诱惑中村静香{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405450a0N0-1940K.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133405451145910-205938.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340545130050-213614.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133405451455S0-226208.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340545162OP-231W5.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133405451MCZ-24H50.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133405451919E0-255b2.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133405450a0N0-1940K_lit.jpg{/dede:field}
