<?php
$z[0]=Array("field","黑色诱惑中村静香",0,57);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的黑色诱惑中村静香",59,131);
$z[1][4]['name']="description";
$z[2]=Array("field","黑色诱惑中村静香",133,187);
$z[2][4]['name']="title";
$z[3]=Array("field","",189,228);
$z[3][4]['name']="writer";
$z[4]=Array("field","",230,269);
$z[4][4]['name']="source";
$z[5]=Array("field","",271,308);
$z[5][4]['name']="body";
$z[6]=Array("field","",310,350);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405450a0N0-1940K.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133405451145910-205938.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340545130050-213614.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133405451455S0-226208.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340545162OP-231W5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133405451MCZ-24H50.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133405451919E0-255b2.jpg{/dede:img}",352,1223);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133405450a0N0-1940K_lit.jpg",1225,1315);
$z[8][4]['name']="litpic";

?>