<?php
$z[0]=Array("field","浴室,比基尼,美女,美女写真",0,66);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",68,112);
$z[1][4]['name']="description";
$z[2]=Array("field","清纯美女浴室比基尼",114,170);
$z[2][4]['name']="title";
$z[3]=Array("field","",172,211);
$z[3][4]['name']="writer";
$z[4]=Array("field","",213,252);
$z[4][4]['name']="source";
$z[5]=Array("field","",254,294);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",296,333);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2Z1F4350-11ZU.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2Z1I00R0-12Q91.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2Z1J10220-13O12.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2Z1K3T30-145N6.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2Z1M11940-155300.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2Z1O00950-1A205.jpg{/dede:img}",335,1099);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2Z1F4350-11ZU_lit.jpg",1101,1188);
$z[8][4]['name']="litpic";

?>