<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="150";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","http://img.qqsisi.com/allimg/111130/10-111130100400.jpg",187,284);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","http://img.qqsisi.com/allimg/111130/10-111130100402.jpg",286,383);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","http://img.qqsisi.com/allimg/111130/10-111130100404.jpg",385,482);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","http://img.qqsisi.com/allimg/111130/10-111130100407.jpg",484,581);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","http://img.qqsisi.com/allimg/111130/10-111130100409.jpg",583,680);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","http://img.qqsisi.com/allimg/111130/10-111130100411.jpg",682,779);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";

?>