<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","VikiChing比基尼",89,142);
$z[2][4]['name']="title";
$z[3]=Array("field","",144,183);
$z[3][4]['name']="writer";
$z[4]=Array("field","",185,224);
$z[4][4]['name']="source";
$z[5]=Array("field","",226,266);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",268,305);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2cV5aV0-1bJ4.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2cVEJ60-203300.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2cVJAF-21b51.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2cVWbF-229147.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2cV924b0-233214.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2cVbIP-244018.jpg{/dede:img}",307,1063);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2cV5aV0-1bJ4_lit.jpg",1065,1151);
$z[8][4]['name']="litpic";

?>