{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}婧丽可人{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/133412205P4S0-2WB6.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334122061544F-294101.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/133412206491560-302914.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/13341220F01L0-31BT.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/13341220K0D50-323O6.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/13341220OV0-33Y38.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/133412205P4S0-2WB6_lit.jpg{/dede:field}
