{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}阳光微笑{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334121W964460-13Z6.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334121X500340-219A.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/1334121Xc0A0-325S.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334121Y41V60-4I50.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/1334121YZ5260-5LP.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/1334121Z2KE0-BA4.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/1334121Z622c0-G437.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/1334121910b440-T353.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/1334121913AF-92B4.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/1334121W964460-13Z6_lit.jpg{/dede:field}
