{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}砰然心动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334121F453460-1W2N.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334121FL4430-196400.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/1334121G0I310-2023R.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334121G434520-2161P.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/1334121GL33Z-2294Z.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/1334121H0S360-234505.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/1334121H3942Z-24A41.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/1334121HFHF-25G13.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/1334121I025920-2C523.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120411/1334121I35bZ-2I296.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/1334121F453460-1W2N_lit.jpg{/dede:field}
