{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354240U4460P-333117.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354240U4TL0-342250.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354240U510350-353A5.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354240U54320-3CA4.jpg{/dede:img}