<?php
$z[0]=Array("field","越南妞Elly",0,51);
$z[0][4]['name']="keywords";
$z[1]=Array("field","越南妞Elly阮金红",53,113);
$z[1][4]['name']="description";
$z[2]=Array("field","越南妞Elly比基尼新照",115,173);
$z[2][4]['name']="title";
$z[3]=Array("field","",175,214);
$z[3][4]['name']="writer";
$z[4]=Array("field","",216,255);
$z[4][4]['name']="source";
$z[5]=Array("field","",257,297);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",299,336);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/13340430Z59410-95045.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340430915I40-102409.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133404309233O0-114103.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334043093060P-122649.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334043093I930-134445.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334043094E430-146119.jpg{/dede:img}",338,1122);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133404309529140-151494.jpg",1124,1213);
$z[8][4]['name']="litpic";

?>