<?php
$z[0]=Array("field",",",0,42);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",44,88);
$z[1][4]['name']="description";
$z[2]=Array("field","Hello!MyBaby",90,140);
$z[2][4]['name']="title";
$z[3]=Array("field","",142,181);
$z[3][4]['name']="writer";
$z[4]=Array("field","",183,222);
$z[4][4]['name']="source";
$z[5]=Array("field","",224,264);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",266,303);
$z[6][4]['name']="body";
$z[7]=Array("field","",305,344);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424193a2530-61041.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424194022040-HM4.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135424194052260-Y0G.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354241940W140-91356.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424194115550-102059.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135424194155920-1111B.jpg{/dede:img}",346,1126);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135424193a2530-61041_lit.jpg",1128,1219);
$z[9][4]['name']="litpic";

?>