{dede:field name='keywords'}第二,四月,写真,生活,女孩,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美空女孩生活写真四月第二期{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403D1060020-1C41.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403D11H440-2H43.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403D12K960-39514.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403D13D2Z-44J5.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403D14C0P-54349.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403D155N40-B033.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403D163U0-N1D.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403D1H5c0-Q1O.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133403D1P6240-940C.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133403D1W2T0-105562.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133403D1955420-115554.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133403D202XP-121100.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133403D21344P-13W27.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133403D2225240-143b8.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133403D2301420-151631.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133403D240I40-1614F.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/133403D24Q160-1I025.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/133403D2544F-1X0b.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c120410/133403D2623620-1cI6.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c120410/133403D2D5210-2031B.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c120410/133403D2LZZ-2192D.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c120410/133403D2UT40-221a6.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c120410/133403D2954920-231016.jpg{/dede:img}
{dede:img ddimg='' text='图 24'}/uploads/allimg/c120410/133403D30431F-243235.jpg{/dede:img}
{dede:img ddimg='' text='图 25'}/uploads/allimg/c120410/133403D313QP-256028.jpg{/dede:img}
{dede:img ddimg='' text='图 26'}/uploads/allimg/c120410/133403D3225030-262A7.jpg{/dede:img}
{dede:img ddimg='' text='图 27'}/uploads/allimg/c120410/133403D3319520-2O021.jpg{/dede:img}
{dede:img ddimg='' text='图 28'}/uploads/allimg/c120410/133403D33T10-2R451.jpg{/dede:img}
{dede:img ddimg='' text='图 29'}/uploads/allimg/c120410/133403D34V30-2a924.jpg{/dede:img}
{dede:img ddimg='' text='图 30'}/uploads/allimg/c120410/133403D35Q250-303910.jpg{/dede:img}
{dede:img ddimg='' text='图 31'}/uploads/allimg/c120410/133403D3F5P-311363.jpg{/dede:img}
{dede:img ddimg='' text='图 32'}/uploads/allimg/c120410/133403D3MI30-325146.jpg{/dede:img}
{dede:img ddimg='' text='图 33'}/uploads/allimg/c120410/133403D3V4160-33aS.jpg{/dede:img}
{dede:img ddimg='' text='图 34'}/uploads/allimg/c120410/133403D394DF-344120.jpg{/dede:img}
{dede:img ddimg='' text='图 35'}/uploads/allimg/c120410/133403D403UP-35C95.jpg{/dede:img}
{dede:img ddimg='' text='图 36'}/uploads/allimg/c120410/133403D4122460-361247.jpg{/dede:img}
{dede:img ddimg='' text='图 37'}/uploads/allimg/c120410/133403D41b1Z-3KS7.jpg{/dede:img}
{dede:img ddimg='' text='图 38'}/uploads/allimg/c120410/133403D42Ia0-3V020.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133403D43L1P-39B08.jpg{/dede:field}
