<?php
$z[0]=Array("field","美女,美女图片,性感美女,私房",0,68);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",70,114);
$z[1][4]['name']="description";
$z[2]=Array("field","六儿私房",116,162);
$z[2][4]['name']="title";
$z[3]=Array("field","",164,203);
$z[3][4]['name']="writer";
$z[4]=Array("field","",205,244);
$z[4][4]['name']="source";
$z[5]=Array("field","",246,286);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",288,325);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U29422L0110-2151B.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U29423156130-224512.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U29423624B0-23FR.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U29423RYF-24V29.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U294240a4P-25CZ.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U29424635010-2C052.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2942Q54220-2K0G.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U2942SV230-2UC2.jpg{/dede:img}",327,1277);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U29422L0110-2151B_lit.jpg",1279,1369);
$z[8][4]['name']="litpic";

?>