<?php
$z[0]=Array("field","清纯美女真野恵里菜",0,59);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的清纯美女真野恵里菜",61,135);
$z[1][4]['name']="description";
$z[2]=Array("field","清纯美女真野恵里菜",137,193);
$z[2][4]['name']="title";
$z[3]=Array("field","",195,234);
$z[3][4]['name']="writer";
$z[4]=Array("field","",236,275);
$z[4][4]['name']="source";
$z[5]=Array("field","",277,314);
$z[5][4]['name']="body";
$z[6]=Array("field","",316,356);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/13340545VJc0-2XY2.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340545WcW0-2c5R.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340545Y04B0-309520.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340545Yc910-312631.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340545ZcB0-32J03.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133405459216330-334395.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133405459303U0-3453J.jpg{/dede:img}",358,1223);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/13340545VJc0-2XY2_lit.jpg",1225,1313);
$z[8][4]['name']="litpic";

?>