{dede:field name='keywords'}诱惑{/dede:field}
{dede:field name='description'}摄影：黑夜的诱惑{/dede:field}
{dede:field name='title'}摄影：黑夜的诱惑{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402FI29550-3N953.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402FJ5EP-3U0N.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402FK360Z-393Q2.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402FL351F-40PP.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402FMN20-415O5.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402FNC3F-422507.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402FOU030-43N21.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133402FQ105Z-446148.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133402FR161Z-45R10.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133402FS091F-461926.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133402FT4C10-4G1a.jpg{/dede:field}
