<?php
$z[0]=Array("field","曾恺玹",0,47);
$z[0][4]['name']="keywords";
$z[1]=Array("field","台湾广告宠儿曾恺玹真人示范，如何呈现清纯性感妆容，让你随时随地散发百分百小女人风情。",49,177);
$z[1][4]['name']="description";
$z[2]=Array("field","曾恺玹性感图片",179,231);
$z[2][4]['name']="title";
$z[3]=Array("field","",233,272);
$z[3][4]['name']="writer";
$z[4]=Array("field","",274,313);
$z[4][4]['name']="source";
$z[5]=Array("field","",315,355);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",357,394);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402320X930-355015.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402320ba0-362B9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402321063550-3I0c.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402321144040-3XA7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402321230G0-392041.jpg{/dede:img}",396,1082);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/1334023212a320-406421.jpg",1084,1172);
$z[8][4]['name']="litpic";

?>