{dede:field name='keywords'}曾恺玹{/dede:field}
{dede:field name='description'}台湾广告宠儿曾恺玹真人示范，如何呈现清纯性感妆容，让你随时随地散发百分百小女人风情。{/dede:field}
{dede:field name='title'}曾恺玹性感图片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402320X930-355015.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402320ba0-362B9.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402321063550-3I0c.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402321144040-3XA7.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402321230G0-392041.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/1334023212a320-406421.jpg{/dede:field}
