<?php
$z[0]=Array("field",",",0,42);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",44,88);
$z[1][4]['name']="description";
$z[2]=Array("field","宝杈白冰",90,136);
$z[2][4]['name']="title";
$z[3]=Array("field","",138,177);
$z[3][4]['name']="writer";
$z[4]=Array("field","",179,218);
$z[4][4]['name']="source";
$z[5]=Array("field","",220,260);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",262,299);
$z[6][4]['name']="body";
$z[7]=Array("field","",301,340);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542419321IF-11I5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354241932U050-23037.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542419330M20-33I1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354241933533F-45540.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354241933c550-534E.jpg{/dede:img}",342,1025);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/13542419321IF-11I5_lit.jpg",1027,1116);
$z[9][4]['name']="litpic";

?>