<?php
$z[0]=Array("field","清纯90后学生妹,甜美诱惑户外清",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供清纯90后学生妹 甜美诱惑户外清凉夏日写真。",72,171);
$z[1][4]['name']="description";
$z[2]=Array("field","清纯90后学生妹 甜美诱惑户外清凉夏日写真",173,250);
$z[2][4]['name']="title";
$z[3]=Array("field","",252,291);
$z[3][4]['name']="writer";
$z[4]=Array("field","",293,332);
$z[4][4]['name']="source";
$z[5]=Array("field","",334,374);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",376,413);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B20I6030-305H0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B20QJF-31ZO.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B20U0c0-32S22.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B20XTZ-334V9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629B20931V0-34HM.jpg{/dede:img}",415,1090);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629B20I6030-305H0_lit.jpg",1092,1182);
$z[8][4]['name']="litpic";

?>