{dede:field name='keywords'}佐佐木希，天使魔鬼诱惑{/dede:field}
{dede:field name='description'}日本模特佐佐木希，一个拥有天使面庞和魔鬼身材的女生，不仅演电影，出唱片，近期又拍摄了一组黑白内衣照，你喜欢恬静纯洁的白色内衣，还是更倾心于神秘性感的黑色内衣呢？{/dede:field}
{dede:field name='title'}佐佐木希黑白内衣天使魔鬼诱惑{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424003O94F-2525a.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424003V30Z-262056.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542400394J60-2IN5.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424003c92F-2U2P.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424004052b0-2a319.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542400410E60-306015.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424004160540-316319.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/13542400420K10-321444.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354240042635P-3393O.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354240043231P-3443V.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354240043OX0-355029.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/135424004434360-364V4.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/13542400450F20-3N034.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135424003O94F-2525a_lit.jpg{/dede:field}
