{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/13340429200RF-11C06.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340429219110-122E2.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133404292255210-13NP.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340429232K50-144153.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404292394310-152541.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334042924594Z-1A1N.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133404292542550-1L4Z.jpg{/dede:img}