{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B23533110-193O.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B235B640-24G5.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B2359B10-36411.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B2361c60-415D.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629B2364I40-5c12.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629B23G520-A452.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629B23OM10-O309.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629B23Y910-YK6.jpg{/dede:img}