{dede:field name='keywords'}清秀女孩的衣装秀写真{/dede:field}
{dede:field name='description'}美桌图片库提供清秀女孩的衣装秀写真。{/dede:field}
{dede:field name='title'}清秀女孩的衣装秀写真{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629AA21RZ-150O.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629AA21RZ-150O.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629AA2FX0-2W03.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629AA303A0-36319.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629AA342140-41601.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629AA392430-51G3.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629AA41LP-C112.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629AA455K0-OY2.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c130311/13629AA4Z260-Y234.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c130311/13629AA5193P-94415.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c130311/13629AA554910-1063F.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c130311/13629AA601B0-113307.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c130311/13629AA63N40-129264.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c130311/13629AABJZ-13H63.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c130311/13629AAG350-14AS.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c130311/13629AAJbF-155524.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c130311/13629AAN5W0-1C5W.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c130311/13629AAR0530-1N1V.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c130311/13629AAVVF-1V015.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c130311/13629AA92YZ-1a3P.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c130311/13629AA95K20-201543.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c130311/13629AA21RZ-150O_lit.jpg{/dede:field}
