<?php
$z[0]=Array("sppage","{path}{file}_{p}{ext}",0,83);
$z[0][4]['sptype']="diyrule";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.taoqao.com/wangshangkaidian/wdhy/20120617/15697.html",85,183);
$z[2]=Array("keywordtrim","",185,222);
$z[3]=Array("descriptiontrim","",224,269);
$z[4]=Array("item","\r\n   {dede:match}<H1>[ÄÚÈÝ]</H1>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",271,425);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",425,565);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",565,705);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",705,846);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<DIV id=entrybody>[ÄÚÈÝ]<div class=\"dede_pages\"{/dede:match}\r\n   {dede:trim replace=''}<a([^>]*)>{/dede:trim}\r\n{dede:trim replace=''}</a>{/dede:trim}\r\n{dede:trim replace=''}<script([^>]*)>(.*)</script>{/dede:trim}\r\n{dede:trim replace=''}<!--(.*)-->{/dede:trim}\r\n{dede:trim replace=''}<style([^>]*)>(.*)</style>{/dede:trim}\r\n{dede:trim replace=''}<div([^.]*)>{/dede:trim}\r\n{dede:trim replace=''}</div>{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",846,1380);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>