<?php
$z[0]=Array("field","宅男,美女,性感美女,比基尼",0,66);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",68,112);
$z[1][4]['name']="description";
$z[2]=Array("field","宅男女神",114,160);
$z[2][4]['name']="title";
$z[3]=Array("field","",162,201);
$z[3][4]['name']="writer";
$z[4]=Array("field","",203,242);
$z[4][4]['name']="source";
$z[5]=Array("field","",244,284);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",286,323);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2a95Q2340-14I10.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2a95Z9350-15Z58.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2a95a1950-1B1W.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2a96045260-1HS9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2a96102460-1V132.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2a961GL0-19BT.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2a96240a0-2091M.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U2a963142F-211956.jpg{/dede:img}",325,1271);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2a95Q2340-14I10_lit.jpg",1273,1362);
$z[8][4]['name']="litpic";

?>