{dede:field name='keywords'}宅男,美女,性感美女,比基尼{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}宅男女神{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2a95Q2340-14I10.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2a95Z9350-15Z58.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2a95a1950-1B1W.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2a96045260-1HS9.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2a96102460-1V132.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2a961GL0-19BT.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2a96240a0-2091M.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U2a963142F-211956.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c131124/13U2a95Q2340-14I10_lit.jpg{/dede:field}
