{dede:field name='keywords'}何静{/dede:field}
{dede:field name='description'}何静学生照{/dede:field}
{dede:field name='title'}何静性感学生照{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424050T5T0-40O49.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424050Z3H0-411c9.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354240509515F-422142.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424050b4U0-43I01.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424051025920-4420V.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354240510B5Z-456128.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424051113940-4625Q.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135424051160240-4HD1.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354240511a640-4X124.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135424050T5T0-40O49_lit.jpg{/dede:field}
