<?php
$z[0]=Array("field","性感美女,美女私房,美女",0,63);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",65,109);
$z[1][4]['name']="description";
$z[2]=Array("field","诱人美女曼妙身材性感床照",111,173);
$z[2][4]['name']="title";
$z[3]=Array("field","",175,214);
$z[3][4]['name']="writer";
$z[4]=Array("field","",216,255);
$z[4][4]['name']="source";
$z[5]=Array("field","",257,297);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",299,336);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2UN931240-151253.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2UO160B0-163D0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2UO3J0F-1M531.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2UO4Y4F-1RS7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2UO641N0-195a7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2UO91520-2020O.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2UP030Q0-215919.jpg{/dede:img}",338,1188);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2UN931240-151253_lit.jpg",1190,1280);
$z[8][4]['name']="litpic";

?>