{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354240Uc3Y0-11503.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354240V063220-29433.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354240V11E50-32C6.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354240V15S40-42A3.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354240V20420-51917.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354240V24O50-61315.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354240V2Y4Z-LP9.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354240V34020-Y019.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354240V395350-a4U.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354240V44D20-104522.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354240V504L0-113O9.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/1354240V550020-122153.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/1354240V595J0-131292.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/1354240VAWF-142Q6.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/1354240VG54P-159408.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/1354240VKU60-1E441.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c121130/1354240Uc3Y0-11503.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c121130/1354240V063220-29433.jpg{/dede:img}