{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/190710/1-1ZG0150418.jpg' text='' width='1280' height='960'} /uploads/allimg/190710/1-1ZG0150418.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190710/1-1ZG0150419.jpg' text='' width='1280' height='960'} /uploads/allimg/190710/1-1ZG0150419.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190710/1-1ZG0150420.jpg' text='' width='959' height='1280'} /uploads/allimg/190710/1-1ZG0150420.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190710/1-1ZG0150423.jpg' text='' width='959' height='1280'} /uploads/allimg/190710/1-1ZG0150423.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190710/1-1ZG0150426.jpg' text='' width='959' height='1280'} /uploads/allimg/190710/1-1ZG0150426.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190710/1-1ZG0150429.jpg' text='' width='959' height='1280'} /uploads/allimg/190710/1-1ZG0150429.jpg {/dede:img}
