<?php
$z[0]=Array("field","高清美女,美女写真,性感美女,美",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",72,116);
$z[1][4]['name']="description";
$z[2]=Array("field","白糖水的近距离",118,170);
$z[2][4]['name']="title";
$z[3]=Array("field","",172,211);
$z[3][4]['name']="writer";
$z[4]=Array("field","",213,252);
$z[4][4]['name']="source";
$z[5]=Array("field","",254,294);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",296,333);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2X104244P-1X57.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2X11221530-254G.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2X1143Q40-32241.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2X11T0060-4AU.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2X119C2F-5Z24.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2X1230JZ-E344.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2X124N50-L602.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U2X13O9D0-S4U.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 9'}/uploads/allimg/c131124/13U2X1G633F-931Y.jpg{/dede:img}",335,1358);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2X104244P-1X57_lit.jpg",1360,1448);
$z[8][4]['name']="litpic";

?>