{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}如真如幻{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334121K061510-2V000.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334121K454410-291201.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/1334121KC560-303J2.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334121KWRZ-31V27.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/1334121L1b020-325113.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/1334121LZ1M0-33GX.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/1334121M5Q640-341341.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/1334121N191T0-3592C.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/1334121N956460-3B2Y.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120411/1334121O5YR0-3G428.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/1334121K061510-2V000_lit.jpg{/dede:field}
