{dede:field name='keywords'}美女,第一,奥运,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}北京奥运看台第一美女任斯璐{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334041WIZ10-c1Q.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334041WQZ-104242.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/1334041WY1N0-115461.jpg{/dede:field}
