<?php
$z[0]=Array("field","美女,第一,奥运,,",0,57);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",59,103);
$z[1][4]['name']="description";
$z[2]=Array("field","北京奥运看台第一美女任斯璐",105,169);
$z[2][4]['name']="title";
$z[3]=Array("field","",171,210);
$z[3][4]['name']="writer";
$z[4]=Array("field","",212,251);
$z[4][4]['name']="source";
$z[5]=Array("field","",253,293);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",295,332);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334041WIZ10-c1Q.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334041WQZ-104242.jpg{/dede:img}",334,738);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/1334041WY1N0-115461.jpg",740,826);
$z[8][4]['name']="litpic";

?>