<?php
$z[0]=Array("field","性感美女,美女私房,美女DJ",0,65);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",67,111);
$z[1][4]['name']="description";
$z[2]=Array("field","DJ莹莹",113,157);
$z[2][4]['name']="title";
$z[3]=Array("field","",159,198);
$z[3][4]['name']="writer";
$z[4]=Array("field","",200,239);
$z[4][4]['name']="source";
$z[5]=Array("field","",241,281);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",283,320);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2UY5R050-1SP0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2UYC0060-1a406.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2UYK3960-2044a.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2UYS23F-215027.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2UYZOF-2242E.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2UYa61F-231339.jpg{/dede:img}",322,1080);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2UY5R050-1SP0_lit.jpg",1082,1169);
$z[8][4]['name']="litpic";

?>