<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="235";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","/uploads/allimg/c131124/13U2c9520S50-19404.jpg",187,275);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","/uploads/allimg/c131124/13U2c956210F-293E.jpg",277,364);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","/uploads/allimg/c131124/13U2c95MYP-34O6.jpg",366,451);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","/uploads/allimg/c131124/13U2c963IH0-44635.jpg",453,540);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","/uploads/allimg/c131124/13U2c96423220-5A08.jpg",542,630);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","/uploads/allimg/c131124/13U2caQY0-E040.jpg",632,716);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";
$z[8]=Array("img","/uploads/allimg/c131124/13U2caY430-N931.jpg",718,803);
$z[8][4]['ddimg']="";
$z[8][4]['text']="图 7";

?>