{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424421c620-344521.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424422101450-35F95.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135424422193130-3D0D.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354244222T220-3HY6.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354244223I20-3X464.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354244224C920-3a364.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424422Q1E0-404c4.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135424422YLF-411533.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/135424422b4060-423206.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354244230I260-4392L.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/13542442315aP-444128.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/135424423249120-451347.jpg{/dede:img}