<?php
$z[0]=Array("field","流年",0,45);
$z[0][4]['name']="keywords";
$z[1]=Array("field","摄影作品：流年",47,105);
$z[1][4]['name']="description";
$z[2]=Array("field","摄影作品：流年",107,159);
$z[2][4]['name']="title";
$z[3]=Array("field","",161,200);
$z[3][4]['name']="writer";
$z[4]=Array("field","",202,241);
$z[4][4]['name']="source";
$z[5]=Array("field","",243,283);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",285,322);
$z[6][4]['name']="body";
$z[7]=Array("field","",324,363);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423Y204S60-1E5B.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423Y20913Z-1G436.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423Y21394F-1X3c.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423Y21M350-191059.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423Y22211P-202616.jpg{/dede:img}",365,1047);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423Y204S60-1E5B_lit.jpg",1049,1138);
$z[9][4]['name']="litpic";

?>