{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2X22303160-1615A.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2X224B4F-1MD2.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2X2255UP-1S2O.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2X22E2O0-1aG2.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2X22R04Z-20Y06.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2X23146110-21KW.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2X23321020-224447.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U2X23610640-232W9.jpg{/dede:img}