{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334031K142950-49A43.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334031K3UM0-503059.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334031KB2250-5111O.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334031KX0T0-52L93.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334031L1050Z-534152.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334031L292410-542240.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334031L4S60-552347.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334031LDE10-5Bc8.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/1334031M06050-5NT9.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/1334031M3O320-5R4J.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/1334031MI95F-594U5.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/1334031N162E0-60G42.jpg{/dede:img}