<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","芦苇中甜美",89,137);
$z[2][4]['name']="title";
$z[3]=Array("field","",139,178);
$z[3][4]['name']="writer";
$z[4]=Array("field","",180,219);
$z[4][4]['name']="source";
$z[5]=Array("field","",221,261);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",263,300);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U292L9605F-1V32.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U292Lc3a0-291V.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U292M204b0-335W.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U292M24IP-41315.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U292M502P-52649.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U292M53130-61943.jpg{/dede:img}",302,1063);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U292L9605F-1V32_lit.jpg",1065,1153);
$z[8][4]['name']="litpic";

?>