<?php
$z[0]=Array("sppage","",0,59);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.meizu.com/services/questionContent.html?questionId=518062",61,164);
$z[2]=Array("keywordtrim","(.*)",166,207);
$z[3]=Array("descriptiontrim","(.*)",209,258);
$z[4]=Array("item","\r\n   {dede:match}<title>[内容]</title>{/dede:match}\r\n   {dede:trim replace=\"\"}-服务支持{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",260,463);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",463,603);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",603,743);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",743,884);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<span class=\"header\">[内容]<div class=\"userInfo\">{/dede:match}\r\n   {dede:trim replace=\"\"}<a([^>]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</a>{/dede:trim}\r\n{dede:trim replace=\"\"}<script([^>]*)>(.*)</script>{/dede:trim}\r\n{dede:trim replace=\"\"}<!--(.*)-->{/dede:trim}\r\n{dede:trim replace=\"\"}<table([^>]*)>(.*)</table>{/dede:trim}\r\n{dede:trim replace=\"\"}<iframe([^>]*)>(.*)</iframe>{/dede:trim}\r\n{dede:trim replace=\"\"}<span class=\"askedInfo\">(.*)<div class=\"blank5\">{/dede:trim}\r\n{dede:trim replace=\"\"}<form([^>]*)>(.*)</form>{/dede:trim}\r\n{dede:trim replace=\"\"}<div([^.]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</div>{/dede:trim}\r\n{dede:trim replace=\"\"}<span([^.]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</span>{/dede:trim}\r\n{dede:trim replace=\"\"}<input([^>]*)/>{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",884,1771);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>