<?php
$z[0]=Array("field","S型女孩完美身材曲线写真",0,64);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供S型女孩完美身材曲线写真。",66,149);
$z[1][4]['name']="description";
$z[2]=Array("field","S型女孩完美身材曲线写真",151,212);
$z[2][4]['name']="title";
$z[3]=Array("field","",214,253);
$z[3][4]['name']="writer";
$z[4]=Array("field","",255,294);
$z[4][4]['name']="source";
$z[5]=Array("field","",296,336);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",338,375);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A4351LZ-45S02.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A43554950-4E1J.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A435A20-4M216.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A435Z20-4S609.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A43615510-492100.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A43640930-503930.jpg{/dede:img}",377,1151);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A4351LZ-45S02_lit.jpg",1153,1242);
$z[8][4]['name']="litpic";

?>