<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="235";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","/uploads/allimg/c131124/13U29196064140-91258.jpg",187,277);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","/uploads/allimg/c131124/13U29196102240-103X6.jpg",279,369);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","/uploads/allimg/c131124/13U291a21Q10-115607.jpg",371,460);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","/uploads/allimg/c131124/13U291a3c920-12ZQ.jpg",462,549);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","/uploads/allimg/c131124/13U291a421H0-13V31.jpg",551,639);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","/uploads/allimg/c131124/13U291a5E330-144E3.jpg",641,729);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";
$z[8]=Array("img","/uploads/allimg/c131124/13U291a63W30-152146.jpg",731,820);
$z[8][4]['ddimg']="";
$z[8][4]['text']="图 7";
$z[9]=Array("img","/uploads/allimg/c131124/13U291aJ5040-1A200.jpg",822,910);
$z[9][4]['ddimg']="";
$z[9][4]['text']="图 8";

?>