{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629AZB2S0-10Q22.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629AZG2620-115D9.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629AZKT20-129207.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629AZO10Z-13XY.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629AZRD50-14Q48.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629AZU5Y0-151127.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629AZXc10-1C4Z.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629AZ92GF-1OD8.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c130311/13629AZ960S0-1Q3c.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c130311/13629AZc050-1911D.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c130311/13629A9102JF-20T30.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c130311/13629A9105C50-21X01.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c130311/13629A910W0F-222016.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c130311/13629A911140Z-231603.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c130311/13629A91143030-2494J.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c130311/13629A911E5F-253404.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c130311/13629A911b310-2633A.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c130311/13629A91220K0-2O193.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c130311/13629A91305440-2Q359.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c130311/13629A91404J0-2bW3.jpg{/dede:img}