<?php
$z[0]=Array("field","大片,最新,,",0,52);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",54,98);
$z[1][4]['name']="description";
$z[2]=Array("field","景甜最新大片",100,150);
$z[2][4]['name']="title";
$z[3]=Array("field","",152,191);
$z[3][4]['name']="writer";
$z[4]=Array("field","",193,232);
$z[4][4]['name']="source";
$z[5]=Array("field","",234,274);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",276,313);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133404193221520-91Z1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133404193296140-10H02.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133404193434010-114050.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334041936250Z-125N5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404193MN0-13J58.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133404193TN0-144091.jpg{/dede:img}",315,1094);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/13340419391V0-152B9.jpg",1096,1182);
$z[8][4]['name']="litpic";

?>