{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133404GPTB0-411341.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133404GSbb0-42M46.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133404GVV2Z-434205.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133404GYB240-449623.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404G9249360-45bK.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133404G9544250-4643G.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133404Ga94150-4H558.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133404H00N50-4V144.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133404H03591F-492635.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133404H0595140-50XN.jpg{/dede:img}