<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="235";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","/uploads/allimg/c131124/13U293C061420-M0B.jpg",187,274);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","/uploads/allimg/c131124/13U293C259130-T603.jpg",276,364);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","/uploads/allimg/c131124/13U293C293230-96491.jpg",366,455);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","/uploads/allimg/c131124/13U293C43X40-10Q95.jpg",457,545);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","/uploads/allimg/c131124/13U293C4E440-11W05.jpg",547,635);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","/uploads/allimg/c131124/13U293CS0a0-122B3.jpg",637,724);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";
$z[8]=Array("img","/uploads/allimg/c131124/13U293CTLF-1341Y.jpg",726,812);
$z[8][4]['ddimg']="";
$z[8][4]['text']="图 7";
$z[9]=Array("img","/uploads/allimg/c131124/13U293C9352F-144060.jpg",814,903);
$z[9][4]['ddimg']="";
$z[9][4]['text']="图 8";
$z[10]=Array("img","/uploads/allimg/c131124/13U293C95HF-1555I.jpg",905,992);
$z[10][4]['ddimg']="";
$z[10][4]['text']="图 9";

?>