<?php
$z[0]=Array("field","夏日清爽外拍,甜美女孩",0,62);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供夏日清爽外拍 甜美女孩。",64,145);
$z[1][4]['name']="description";
$z[2]=Array("field","夏日清爽外拍 甜美女孩",147,206);
$z[2][4]['name']="title";
$z[3]=Array("field","",208,247);
$z[3][4]['name']="writer";
$z[4]=Array("field","",249,288);
$z[4][4]['name']="source";
$z[5]=Array("field","",290,330);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",332,369);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A32344360-2T521.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A32344360-2T521.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A323L340-2b4C.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A3240O60-301457.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A324311Z-31bX.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A3245D40-32Y61.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629A324R020-33a10.jpg{/dede:img}",371,1236);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A32344360-2T521_lit.jpg",1238,1329);
$z[8][4]['name']="litpic";

?>