<?php
$z[0]=Array("field","甘薇",0,45);
$z[0][4]['name']="keywords";
$z[1]=Array("field","甘薇恬静尽显清丽 影视新秀甘薇清丽恬静写真曝光，写真中甘薇化身白色精灵，清澈眼神令人动容，纯净之美展露无疑。她一贯坚持自己的清纯淡雅风，并得到一致认可。",47,242);
$z[1][4]['name']="description";
$z[2]=Array("field","甘薇恬静尽显清丽",244,298);
$z[2][4]['name']="title";
$z[3]=Array("field","",300,339);
$z[3][4]['name']="writer";
$z[4]=Array("field","",341,380);
$z[4][4]['name']="source";
$z[5]=Array("field","",382,422);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",424,461);
$z[6][4]['name']="body";
$z[7]=Array("field","",463,502);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542391003330-5B327.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354239100922P-5M0X.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423910123E0-5T0F.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354239101OY0-5a238.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423910234040-6014T.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354239102D040-6110I.jpg{/dede:img}",504,1281);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/13542391003330-5B327_lit.jpg",1283,1374);
$z[9][4]['name']="litpic";

?>