{dede:field name='keywords'}甘薇{/dede:field}
{dede:field name='description'}甘薇恬静尽显清丽 影视新秀甘薇清丽恬静写真曝光，写真中甘薇化身白色精灵，清澈眼神令人动容，纯净之美展露无疑。她一贯坚持自己的清纯淡雅风，并得到一致认可。{/dede:field}
{dede:field name='title'}甘薇恬静尽显清丽{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542391003330-5B327.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354239100922P-5M0X.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423910123E0-5T0F.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354239101OY0-5a238.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423910234040-6014T.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354239102D040-6110I.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/13542391003330-5B327_lit.jpg{/dede:field}
