{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405435314040-343933.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133405435434H0-3554b.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133405435522360-3BJ9.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334054356064P-3O013.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133405435E0O0-3R2J.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133405435NU0-3c326.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133405435W9520-4063X.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133405435aD0-41O26.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/1334054360I5F-422933.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/1334054361Z30-435422.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133405436305R0-44LM.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/13340543640410-456036.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/13340543A04U0-4C4L.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/13340543B23S0-4K4Q.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/13340543C25R0-4T4Q.jpg{/dede:img}