<?php
$z[0]=Array("noteinfo","",2,159);
$z[0][4]['notename']="Õ¾¿á-¾­Ñé";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div>{/dede:areastart}\r\n    {dede:areaend}</div>{/dede:areaend}\r\n",161,615);
$z[1][4]['sourcetype']="rss";
$z[1][4]['rssurl']="http://fknet.cn/chanjilink.html";
$z[1][4]['regxurl']="http://www.zcool.com.cn/articles/322!325!200!2!(*)!0!0!2/";
$z[1][4]['startid']="1";
$z[1][4]['endid']="1";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']=".html";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="0";
$z[1][4]['usemore']="0";

?>