{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334041Z406360-2542V.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334041Z4N5F-2ER0.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334041Z55140-2I462.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334041Z595O0-2S160.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334041Z64Z50-291191.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334041ZH2930-30O16.jpg{/dede:img}