{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334022JDWF-113Y1.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334022JN54F-125296.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334022JW0460-1354a.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334022Ja14Z-14MI.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334022K0a230-15O58.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334022K1942Z-1612I.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334022K2b130-1KS3.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334022K424S0-1U318.jpg{/dede:img}