{dede:field name='keywords'}完美身材秋山莉奈{/dede:field}
{dede:field name='description'}提供最漂亮的完美身材秋山莉奈{/dede:field}
{dede:field name='title'}完美身材秋山莉奈{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424462026010-415401.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424462144930-421R5.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135424462236350-431937.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424462334S0-445600.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542446243360-452a1.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354244625314P-4C351.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424462630040-4G260.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135424462HX50-4R018.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/135424462RE10-49B43.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/135424462925130-5034N.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/135424463031020-512243.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/13542446312X50-52E31.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/135424463219640-532226.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/13542446331P-54C11.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/13542446341CP-5563L.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/135424463516010-563360.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c121130/135424463621W0-5G116.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c121130/135424463G2K0-5R363.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c121130/135424463Q2K0-5bQ6.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c121130/135424463910150-602V3.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c121130/13542446400TP-613350.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c121130/135424464113a0-62b20.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c121130/135424464204930-639350.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135424462026010-415401_lit.jpg{/dede:field}
