<?php
$z[0]=Array("field","服饰,,",0,47);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",49,93);
$z[1][4]['name']="description";
$z[2]=Array("field","农家服饰的天仙MM",95,149);
$z[2][4]['name']="title";
$z[3]=Array("field","",151,190);
$z[3][4]['name']="writer";
$z[4]=Array("field","",192,231);
$z[4][4]['name']="source";
$z[5]=Array("field","",233,273);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",275,312);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/13340429200RF-11C06.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340429219110-122E2.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133404292255210-13NP.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340429232K50-144153.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404292394310-152541.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334042924594Z-1A1N.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133404292542550-1L4Z.jpg{/dede:img}",314,1186);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133404292632M0-1Q5Y.jpg",1188,1274);
$z[8][4]['name']="litpic";

?>