{dede:field name='keywords'}夏日OL{/dede:field}
{dede:field name='description'}最潮夏日OL气质职业裙{/dede:field}
{dede:field name='title'}最潮夏日OL气质职业裙{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403R101920-316096.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403R1115Q0-323V1.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403R1196240-33NU.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403R1251B0-3413V.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403R1310K0-35V00.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403R13912Z-3AE6.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403R145H50-3GA7.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403R1533050-3XA6.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133403R160K30-3cF2.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133403R1F9620-406454.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133403R1O02F-41H50.jpg{/dede:field}
