{dede:field name='keywords'}娇嫩气质的青春美少女{/dede:field}
{dede:field name='description'}美桌图片库提供娇嫩气质的青春美少女。{/dede:field}
{dede:field name='title'}娇嫩气质的青春美少女{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A22293R0-O216.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A22324540-W544.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A22354S0-930A.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A22395550-101594.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A22430F-112A7.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A224O1F-1231V.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c130311/13629A22293R0-O216_lit.jpg{/dede:field}
