<?php
$z[0]=Array("field","董璇",0,45);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",47,91);
$z[1][4]['name']="description";
$z[2]=Array("field","董璇变身成最闪耀的足球宝贝",93,157);
$z[2][4]['name']="title";
$z[3]=Array("field","",159,198);
$z[3][4]['name']="writer";
$z[4]=Array("field","",200,239);
$z[4][4]['name']="source";
$z[5]=Array("field","",241,281);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",283,320);
$z[6][4]['name']="body";
$z[7]=Array("field","",322,361);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424043I5240-14214.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424043N4120-2cU.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135424043R20P-355H.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424043V1E0-45R9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424043Z0630-5L57.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135424043942360-D509.jpg{/dede:img}",363,1135);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135424043I5240-14214_lit.jpg",1137,1228);
$z[9][4]['name']="litpic";

?>