{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405295215T0-19150.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340529541C10-2C61.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334052955CN0-31G4.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133405295H01F-412L.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133405295W5220-5E22.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133405296042940-63128.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334052961Q2Z-IG7.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/13340529634JF-U140.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/1334052964W430-cS5.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/13340529B26020-1021C.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/13340529CN320-11Z30.jpg{/dede:img}