<?php
$z[0]=Array("field","清纯美少女,比基尼美乳诱惑",0,66);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供清纯美少女 比基尼美乳诱惑。",68,153);
$z[1][4]['name']="description";
$z[2]=Array("field","清纯美少女   比基尼美乳诱惑",155,220);
$z[2][4]['name']="title";
$z[3]=Array("field","",222,261);
$z[3][4]['name']="writer";
$z[4]=Array("field","",263,302);
$z[4][4]['name']="source";
$z[5]=Array("field","",304,344);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",346,383);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B01321330-14XO.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B01321330-14XO.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B013K120-152403.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B0141MF-1A3D.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629B0145OP-1L037.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629B0150450-1S036.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629B01550260-1aV0.jpg{/dede:img}",385,1247);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629B01321330-14XO_lit.jpg",1249,1339);
$z[8][4]['name']="litpic";

?>