<?php
$z[0]=Array("field","女人,精致,,",0,52);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",54,98);
$z[1][4]['name']="description";
$z[2]=Array("field","精致小女人",100,148);
$z[2][4]['name']="title";
$z[3]=Array("field","",150,189);
$z[3][4]['name']="writer";
$z[4]=Array("field","",191,230);
$z[4][4]['name']="source";
$z[5]=Array("field","",232,272);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",274,311);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334022623SY0-394940.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402262533030-409355.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402262B4N0-414V2.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402262OH50-422W9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334022629244P-434F7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402263049E0-444639.jpg{/dede:img}",313,1093);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/1334022631Q410-451950.jpg",1095,1183);
$z[8][4]['name']="litpic";

?>