{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334022623SY0-394940.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402262533030-409355.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402262B4N0-414V2.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402262OH50-422W9.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334022629244P-434F7.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402263049E0-444639.jpg{/dede:img}