{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403QL931P-163449.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403QMK10-1MT8.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403QNA4P-1Y306.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403QO2C10-1b3G.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403QO94T0-20X37.jpg{/dede:img}