<?php
$z[0]=Array("field","陶昕然",0,47);
$z[0][4]['name']="keywords";
$z[1]=Array("field","陶昕然，湖南人，演员。清新淡雅，温婉大气，曾出演多部电影电视剧。",49,157);
$z[1][4]['name']="description";
$z[2]=Array("field","陶昕然优雅写真",159,211);
$z[2][4]['name']="title";
$z[3]=Array("field","",213,252);
$z[3][4]['name']="writer";
$z[4]=Array("field","",254,293);
$z[4][4]['name']="source";
$z[5]=Array("field","",295,335);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",337,374);
$z[6][4]['name']="body";
$z[7]=Array("field","",376,415);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423X4PA50-1V39.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423X4UK20-2NN.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423X4Y0340-3H92.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423X492C40-45491.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423X4c0R0-53A7.jpg{/dede:img}",417,1091);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423X4PA50-1V39_lit.jpg",1093,1181);
$z[9][4]['name']="litpic";

?>