{dede:field name='keywords'}清纯可爱的妞妞美图{/dede:field}
{dede:field name='description'}美桌图片库提供清纯可爱的妞妞美图。{/dede:field}
{dede:field name='title'}清纯可爱的妞妞美图{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A45350450-1E135.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A453V0-1K1Q.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A4541D0-1Y547.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A4542K10-1b130.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A45450160-20V05.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A454JK0-212212.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629A454T630-222R3.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629A4550XF-23K12.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c130311/13629A45519510-246400.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c130311/13629A45541Z-25WT.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c130311/13629A455BQ0-2DH2.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c130311/13629A455ZV0-2HJ1.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c130311/13629A456155F-2X3Z.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c130311/13629A456415Z-2bW1.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c130311/13629A45A2020-309592.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c130311/13629A45C4I0-314604.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c130311/13629A45D2c0-325A6.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c130311/13629A45F43P-333Y0.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c130311/13629A45I25F-349303.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c130311/13629A45J22F-353H2.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c130311/13629A45350450-1E135_lit.jpg{/dede:field}
