{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U29323295120-2Vc3.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U29323542430-2935D.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U29323600340-301T0.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2932545E40-313248.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U29325512140-3233Q.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U29325JJ60-335A7.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U29325LK60-34R64.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U2932E3R30-35B07.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c131124/13U2932EN530-3E103.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c131124/13U2932L25M0-3M9D.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c131124/13U2932L92C0-3Q0S.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c131124/13U2932R3010-39A19.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c131124/13U2932R5a0-401c6.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c131124/13U2932X62540-415053.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c131124/13U29332156420-429347.jpg{/dede:img}