{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334121345912F-339126.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/133412134933150-341159.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/133412135243960-35K41.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334121355L620-3E217.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/133412135ZO10-3O453.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/13341213621H50-3SN4.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/13341213A22V0-395050.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/13341213D51N0-409101.jpg{/dede:img}