<?php
$z[0]=Array("field","比基尼,美女图片,性感美女",0,65);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",67,111);
$z[1][4]['name']="description";
$z[2]=Array("field","阳光沙滩比基尼",113,165);
$z[2][4]['name']="title";
$z[3]=Array("field","",167,206);
$z[3][4]['name']="writer";
$z[4]=Array("field","",208,247);
$z[4][4]['name']="source";
$z[5]=Array("field","",249,289);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",291,328);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2Z1920A20-226092.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2Z19410140-23G56.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2Z19DF50-24T56.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2Z1bFL0-25M42.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2Z201L3P-263b8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2Z204G0-2OS4.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2Z20HY10-2W4K.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U2Z20911920-295055.jpg{/dede:img}",330,1272);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2Z1920A20-226092_lit.jpg",1274,1364);
$z[8][4]['name']="litpic";

?>