<?php
$z[0]=Array("field","",370,389);
$z[0][4]['name']="title";
$z[1]=Array("global","",390,416);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",457,486);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",526,584);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",865,902);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("field","",973,992);
$z[5][4]['name']="title";
$z[6]=Array("type","\r\n<span> <a href=\"[field:typelink /]\">[field:typename /]</a> </span>\r\n",999,1092);
$z[7]=Array("field","<img src=\"[field:imgsrc/]\" />",1182,1268);
$z[7][4]['name']="imgurls";
$z[7][4]['alt']="Í¼Æ¬Êä³öÇø";
$z[8]=Array("pagebreak","",1315,1332);
$z[9]=Array("prenext","",1401,1426);
$z[9][4]['get']="pre";
$z[10]=Array("prenext","",1438,1464);
$z[10][4]['get']="next";
$z[11]=Array("arclist","\r\n<li><a href='view.php?aid=[field:id/]' title=\"[field:title/] \"><img src=\"[field:litpic/] \" alt=\"[field:title/] \"></a><p><a href='view.php?aid=[field:id/]'>[field:title/] </a></p></li>\r\n",1633,1889);
$z[11][4]['flag']="";
$z[11][4]['typeid']="";
$z[11][4]['row']="6";
$z[11][4]['titlelen']="30";
$z[12]=Array("arclist","\r\n<li><a href='view.php?aid=[field:id/]' title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></a><p><a href='view.php?aid=[field:id/]'>[field:title/]</a></p></li>\r\n",2099,2342);
$z[12][4]['flag']="";
$z[12][4]['row']="6";
$z[12][4]['titlelen']="30";
$z[13]=Array("include","",2368,2405);
$z[13][4]['filename']="foot_m.htm";

?>