<?php
$z[0]=Array("field","让人如痴如醉的邻家姐姐",0,63);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供让人如痴如醉的邻家姐姐。",65,147);
$z[1][4]['name']="description";
$z[2]=Array("field","让人如痴如醉的邻家姐姐",149,209);
$z[2][4]['name']="title";
$z[3]=Array("field","",211,250);
$z[3][4]['name']="writer";
$z[4]=Array("field","",252,291);
$z[4][4]['name']="source";
$z[5]=Array("field","",293,333);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",335,372);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629AD3S520-452c0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629AD43J50-464444.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629AD491030-4H262.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629AD551M0-4Y458.jpg{/dede:img}",374,963);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629AD3S520-452c0_lit.jpg",965,1054);
$z[8][4]['name']="litpic";

?>