<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","可爱粉红MM",89,137);
$z[2][4]['name']="title";
$z[3]=Array("field","",139,178);
$z[3][4]['name']="writer";
$z[4]=Array("field","",180,219);
$z[4][4]['name']="source";
$z[5]=Array("field","",221,258);
$z[5][4]['name']="body";
$z[6]=Array("field","",260,300);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/13341214U4250-162152.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/13341214Y04c0-1MG7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/133412149244K0-1YH1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334121495J250-192222.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/13341214b95N0-20IQ.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/133412150240110-21b13.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/1334121505K450-22RJ.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/133412150S2910-233062.jpg{/dede:img}",302,1262);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120411/13341214U4250-162152_lit.jpg",1264,1355);
$z[8][4]['name']="litpic";

?>