{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402K3421330-15Y3.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402K34bZ-23M0.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402K35614F-312A.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402K3632R0-4M62.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402K3G5F-5Q55.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402K3OW30-63213.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402K3VY40-H202.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133402K394M30-WT1.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133402K4025430-92457.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133402K4120520-109C3.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133402K4191360-11K39.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133402K42Q240-12K60.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133402K43R1F-139493.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133402K44B540-14ZE.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133402K4543330-151127.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133402K4612040-1A4V.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/133402K4E4Z-1I640.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/133402K4M4E0-1Q519.jpg{/dede:img}