<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="150";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","http://img.qqsisi.com/allimg/111125/10-1111251FI5.jpg",187,282);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","http://img.qqsisi.com/allimg/111125/10-1111251FI7.jpg",284,379);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","http://img.qqsisi.com/allimg/111125/10-1111251FI9.jpg",381,476);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","http://img.qqsisi.com/allimg/111125/10-1111251FJ1.jpg",478,573);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","http://img.qqsisi.com/allimg/111125/10-1111251FJ4.jpg",575,670);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","http://img.qqsisi.com/allimg/111125/10-1111251FJ7.jpg",672,767);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";
$z[8]=Array("img","http://img.qqsisi.com/allimg/111125/10-1111251FK0.jpg",769,864);
$z[8][4]['ddimg']="";
$z[8][4]['text']="图 7";
$z[9]=Array("img","http://img.qqsisi.com/allimg/111125/10-1111251FK2.jpg",866,961);
$z[9][4]['ddimg']="";
$z[9][4]['text']="图 8";
$z[10]=Array("img","http://img.qqsisi.com/allimg/111125/10-1111251FK4.jpg",963,1058);
$z[10][4]['ddimg']="";
$z[10][4]['text']="图 9";

?>