<?php
$z[0]=Array("field","黑色,,",0,47);
$z[0][4]['name']="keywords";
$z[1]=Array("field","MM黑色私房照",49,105);
$z[1][4]['name']="description";
$z[2]=Array("field","MM黑色私房照",107,157);
$z[2][4]['name']="title";
$z[3]=Array("field","",159,198);
$z[3][4]['name']="writer";
$z[4]=Array("field","",200,239);
$z[4][4]['name']="source";
$z[5]=Array("field","",241,281);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",283,320);
$z[6][4]['name']="body";
$z[7]=Array("field","",322,361);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424050243L0-33N96.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354240502Y2Z-341L5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542405033D40-35R37.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354240503KM0-362526.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424050424P-3H938.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354240504640F-3Y4U.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424050512U0-3950O.jpg{/dede:img}",363,1231);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135424050243L0-33N96_lit.jpg",1233,1324);
$z[9][4]['name']="litpic";

?>