{dede:field name='keywords'}“胸替”蒋丽莎{/dede:field}
{dede:field name='description'}陈浩民娇妻“胸替”蒋丽莎大尺度写真{/dede:field}
{dede:field name='title'}陈浩民娇妻蒋丽莎大尺度写真{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403154O50F-2aV1.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334031555V3F-3030S.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403156206110-3124O.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340315F20940-322351.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340315K3IF-339B5.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340315PN0P-349493.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340315Z36230-354564.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403159419330-3A936.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/13340315c333F-3M094.jpg{/dede:field}
