{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A64105c0-5b5a.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A64141060-60P35.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A64253L0-611G6.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A642U10-62c30.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A64312910-631021.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A64341c0-64c04.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629A643G2Z-A1938.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629A64396140-B9118.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c130311/13629A6441M30-CQ55.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c130311/13629A6444DF-DCc.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c130311/13629A644J010-E4645.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c130311/13629A644b60-F51O.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c130311/13629A64524550-G9457.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c130311/13629A645943P-HX61.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c130311/13629A6462K40-I1352.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c130311/13629A64B5c0-J4X0.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c130311/13629A64ENF-K6348.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c130311/13629A64I50P-L5548.jpg{/dede:img}