<?php
$z[0]=Array("field","美女,美女图片,性感美女,私房",0,68);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",70,114);
$z[1][4]['name']="description";
$z[2]=Array("field","薄纱落隐落现",116,166);
$z[2][4]['name']="title";
$z[3]=Array("field","",168,207);
$z[3][4]['name']="writer";
$z[4]=Array("field","",209,248);
$z[4][4]['name']="source";
$z[5]=Array("field","",250,290);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",292,329);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2aY53AZ-1C561.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2aY6095Z-1J125.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2aYD92Z-1V106.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2aYI350-194043.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2aYL920-206005.jpg{/dede:img}",331,1001);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2aY53AZ-1C561_lit.jpg",1003,1090);
$z[8][4]['name']="litpic";

?>