{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}芦苇从中{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334120Y950930-361V7.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334120Z2U940-3H537.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/1334120Z61A50-3R242.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334120Z943c0-394052.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/133412091243H0-405619.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/1334120915c320-41c51.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/13341209193Q0-422318.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/133412092244260-43BJ.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/1334120Y950930-361V7_lit.jpg{/dede:field}
