<?php
$z[0]=Array("field","睡美人,美女",0,52);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",54,98);
$z[1][4]['name']="description";
$z[2]=Array("field","性感睡衣",100,146);
$z[2][4]['name']="title";
$z[3]=Array("field","",148,187);
$z[3][4]['name']="writer";
$z[4]=Array("field","",189,228);
$z[4][4]['name']="source";
$z[5]=Array("field","",230,270);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",272,309);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2V05354450-1O63.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2V05391460-23947.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2V05456260-35b7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2V054T260-411O.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2V05534260-5Y17.jpg{/dede:img}",311,988);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2V05354450-1O63_lit.jpg",990,1079);
$z[8][4]['name']="litpic";

?>