{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133404342C0X0-443541.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133404342K4S0-455639.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133404342XG30-461Q1.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133404343010110-4G338.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334043430Rc0-4W917.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133404343152D0-4b451.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133404343213R0-50DS.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334043432M060-5161W.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/13340434332a20-523161.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133404343401510-534926.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/1334043434LZ-54V54.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/13340434363K60-55LA.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133404343M9630-561J4.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133404343T5010-5G464.jpg{/dede:img}