<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190710/1-1ZG01Q642.jpg ",93,235);
$z[1][4]['ddimg']="/uploads/allimg/190710/1-1ZG01Q642.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1024";
$z[1][4]['height']="683";
$z[2]=Array("img"," /uploads/allimg/190710/1-1ZG01Q643.jpg ",237,379);
$z[2][4]['ddimg']="/uploads/allimg/190710/1-1ZG01Q643.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="682";
$z[2][4]['height']="1023";
$z[3]=Array("img"," /uploads/allimg/190710/1-1ZG01Q646.jpg ",381,523);
$z[3][4]['ddimg']="/uploads/allimg/190710/1-1ZG01Q646.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1024";
$z[3][4]['height']="683";
$z[4]=Array("img"," /uploads/allimg/190710/1-1ZG01Q647.jpg ",525,667);
$z[4][4]['ddimg']="/uploads/allimg/190710/1-1ZG01Q647.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="682";
$z[4][4]['height']="1024";
$z[5]=Array("img"," /uploads/allimg/190710/1-1ZG01Q648.jpg ",669,811);
$z[5][4]['ddimg']="/uploads/allimg/190710/1-1ZG01Q648.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="1024";
$z[5][4]['height']="683";

?>