{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A46016460-3Eb8.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A4613DF-3KH8.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A461M3F-3V118.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A46235A0-3b431.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A462T050-403251.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A46326110-411525.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629A463B050-422T3.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629A4640QZ-435O6.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c130311/13629A464600Z-441413.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c130311/13629A4A05640-455348.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c130311/13629A4A4310-4635b.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c130311/13629A4AP4F-4L620.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c130311/13629A4B21K0-4Y926.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c130311/13629A4B623F-491244.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c130311/13629A4C16150-50SC.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c130311/13629A4CJ3F-515037.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c130311/13629A4D2030-52TP.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c130311/13629A4D63320-531O4.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c130311/13629A4E14310-541Y7.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c130311/13629A4E55960-55C49.jpg{/dede:img}