<?php
$z[0]=Array("field","性感车模,美女图片,性感美女,高",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",72,116);
$z[1][4]['name']="description";
$z[2]=Array("field","2012车展靓妹",118,168);
$z[2][4]['name']="title";
$z[3]=Array("field","",170,209);
$z[3][4]['name']="writer";
$z[4]=Array("field","",211,250);
$z[4][4]['name']="source";
$z[5]=Array("field","",252,292);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",294,331);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U29196064140-91258.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U29196102240-103X6.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U291a21Q10-115607.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U291a3c920-12ZQ.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U291a421H0-13V31.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U291a5E330-144E3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U291a63W30-152146.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U291aJ5040-1A200.jpg{/dede:img}",333,1285);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U29196064140-91258_lit.jpg",1287,1378);
$z[8][4]['name']="litpic";

?>