<?php
$z[0]=Array("field","楚楚",0,45);
$z[0][4]['name']="keywords";
$z[1]=Array("field","楚楚魅惑美图",47,103);
$z[1][4]['name']="description";
$z[2]=Array("field","楚楚魅惑美图",105,155);
$z[2][4]['name']="title";
$z[3]=Array("field","",157,196);
$z[3][4]['name']="writer";
$z[4]=Array("field","",198,237);
$z[4][4]['name']="source";
$z[5]=Array("field","",239,279);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",281,318);
$z[6][4]['name']="body";
$z[7]=Array("field","",320,359);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424045E2U0-2E0N.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424045KP20-2GN3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135424045QZ-2Qa1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424045W1K0-2a0R.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424045915a0-30K16.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354240460H310-3129D.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/13542404611420-326157.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354240461L60-33A60.jpg{/dede:img}",361,1314);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135424045E2U0-2E0N_lit.jpg",1316,1405);
$z[9][4]['name']="litpic";

?>