<?php
$z[0]=Array("field","兔女郎,性感美女,美女图片",0,65);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",67,111);
$z[1][4]['name']="description";
$z[2]=Array("field","兔女郎的诱惑",113,163);
$z[2][4]['name']="title";
$z[3]=Array("field","",165,204);
$z[3][4]['name']="writer";
$z[4]=Array("field","",206,245);
$z[4][4]['name']="source";
$z[5]=Array("field","",247,287);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",289,326);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2V0461W10-25EM.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2V04HC20-2A5V.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2V04Qa20-2OK5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2V04V9430-2XE9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2V04962430-293132.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2V05094J0-30F56.jpg{/dede:img}",328,1091);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2V0461W10-25EM_lit.jpg",1093,1181);
$z[8][4]['name']="litpic";

?>