<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","阳台上的女孩",89,139);
$z[2][4]['name']="title";
$z[3]=Array("field","",141,180);
$z[3][4]['name']="writer";
$z[4]=Array("field","",182,221);
$z[4][4]['name']="source";
$z[5]=Array("field","",223,260);
$z[5][4]['name']="body";
$z[6]=Array("field","",262,302);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334120BY5c0-232223.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334120C1R630-241043.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/1334120C430M0-2564Y.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334120D03J30-2C146.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/1334120D334S0-2N1V.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/1334120D6060F-2T021.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/1334120DU2330-2a920.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/1334120E125550-302602.jpg{/dede:img}",304,1261);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120411/1334120BY5c0-232223_lit.jpg",1263,1353);
$z[8][4]['name']="litpic";

?>