{dede:noteinfo notename="Íøµê»õÔ´ www.taoqao.com" channelid="1" macthtype="string"
    refurl="" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://fknet.cn/chanjilink.html" regxurl="http://www.taoqao.com/wangshangkaidian/wdhy/list_6_(*).html"
startid="1" endid="27" addv="1" urlrule="area" musthas=".html"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="news_list">	{/dede:areastart}
    {dede:areaend}<div class="pagenum">{/dede:areaend}
{/dede:listrule}
