{dede:noteinfo notename="Õ¾¿á-¾­Ñé" channelid="1" macthtype="string"
    refurl="" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="rss" rssurl="http://fknet.cn/chanjilink.html" regxurl="http://www.zcool.com.cn/articles/322!325!200!2!(*)!0!0!2/"
startid="1" endid="1" addv="1" urlrule="area" musthas=".html"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div>{/dede:areastart}
    {dede:areaend}</div>{/dede:areaend}
{/dede:listrule}
