<?php
$z[0]=Array("field","XGMM,诗朵雅,美女图片,美女,清纯",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",73,117);
$z[1][4]['name']="description";
$z[2]=Array("field","纯白诱惑李杨子",119,171);
$z[2][4]['name']="title";
$z[3]=Array("field","",173,212);
$z[3][4]['name']="writer";
$z[4]=Array("field","",214,253);
$z[4][4]['name']="source";
$z[5]=Array("field","",255,295);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",297,334);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",336,563);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","",565,604);
$z[8][4]['name']="litpic";

?>