{dede:field name='keywords'}XGMM,诗朵雅,美女图片,美女,清纯{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}纯白诱惑李杨子{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}{/dede:field}
