<?php
$z[0]=Array("field","森林里木口亜矢",0,55);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的森林里木口亜矢",57,127);
$z[1][4]['name']="description";
$z[2]=Array("field","森林里木口亜矢",129,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","",224,263);
$z[4][4]['name']="source";
$z[5]=Array("field","",265,302);
$z[5][4]['name']="body";
$z[6]=Array("field","",304,344);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405430445510-123a.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133405430562320-2CW.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133405430AY50-32961.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133405430L0P-42T4.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133405430T51Z-5Q55.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340543094a50-64924.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133405431054O0-LM3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133405431150440-VU0.jpg{/dede:img}",346,1299);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133405430445510-123a_lit.jpg",1301,1392);
$z[8][4]['name']="litpic";

?>