{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}校花赵已晨{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/133412210L0310-343394.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334122112214Z-35N45.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/133412211J2A0-362H3.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334122122I4P-3I442.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/133412212N4M0-3X920.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/13341221333G20-39E96.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/133412213PB40-403146.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/133412214352160-414157.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/133412214Y1R0-421W4.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120411/1334122153L0F-434I3.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/133412210L0310-343394_lit.jpg{/dede:field}
