{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334023195B410-24H31.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402319C22Z-259112.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340231a4aF-2E335.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340231b0WZ-2K541.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340231bO610-2WZ8.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340231c35020-2950R.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402320020440-303552.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/13340232010S40-314W3.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133402320223040-32U26.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/1334023203092F-333R9.jpg{/dede:img}