{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}清纯美女邵星芸{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/13341221R31P-11009.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/13341221W623Z-25642.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/133412219154H0-31430.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334122195460P-4P30.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/13341221c9460-52025.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/13341222031SP-C3M.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/133412220540O0-L3W.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/133412220R2540-T1L.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/1334122210U610-94325.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120411/133412221356430-106022.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/13341221R31P-11009_lit.jpg{/dede:field}
