<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","茑花二月青春半",89,141);
$z[2][4]['name']="title";
$z[3]=Array("field","",143,182);
$z[3][4]['name']="writer";
$z[4]=Array("field","",184,223);
$z[4][4]['name']="source";
$z[5]=Array("field","",225,262);
$z[5][4]['name']="body";
$z[6]=Array("field","",264,304);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/13341212Wc310-261043.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334121294112F-2MD3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/13341212c930P-2W337.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334121305W240-291M0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/1334121311645F-302002.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/133412131J6230-319456.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/1334121323D450-32D11.jpg{/dede:img}",306,1177);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120411/13341212Wc310-261043_lit.jpg",1179,1270);
$z[8][4]['name']="litpic";

?>