{dede:noteinfo notename="常见问题" channelid="1" macthtype="string"
refurl="http://" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.meizu.com/services/questionList.html?type=2&gradeClass=1&gradeTypeId=17002&pageNumber=(*)"
startid="1" endid="314" addv="1" urlrule="area"
 musthas=".html" nothas="" listpic="0" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="p_tabbg">{/dede:areastart}
    {dede:areaend}<div class="centerSep">{/dede:areaend}
{/dede:listrule}
