<?php
$z[0]=Array("noteinfo","",0,156);
$z[0][4]['notename']="³£¼ûÎÊÌâ";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div class=\"p_tabbg\">{/dede:areastart}\r\n    {dede:areaend}<div class=\"centerSep\">{/dede:areaend}\r\n",160,670);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.meizu.com/services/questionList.html?type=2&gradeClass=1&gradeTypeId=17002&pageNumber=(*)";
$z[1][4]['startid']="1";
$z[1][4]['endid']="314";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']=".html";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="0";
$z[1][4]['usemore']="0";

?>