<?php
$z[0]=Array("field","清纯美女,白色性感诱惑睡衣私房",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供清纯美女 白色性感诱惑睡衣私房写真。",72,165);
$z[1][4]['name']="description";
$z[2]=Array("field","清纯美女 白色性感诱惑睡衣私房写真",167,238);
$z[2][4]['name']="title";
$z[3]=Array("field","",240,279);
$z[3][4]['name']="writer";
$z[4]=Array("field","",281,320);
$z[4][4]['name']="source";
$z[5]=Array("field","",322,362);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",364,401);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B120MG0-21E39.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B12129440-22Y36.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B12163040-231300.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B12196140-24b51.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629B1222J0-25UD.jpg{/dede:img}",403,1086);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629B120MG0-21E39_lit.jpg",1088,1177);
$z[8][4]['name']="litpic";

?>