<?php
$z[0]=Array("field","清纯美女私房密照",0,57);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供清纯美女私房密照。",59,135);
$z[1][4]['name']="description";
$z[2]=Array("field","清纯美女私房密照",137,191);
$z[2][4]['name']="title";
$z[3]=Array("field","",193,232);
$z[3][4]['name']="writer";
$z[4]=Array("field","",234,273);
$z[4][4]['name']="source";
$z[5]=Array("field","",275,315);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",317,354);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A35494120-15a37.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A35494120-15a37.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A35524M0-1D106.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A35550160-1KG6.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A35561610-1T0U.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A355R5P-192950.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c130311/13629A3560JF-209219.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c130311/13629A35631N0-21JQ.jpg{/dede:img}",356,1312);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A35494120-15a37_lit.jpg",1314,1405);
$z[8][4]['name']="litpic";

?>