<?php
$z[0]=Array("field",",",0,42);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",44,88);
$z[1][4]['name']="description";
$z[2]=Array("field","花神美境小龙女",90,142);
$z[2][4]['name']="title";
$z[3]=Array("field","",144,183);
$z[3][4]['name']="writer";
$z[4]=Array("field","",185,224);
$z[4][4]['name']="source";
$z[5]=Array("field","",226,266);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",268,305);
$z[6][4]['name']="body";
$z[7]=Array("field","",307,346);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423Z2300040-2L552.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423Z23611Z-2WP1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423Z2422940-2c037.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423Z2492Y0-303J5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423Z25BE0-313163.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423Z2A1010-326291.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423Z2H1020-333607.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423Z2O3N0-345N5.jpg{/dede:img}",348,1305);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423Z2300040-2L552_lit.jpg",1307,1398);
$z[9][4]['name']="litpic";

?>