<?php
$z[0]=Array("field",",",0,42);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",44,88);
$z[1][4]['name']="description";
$z[2]=Array("field","春睡足",90,134);
$z[2][4]['name']="title";
$z[3]=Array("field","",136,175);
$z[3][4]['name']="writer";
$z[4]=Array("field","",177,216);
$z[4][4]['name']="source";
$z[5]=Array("field","",218,258);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",260,297);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334022M401J0-2a1C.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334022M533250-305319.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334022MB1V0-3115V.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334022MNCP-3215X.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334022MZE10-332K5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334022N01O60-345202.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334022N1251F-35A39.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334022N240P-362417.jpg{/dede:img}",299,1252);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/1334022N361N0-3O363.jpg",1254,1340);
$z[8][4]['name']="litpic";

?>