<?php
$z[0]=Array("field","90后美女,王馨漪超清纯美丽动人",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供90后美女 王馨漪超清纯美丽动人个性秀。",72,167);
$z[1][4]['name']="description";
$z[2]=Array("field","90后美女 王馨漪超清纯美丽动人个性秀",169,242);
$z[2][4]['name']="title";
$z[3]=Array("field","",244,283);
$z[3][4]['name']="writer";
$z[4]=Array("field","",285,324);
$z[4][4]['name']="source";
$z[5]=Array("field","",326,366);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",368,405);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629B0c5X10-1O42.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629B100094P-23112.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629B100403F-32Q1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629B100G360-43X6.jpg{/dede:img}",407,994);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629B0c5X10-1O42_lit.jpg",996,1084);
$z[8][4]['name']="litpic";

?>