<?php
$z[0]=Array("noteinfo","",0,193);
$z[0][4]['notename']="ÃÀÅ®ÕÕÆ¬";
$z[0][4]['channelid']="2";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://www.mn123.net/wangluohongren/";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div class=\"main_column\">{/dede:areastart}\r\n    {dede:areaend}</div>{/dede:areaend}\r\n",195,636);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.mn123.net/wangluohongren/list_5_(*).html";
$z[1][4]['startid']="1";
$z[1][4]['endid']="2";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="0";
$z[1][4]['usemore']="0";

?>