<?php
$z[0]=Array("field","美女",0,45);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美女摄影：窗外",47,105);
$z[1][4]['name']="description";
$z[2]=Array("field","美女摄影：窗外",107,159);
$z[2][4]['name']="title";
$z[3]=Array("field","",161,200);
$z[3][4]['name']="writer";
$z[4]=Array("field","",202,241);
$z[4][4]['name']="source";
$z[5]=Array("field","",243,283);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",285,322);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402F92b0-11959.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402F9611220-232I.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402Fc00520-31437.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402G02134F-45D0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402G0492210-5F14.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402G0JE0-61535.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402G1055L0-GE8.jpg{/dede:img}",324,1181);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133402G1364030-Q104.jpg",1183,1269);
$z[8][4]['name']="litpic";

?>