<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","时光流转",89,135);
$z[2][4]['name']="title";
$z[3]=Array("field","",137,176);
$z[3][4]['name']="writer";
$z[4]=Array("field","",178,217);
$z[4][4]['name']="source";
$z[5]=Array("field","",219,259);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",261,298);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U292X933250-1L5N.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U292Y0H460-1U2c.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U292Y15FF-192641.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U292Y3T5P-201524.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U292Y4643P-21L95.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U292YR020-22UJ.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U292YT940-23E43.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U292YcV10-24K33.jpg{/dede:img}",300,1242);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U292X933250-1L5N_lit.jpg",1244,1333);
$z[8][4]['name']="litpic";

?>