<?php
$z[0]=Array("field","出浴美人,浴室诱惑",0,58);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",60,104);
$z[1][4]['name']="description";
$z[2]=Array("field","没人出浴",106,152);
$z[2][4]['name']="title";
$z[3]=Array("field","",154,193);
$z[3][4]['name']="writer";
$z[4]=Array("field","",195,234);
$z[4][4]['name']="source";
$z[5]=Array("field","",236,276);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",278,315);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2V06319110-11P25.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2V0634a10-125b5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2V06460020-1353c.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2V064O320-141239.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2V0A15620-151S7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2V0A94020-162059.jpg{/dede:img}",317,1088);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2V06319110-11P25_lit.jpg",1090,1180);
$z[8][4]['name']="litpic";

?>