{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133404322C1H0-3434G.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133404322LD20-356256.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133404322U0230-3B923.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133404322914460-3L423.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404323035630-3S445.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/13340432313c50-391O7.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340432325630-402921.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133404323360Q0-41IX.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133404323454320-42D62.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/13340432353Z60-435017.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/13340432363M10-44IK.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133404323FV20-451036.jpg{/dede:img}