{dede:field name='keywords'}相泽仁美{/dede:field}
{dede:field name='description'}提供最漂亮的相泽仁美{/dede:field}
{dede:field name='title'}相泽仁美{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405429451440-62OD.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334054295IC0-633644.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133405429BWP-645632.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340542aB550-AA28.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340542bT460-B5R8.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133405429451440-62OD_lit.jpg{/dede:field}
