<?php
$z[0]=Array("field","相泽仁美",0,49);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的相泽仁美",51,115);
$z[1][4]['name']="description";
$z[2]=Array("field","相泽仁美",117,163);
$z[2][4]['name']="title";
$z[3]=Array("field","",165,204);
$z[3][4]['name']="writer";
$z[4]=Array("field","",206,245);
$z[4][4]['name']="source";
$z[5]=Array("field","",247,284);
$z[5][4]['name']="body";
$z[6]=Array("field","",286,326);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405429451440-62OD.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334054295IC0-633644.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133405429BWP-645632.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/13340542aB550-AA28.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/13340542bT460-B5R8.jpg{/dede:img}",328,1010);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133405429451440-62OD_lit.jpg",1012,1103);
$z[8][4]['name']="litpic";

?>