{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334022F3Z460-303013.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334022F53920-315129.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334022FC3U0-32Z08.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334022FQ0X0-332317.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334022F942320-3463G.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334022G0H550-359537.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334022G1b340-3D614.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334022G324S0-3GH7.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/1334022G449130-3Rc8.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/1334022G5T3P-3a1L.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/1334022GGWF-403451.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/1334022GTRF-411G5.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/1334022Ga5010-42QN.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/1334022H10aP-431301.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/1334022H23CZ-44K96.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/1334022H3F930-45J61.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/1334022H51LZ-462045.jpg{/dede:img}