<?php
$z[0]=Array("field","幽然花园",0,49);
$z[0][4]['name']="keywords";
$z[1]=Array("field","幽然花园",51,103);
$z[1][4]['name']="description";
$z[2]=Array("field","幽然花园",105,151);
$z[2][4]['name']="title";
$z[3]=Array("field","",153,192);
$z[3][4]['name']="writer";
$z[4]=Array("field","",194,233);
$z[4][4]['name']="source";
$z[5]=Array("field","",235,275);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",277,314);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402H2239350-1V591.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402H23210-194021.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402H2402620-20EL.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402H24Q5P-215092.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402H2559550-222339.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402H2635340-239636.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402H2GHP-24N58.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133402H2PM60-25P14.jpg{/dede:img}",316,1273);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133402H2X1030-264J1.jpg",1275,1361);
$z[8][4]['name']="litpic";

?>