{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405303021340-446395.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133405303109550-452218.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133405303204510-462942.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334053032UN0-4M910.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334053033E450-4W942.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334053034H550-4b247.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334053035MJ0-504911.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133405303C4530-515218.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133405303MU10-524I5.jpg{/dede:img}