{dede:field name='keywords'}写真,生活,女孩,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美空女孩生活写真{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403FDHV0-4219A.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403FE93120-43H01.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403FF93460-44Sa.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403FGS330-45U49.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403FHW3F-4B1C.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403FI52620-4O2L.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403FJ2a20-4R219.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403FK214Z-4c0E.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133403FL25010-502333.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133403FM04030-511964.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133403FN0Q20-525256.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133403FO00P-536111.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133403FOb4Z-549C5.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133403FPY520-5532L.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133403FR00950-561T3.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133403FS0L30-5G131.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/133403FSZA0-5Y206.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/133403FTL030-595563.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c120410/133403FUU5Z-6015C.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c120410/133403FW0O20-613911.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c120410/133403FWZ4P-62T45.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c120410/133403FXQ160-63a38.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c120410/133403FYF420-6431J.jpg{/dede:img}
{dede:img ddimg='' text='图 24'}/uploads/allimg/c120410/133403FZS230-A6457.jpg{/dede:img}
{dede:img ddimg='' text='图 25'}/uploads/allimg/c120410/133403F91L030-B4251.jpg{/dede:img}
{dede:img ddimg='' text='图 26'}/uploads/allimg/c120410/133403F92AD0-CG21.jpg{/dede:img}
{dede:img ddimg='' text='图 27'}/uploads/allimg/c120410/133403F9353C0-D5303.jpg{/dede:img}
{dede:img ddimg='' text='图 28'}/uploads/allimg/c120410/133403F94510Z-E1305.jpg{/dede:img}
{dede:img ddimg='' text='图 29'}/uploads/allimg/c120410/133403F9546320-FC39.jpg{/dede:img}
{dede:img ddimg='' text='图 30'}/uploads/allimg/c120410/133403F9632260-GH06.jpg{/dede:img}
{dede:img ddimg='' text='图 31'}/uploads/allimg/c120410/133403Fa351P-HA18.jpg{/dede:img}
{dede:img ddimg='' text='图 32'}/uploads/allimg/c120410/133403Fb3GZ-Ia29.jpg{/dede:img}
{dede:img ddimg='' text='图 33'}/uploads/allimg/c120410/133403Fc5KF-J4E2.jpg{/dede:img}
{dede:img ddimg='' text='图 34'}/uploads/allimg/c120410/133403G00N910-K4001.jpg{/dede:img}
{dede:img ddimg='' text='图 35'}/uploads/allimg/c120410/133403G01S0Z-L5044.jpg{/dede:img}
{dede:img ddimg='' text='图 36'}/uploads/allimg/c120410/133403G02X550-MM92.jpg{/dede:img}
{dede:img ddimg='' text='图 37'}/uploads/allimg/c120410/133403G0394K0-N3N0.jpg{/dede:img}
{dede:img ddimg='' text='图 38'}/uploads/allimg/c120410/133403G050U0-O4A1.jpg{/dede:img}
{dede:img ddimg='' text='图 39'}/uploads/allimg/c120410/133403G0594J0-P4039.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133403G0G3X0-QO50.jpg{/dede:field}
