<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="235";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","/uploads/allimg/c131124/13U2U95E150-221535.jpg",187,275);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","/uploads/allimg/c131124/13U2U95L4410-2344U.jpg",277,365);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","/uploads/allimg/c131124/13U2U96031620-243954.jpg",367,457);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","/uploads/allimg/c131124/13U2U9613V30-25b52.jpg",459,547);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","/uploads/allimg/c131124/13U2U9624E30-2A0E.jpg",549,636);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","/uploads/allimg/c131124/13U2U9630U40-2OC7.jpg",638,725);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";
$z[8]=Array("img","/uploads/allimg/c131124/13U2U964N050-2R559.jpg",727,815);
$z[8][4]['ddimg']="";
$z[8][4]['text']="图 7";
$z[9]=Array("img","/uploads/allimg/c131124/13U2U9A42050-2aV1.jpg",817,904);
$z[9][4]['ddimg']="";
$z[9][4]['text']="图 8";
$z[10]=Array("img","/uploads/allimg/c131124/13U2U9BO360-30E57.jpg",906,993);
$z[10][4]['ddimg']="";
$z[10][4]['text']="图 9";

?>