<?php
$z[0]=Array("field","性感美女,美女图片,比基尼美女",0,69);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",71,115);
$z[1][4]['name']="description";
$z[2]=Array("field","性感迷人身材妖娆",117,171);
$z[2][4]['name']="title";
$z[3]=Array("field","",173,212);
$z[3][4]['name']="writer";
$z[4]=Array("field","",214,253);
$z[4][4]['name']="source";
$z[5]=Array("field","",255,295);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",297,334);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2U35ZcP-129101.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2U35c4Y0-135336.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2U3625220-144012.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2U36264P-152313.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2U3C14330-1B134.jpg{/dede:img}",336,1013);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2U35ZcP-129101_lit.jpg",1015,1103);
$z[8][4]['name']="litpic";

?>