<?php
$z[0]=Array("field","封面,时装,优雅,,",0,57);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",59,103);
$z[1][4]['name']="description";
$z[2]=Array("field","张静初优雅登《时装》封面",105,167);
$z[2][4]['name']="title";
$z[3]=Array("field","",169,208);
$z[3][4]['name']="writer";
$z[4]=Array("field","",210,249);
$z[4][4]['name']="source";
$z[5]=Array("field","",251,291);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",293,330);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403G403P30-1031206.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403G411EP-1041326.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403G41La0-105aS.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403G4233N0-1062a1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403G42912P-10I933.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403G4353330-10VX2.jpg{/dede:img}",332,1110);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133403G43c240-1094934.jpg",1112,1200);
$z[8][4]['name']="litpic";

?>