{dede:field name='keywords'}越南人气大胸女{/dede:field}
{dede:field name='description'}曾经在网络上靠自拍爆红的越南人气“大胸”美女，近日代言了内衣。从网络红人到专业演员、模特，这种自我炒作手法似乎在如今的网络上悄然流行起来，众人对此褒贬不一，许多如此途径走红的少男少女在众人眼前只是昙花一现，并没有一直在演艺事业上走下去。{/dede:field}
{dede:field name='title'}越南人气大胸女代言内衣{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354241D43E0-4644a.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354241D4K5Z-4KV6.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354241D53R50-4S0a.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354241D6062P-494496.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354241DCE0-504209.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354241DK0420-519394.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354241DR2B0-524I2.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354241DUc10-53Z25.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354241D94W60-543332.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/1354241D43E0-4644a_lit.jpg{/dede:field}
