<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="235";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","/uploads/allimg/c131124/13U2cTW4460-14260.jpg",187,274);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","/uploads/allimg/c131124/13U2cU020C0-2S44.jpg",276,362);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","/uploads/allimg/c131124/13U2cU0V5F-34102.jpg",364,450);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","/uploads/allimg/c131124/13U2cU1354F-42A1.jpg",452,538);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","/uploads/allimg/c131124/13U2cU232N0-54211.jpg",540,627);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","/uploads/allimg/c131124/13U2cU3003P-E609.jpg",629,715);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";

?>