<?php
$z[0]=Array("field","车模私房大片",0,53);
$z[0][4]['name']="keywords";
$z[1]=Array("field","车模私房大片。",55,113);
$z[1][4]['name']="description";
$z[2]=Array("field","车模私房大片二",115,167);
$z[2][4]['name']="title";
$z[3]=Array("field","",169,208);
$z[3][4]['name']="writer";
$z[4]=Array("field","",210,249);
$z[4][4]['name']="source";
$z[5]=Array("field","",251,291);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",293,330);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133402I3560060-3Ka2.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133402I3V1T0-3W1U.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133402I40c520-3a517.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133402I4615O0-405641.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133402I4V3c0-41E08.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133402I50943P-42V25.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133402I52H150-435U6.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133402I54P20-44cV.jpg{/dede:img}",332,1283);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/133402I55VQ0-45P60.jpg",1285,1370);
$z[8][4]['name']="litpic";

?>