<?php
$z[0]=Array("field","粉色小白兔的蝙蝠衫,清纯可爱",0,68);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供粉色小白兔的蝙蝠衫 清纯可爱。",70,157);
$z[1][4]['name']="description";
$z[2]=Array("field","粉色小白兔的蝙蝠衫 清纯可爱",159,224);
$z[2][4]['name']="title";
$z[3]=Array("field","",226,265);
$z[3][4]['name']="writer";
$z[4]=Array("field","",267,306);
$z[4][4]['name']="source";
$z[5]=Array("field","",308,348);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",350,387);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A241RN0-25H05.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A2422b60-264C0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A24261330-2HU6.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A242c20-2R439.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A24346320-2a255.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A243M3F-303110.jpg{/dede:img}",389,1161);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A241RN0-25H05_lit.jpg",1163,1252);
$z[8][4]['name']="litpic";

?>