{dede:field name='keywords'}粉色小白兔的蝙蝠衫,清纯可爱{/dede:field}
{dede:field name='description'}美桌图片库提供粉色小白兔的蝙蝠衫 清纯可爱。{/dede:field}
{dede:field name='title'}粉色小白兔的蝙蝠衫 清纯可爱{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A241RN0-25H05.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A2422b60-264C0.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A24261330-2HU6.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A242c20-2R439.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A24346320-2a255.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A243M3F-303110.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c130311/13629A241RN0-25H05_lit.jpg{/dede:field}
