<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="150";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","/uploads/allimg/c121130/1354244G430440-316121.jpg",187,278);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","/uploads/allimg/c121130/1354244G5550Z-324b3.jpg",280,369);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","/uploads/allimg/c121130/1354244GB10P-33a00.jpg",371,459);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","/uploads/allimg/c121130/1354244GL6050-344Z7.jpg",461,550);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","/uploads/allimg/c121130/1354244GWF30-359B1.jpg",552,640);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","/uploads/allimg/c121130/1354244Gb40P-3A610.jpg",642,730);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";
$z[8]=Array("img","/uploads/allimg/c121130/1354244H093U0-3NR1.jpg",732,820);
$z[8][4]['ddimg']="";
$z[8][4]['text']="图 7";
$z[9]=Array("img","/uploads/allimg/c121130/1354244H2031P-3R445.jpg",822,911);
$z[9][4]['ddimg']="";
$z[9][4]['text']="图 8";
$z[10]=Array("img","/uploads/allimg/c121130/1354244H305640-3a1A.jpg",913,1002);
$z[10][4]['ddimg']="";
$z[10][4]['text']="图 9";

?>