<?php
$z[0]=Array("field","日本木村亜梨沙",0,55);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的日本木村亜梨沙",57,127);
$z[1][4]['name']="description";
$z[2]=Array("field","日本木村亜梨沙",129,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","",224,263);
$z[4][4]['name']="source";
$z[5]=Array("field","",265,305);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",307,344);
$z[6][4]['name']="body";
$z[7]=Array("field","",346,385);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354244M4D1Z-115b8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354244MR05P-12CT.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354244N02N40-136313.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354244N23D40-143160.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354244N4440-1540J.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354244NB0F-1BG7.jpg{/dede:img}",387,1155);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/1354244M4D1Z-115b8_lit.jpg",1157,1246);
$z[9][4]['name']="litpic";

?>