
{dede:noteinfo notename="¾Õ»¨±¦µä" channelid="1" macthtype="string"
refurl="http://" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.neihan8.com/jhxd/63438_(*).html"
startid="1" endid="33" addv="1" urlrule="area"
 musthas=".html" nothas="" listpic="0" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<ul class="e2">{/dede:areastart}
    {dede:areaend}<div class="dede_pages">{/dede:areaend}
{/dede:listrule}

