{dede:noteinfo notename="Ë¿ÍàÃÀÍÈ" channelid="2" macthtype="string"
refurl="http://www.ddxiezhen.com/siwa/" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.ddxiezhen.com/siwa/index_(*).html"
startid="1" endid="2" addv="1" urlrule="area"
 musthas="" nothas="" listpic="0" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart} <ul class="i_pic">{/dede:areastart}
    {dede:areaend}</li>{/dede:areaend}
{/dede:listrule}
