{dede:field name='keywords'}灿烂,那么,总是,笑容,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}符晓薇--笑容总是那么灿烂{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423Yc36430-12929.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423Z002KZ-2GS.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423Z0101220-34J2.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423Z01L2Z-43501.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423Z02C530-54O1.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423Z033TF-63407.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423Z041FP-L296.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423Z05063F-V037.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/135423Z05Q30-91552.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/135423Z0AU50-102060.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/135423Z0I2030-111105.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/135423Z0Q5120-121004.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/135423Z0ZSZ-133B8.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/135423Z0c9260-14UD.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/135423Z10IB0-15Ua.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/135423Z11500Z-1C927.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c121130/135423Z1225250-1N4P.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135423Yc36430-12929_lit.jpg{/dede:field}
