<?php
$z[0]=Array("field",",",0,42);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",44,88);
$z[1][4]['name']="description";
$z[2]=Array("field","春睡足",90,134);
$z[2][4]['name']="title";
$z[3]=Array("field","",136,175);
$z[3][4]['name']="writer";
$z[4]=Array("field","",177,216);
$z[4][4]['name']="source";
$z[5]=Array("field","",218,258);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",260,297);
$z[6][4]['name']="body";
$z[7]=Array("field","",299,338);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423Z3J5050-439449.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423Z3S93F-443D3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423Z392C30-45WU.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423Z3c64F-4C428.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423Z40635F-4H062.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423Z4145440-4Y925.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423Z42150P-495W1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423Z42NS0-5012H.jpg{/dede:img}",340,1293);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423Z3J5050-439449_lit.jpg",1295,1386);
$z[9][4]['name']="litpic";

?>