{dede:field name='keywords'}靓丽写真{/dede:field}
{dede:field name='description'}百变美女徐嘉阳靓丽写真。{/dede:field}
{dede:field name='title'}百变美女徐嘉阳靓丽写真{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423Y6226340-153045.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423Y62O020-162H3.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423Y6329320-1K500.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423Y63B230-1X2F.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423Y6400I0-1b058.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423Y6445210-20I47.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423Y64N910-21C02.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423YA11J0-225c5.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/135423YA4T40-2364P.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/135423YAN950-24Z94.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/135423YB13T0-2562J.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/135423YB50550-264425.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/135423YBXB0-2I591.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/135423YC240-2QJ0.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/135423YC44130-2aO5.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/135423YCL1P-302613.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c121130/135423YD11950-312345.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c121130/135423YD5E40-32Y13.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c121130/135423YDb450-33C35.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c121130/135423YE29230-344T3.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c121130/135423YEA260-3513K.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135423Y6226340-153045_lit.jpg{/dede:field}
