{dede:field name='keywords'}私房写真{/dede:field}
{dede:field name='description'}小妹私房写真照{/dede:field}
{dede:field name='title'}小妹私房写真照{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542404V03140-122118.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542404VN060-133422.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542404W25Y0-141423.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542404WV240-1533H.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542404X354Z-1D026.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542404Y0X20-1I2F.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/13542404YM450-1X153.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/13542404Z52430-192H3.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/13542404910TF-205O1.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/135424049161610-211216.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/135424049221c0-22LQ.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/1354240492N50-23J60.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/135424049331C0-24SK.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/1354240493J920-252644.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/13542404V03140-122118_lit.jpg{/dede:field}
