<?php
$z[0]=Array("field","“胸替”蒋丽莎",0,55);
$z[0][4]['name']="keywords";
$z[1]=Array("field","陈浩民娇妻“胸替”蒋丽莎大尺度写真",57,135);
$z[1][4]['name']="description";
$z[2]=Array("field","陈浩民娇妻蒋丽莎大尺度写真",137,201);
$z[2][4]['name']="title";
$z[3]=Array("field","",203,242);
$z[3][4]['name']="writer";
$z[4]=Array("field","",244,283);
$z[4][4]['name']="source";
$z[5]=Array("field","",285,325);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",327,364);
$z[6][4]['name']="body";
$z[7]=Array("field","",366,405);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423aL114P-114K.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423aLVN0-2a53.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423aM345Z-3B52.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423aM94630-42356.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423aN505F-5D10.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423aO0L20-D120.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423aOA950-N632.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423aP125F-SX1.jpg{/dede:img}",407,1346);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423aL114P-114K_lit.jpg",1348,1436);
$z[9][4]['name']="litpic";

?>