{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542592T4PZ-1H201.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542592VC940-1YM5.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542592XR560-1912K.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542592Z64460-2092F.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135425929259360-213338.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542592945FF-22TG.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135425929B34F-234409.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/13542592bH20-2495J.jpg{/dede:img}