<?php
$z[0]=Array("field","性感美女,美女私房,美女,诱人美",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",72,116);
$z[1][4]['name']="description";
$z[2]=Array("field","蓝色倩影",118,164);
$z[2][4]['name']="title";
$z[3]=Array("field","",166,205);
$z[3][4]['name']="writer";
$z[4]=Array("field","",207,246);
$z[4][4]['name']="source";
$z[5]=Array("field","",248,288);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",290,327);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2WKb4510-2334W.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2WL0RH0-24E44.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2WL101220-255126.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2WL1Q320-2C434.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2WL3FJ0-2IK5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2WLS0060-2W538.jpg{/dede:img}",329,1089);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2WKb4510-2334W_lit.jpg",1091,1179);
$z[8][4]['name']="litpic";

?>