<?php
$z[0]=Array("field","一眼就让你陶醉的绝色纯美女孩儿",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供一眼就让你陶醉的绝色纯美女孩儿。",73,163);
$z[1][4]['name']="description";
$z[2]=Array("field","一眼就让你陶醉的绝色纯美女孩儿",165,233);
$z[2][4]['name']="title";
$z[3]=Array("field","",235,274);
$z[3][4]['name']="writer";
$z[4]=Array("field","",276,315);
$z[4][4]['name']="source";
$z[5]=Array("field","",317,357);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",359,396);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A2W531P-25YQ.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A2X0O40-2643M.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A2X602F-2I223.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A2X94040-2W252.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A2Y40250-292A5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A2Y92K0-303193.jpg{/dede:img}",398,1167);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A2W531P-25YQ_lit.jpg",1169,1257);
$z[8][4]['name']="litpic";

?>