<?php
$z[0]=Array("field","森林里木口亜矢",0,55);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的森林里木口亜矢",57,127);
$z[1][4]['name']="description";
$z[2]=Array("field","森林里木口亜矢",129,181);
$z[2][4]['name']="title";
$z[3]=Array("field","",183,222);
$z[3][4]['name']="writer";
$z[4]=Array("field","",224,263);
$z[4][4]['name']="source";
$z[5]=Array("field","",265,305);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",307,344);
$z[6][4]['name']="body";
$z[7]=Array("field","",346,385);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542441Z95210-134237.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424419195250-144A3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354244192V10-154248.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354244193JT0-1A525.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424419454230-1LM9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542441952Y10-1R118.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424419625050-193223.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/13542441a13940-2022I.jpg{/dede:img}",387,1353);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/13542441Z95210-134237_lit.jpg",1355,1447);
$z[9][4]['name']="litpic";

?>