<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="600";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/c130311/13629B2J3JP-4024U.jpg ",93,252);
$z[1][4]['ddimg']="/uploads/allimg/c130311/13629B2J3JP-4024U.jpg";
$z[1][4]['text']="ͼ 1";
$z[1][4]['width']="960";
$z[1][4]['height']="640";
$z[2]=Array("img"," /uploads/allimg/c130311/13629B2J3JP-4024U.jpg ",254,413);
$z[2][4]['ddimg']="/uploads/allimg/c130311/13629B2J3JP-4024U.jpg";
$z[2][4]['text']="ͼ 2";
$z[2][4]['width']="960";
$z[2][4]['height']="640";
$z[3]=Array("img"," /uploads/allimg/c130311/13629B2K001F-412E9.jpg ",415,576);
$z[3][4]['ddimg']="/uploads/allimg/c130311/13629B2K001F-412E9.jpg";
$z[3][4]['text']="ͼ 3";
$z[3][4]['width']="640";
$z[3][4]['height']="960";
$z[4]=Array("img"," /uploads/allimg/c130311/13629B2K45220-424563.jpg ",578,743);
$z[4][4]['ddimg']="/uploads/allimg/c130311/13629B2K45220-424563.jpg";
$z[4][4]['text']="ͼ 4";
$z[4][4]['width']="960";
$z[4][4]['height']="640";
$z[5]=Array("img"," /uploads/allimg/c130311/13629B2KZF-43a35.jpg ",745,902);
$z[5][4]['ddimg']="/uploads/allimg/c130311/13629B2KZF-43a35.jpg";
$z[5][4]['text']="ͼ 5";
$z[5][4]['width']="960";
$z[5][4]['height']="640";

?>