{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}草坪上的清纯女{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/133412101006260-15Y44.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/13341210133PZ-163502.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/13341210164Y10-1GS9.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/133412102042030-1XW9.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/1334121023503F-192450.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/133412102E0L0-205R4.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/13341210311A30-2163A.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/13341210355R60-22B00.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/133412103X44Z-231164.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120411/13341210429310-243054.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/133412101006260-15Y44_lit.jpg{/dede:field}
