{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354244O339510-1K164.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354244O4O350-1S239.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354244O5X1P-1a951.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354244OF6420-20Z05.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354244OR5530-212U6.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354244O952230-225241.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354244P064Y0-231043.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354244P1O510-24Y93.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354244P2W440-25H50.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354244P394910-2B248.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354244P520B0-2O542.jpg{/dede:img}