<?php
$z[0]=Array("pagestyle","",0,75);
$z[0][4]['maxwidth']="800";
$z[0][4]['ddmaxwidth']="240";
$z[0][4]['row']="3";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("comments","图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效",77,185);
$z[2]=Array("img","/uploads/allimg/c120411/1334122600V0-119C.jpg",187,274);
$z[2][4]['ddimg']="";
$z[2][4]['text']="图 1";
$z[3]=Array("img","/uploads/allimg/c120411/133412260453530-215V.jpg",276,366);
$z[3][4]['ddimg']="";
$z[3][4]['text']="图 2";
$z[4]=Array("img","/uploads/allimg/c120411/133412260MC10-35594.jpg",368,457);
$z[4][4]['ddimg']="";
$z[4][4]['text']="图 3";
$z[5]=Array("img","/uploads/allimg/c120411/1334122610IU0-44411.jpg",459,548);
$z[5][4]['ddimg']="";
$z[5][4]['text']="图 4";
$z[6]=Array("img","/uploads/allimg/c120411/1334122615Q30-51509.jpg",550,639);
$z[6][4]['ddimg']="";
$z[6][4]['text']="图 5";
$z[7]=Array("img","/uploads/allimg/c120411/1334122620S130-C518.jpg",641,730);
$z[7][4]['ddimg']="";
$z[7][4]['text']="图 6";
$z[8]=Array("img","/uploads/allimg/c120411/133412262GTF-K5c.jpg",732,818);
$z[8][4]['ddimg']="";
$z[8][4]['text']="图 7";
$z[9]=Array("img","/uploads/allimg/c120411/13341226321b50-R408.jpg",820,909);
$z[9][4]['ddimg']="";
$z[9][4]['text']="图 8";
$z[10]=Array("img","/uploads/allimg/c120411/133412263550610-95Y0.jpg",911,1001);
$z[10][4]['ddimg']="";
$z[10][4]['text']="图 9";

?>