{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美女与法拉利{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2ZB4aI0-1T96.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2ZBa0L0-24U1.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2ZC4405P-3K92.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2ZD22D30-43333.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2ZF015030-55911.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2ZF364550-61419.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2ZF591460-H600.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c131124/13U2ZFM23F-W2F.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c131124/13U2ZG02HZ-96320.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c131124/13U2ZG2420-10G02.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c131124/13U2ZB4aI0-1T96_lit.jpg{/dede:field}
