<?php
$z[0]=Array("field","美丽,,",0,47);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",49,93);
$z[1][4]['name']="description";
$z[2]=Array("field","美丽足球宝贝",95,145);
$z[2][4]['name']="title";
$z[3]=Array("field","",147,186);
$z[3][4]['name']="writer";
$z[4]=Array("field","",188,227);
$z[4][4]['name']="source";
$z[5]=Array("field","",229,269);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",271,308);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334022BA0940-V624.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334022BN1J0-cc9.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334022BZ5440-101363.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334022C0035F-119450.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334022C11XP-126401.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334022C25Y60-13H51.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334022C3R160-1453U.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334022C51L10-15UL.jpg{/dede:img}",310,1262);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/1334022C603440-1E2T.jpg",1264,1350);
$z[8][4]['name']="litpic";

?>