<?php
$z[0]=Array("field","美女",0,45);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美女Action",47,101);
$z[1][4]['name']="description";
$z[2]=Array("field","美女Action",103,151);
$z[2][4]['name']="title";
$z[3]=Array("field","",153,192);
$z[3][4]['name']="writer";
$z[4]=Array("field","",194,233);
$z[4][4]['name']="source";
$z[5]=Array("field","",235,275);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",277,314);
$z[6][4]['name']="body";
$z[7]=Array("field","",316,355);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423c34FX0-2393c.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423c35534Z-241494.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423c3625450-253637.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423c3F0540-2C312.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423c3LX40-2G361.jpg{/dede:img}",357,1040);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423c34FX0-2393c_lit.jpg",1042,1131);
$z[9][4]['name']="litpic";

?>