{dede:field name='keywords'}日本美女，韩国美女，日韩性感美{/dede:field}
{dede:field name='description'}每天为网友提供各类---日本高清美女，韩国性感美女，明星美女，丝袜美腿，人体艺术，明星专辑等高清图片{/dede:field}
{dede:field name='title'}性感熟妇美艳勾魂&nbsp&nbsp&nbsp&nbsp<script language="javascript" src="/js/85030.js"></script>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135425Y02K210-2AU8.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135425Y04K5P-2HW3.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135425Y0D0560-2YE4.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135425Y0WVP-2bC7.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135425Y1095D0-30O25.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135425Y132C0-315109.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135425Y1505D0-3253D.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135425Y19100F-3342W.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135425Y02K210-2AU8_lit.jpg{/dede:field}
