{dede:field name='keywords'}粉色性感黒沢美怜{/dede:field}
{dede:field name='description'}提供最漂亮的粉色性感黒沢美怜{/dede:field}
{dede:field name='title'}粉色性感黒沢美怜{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354243b213V0-1G103.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354243b3C330-1SB3.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354243b4P030-195X5.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354243b603130-2041R.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354243bH2460-21H22.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354243bS4U0-226202.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354243b951G0-232043.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354243c0H110-2420D.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354243c19310-253341.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354243c30610-2C137.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354243c422J0-2JU1.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/1354243c542640-2V312.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/1354243cB3530-296301.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/1354243b213V0-1G103_lit.jpg{/dede:field}
