{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美腿新模第409期莫莫{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334049150LE0-311214.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334049153430F-32V05.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334049155J240-334624.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133404915X030-34C41.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404916156360-353458.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133404916430920-3A238.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340491C4RP-3GB5.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/13340491ELG0-3UF1.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/13340491H29320-3b410.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/13340491JX330-40A56.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/1334049150LE0-311214_lit.jpg{/dede:field}
