<?php
$z[0]=Array("field","亲切,,",0,47);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",49,93);
$z[1][4]['name']="description";
$z[2]=Array("field","亲切的笑脸",95,143);
$z[2][4]['name']="title";
$z[3]=Array("field","",145,184);
$z[3][4]['name']="writer";
$z[4]=Array("field","",186,225);
$z[4][4]['name']="source";
$z[5]=Array("field","",227,267);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",269,306);
$z[6][4]['name']="body";
$z[7]=Array("field","",308,347);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/13542391F114Z-1N302.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542391G02950-1R296.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/13542391G92R0-1a295.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/13542391HP510-204401.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542391I552F-213419.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542391J34Z-225064.jpg{/dede:img}",349,1125);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/13542391F114Z-1N302_lit.jpg",1127,1217);
$z[9][4]['name']="litpic";

?>