{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423Z954W20-51H07.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423Z96194F-524217.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423Z9C0050-534096.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423Za25K0-5420S.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423Zaa620-556263.jpg{/dede:img}