{dede:field name='keywords'}嫩模Dabora{/dede:field}
{dede:field name='description'}14岁巴西嫩模Dabora 疑似仙女落凡尘{/dede:field}
{dede:field name='title'}14岁巴西嫩模Dabora 疑似仙女落凡尘{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133404334326310-1UR.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340433445TF-2S44.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334043345952P-31c9.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133404334B9150-4c14.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133404334N61F-5H48.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133404334W24P-A211.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/13340433493A50-G524.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/13340433510B0-WA4.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/1334043352M2P-91630.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/1334043353Ha0-101J0.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133404335445Q0-112b3.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133404335559410-12HD.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133404335E0A0-139260.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133404335T2E0-145291.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/13340433602V60-15LA.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/1334043361QC0-1615N.jpg{/dede:field}
