{dede:field name='keywords'}国际数码互动娱乐展览会{/dede:field}
{dede:field name='description'}提供最漂亮的国际数码互动娱乐展览会{/dede:field}
{dede:field name='title'}国际数码互动娱乐展览会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405319340a0-105460.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133405319563F-1154G.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/13340540254b10-135W.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133405402HF50-2E17.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133405402915H0-3A28.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334054030D130-43302.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133405403310B0-55619.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334054035N30-62442.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133405403Ka0-JB7.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133405403Z3c0-W595.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/1334054040WF-935X.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133405404231V0-109111.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133405404424350-116047.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/1334054045961Z-124436.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133405404M13P-132311.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133405404935Y0-14S33.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/133405405154310-1560B.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/133405405361910-1B056.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133405319340a0-105460_lit.jpg{/dede:field}
