{dede:field name='keywords'}12岁超嫩模爆红网络,曾获越南模{/dede:field}
{dede:field name='description'}美桌图片库提供12岁超嫩模爆红网络 曾获越南模特大赛冠军。{/dede:field}
{dede:field name='title'}12岁超嫩模爆红网络 曾获越南模特大赛冠军{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A42a2E0-41O35.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A42c2a0-425419.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A43015010-434504.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A43026360-44P12.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c130311/13629A42a2E0-41O35_lit.jpg{/dede:field}
