<?php
$z[0]=Array("field","12岁超嫩模爆红网络,曾获越南模",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供12岁超嫩模爆红网络 曾获越南模特大赛冠军。",72,171);
$z[1][4]['name']="description";
$z[2]=Array("field","12岁超嫩模爆红网络 曾获越南模特大赛冠军",173,250);
$z[2][4]['name']="title";
$z[3]=Array("field","",252,291);
$z[3][4]['name']="writer";
$z[4]=Array("field","",293,332);
$z[4][4]['name']="source";
$z[5]=Array("field","",334,374);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",376,413);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A42a2E0-41O35.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A42c2a0-425419.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A43015010-434504.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A43026360-44P12.jpg{/dede:img}",415,1008);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A42a2E0-41O35_lit.jpg",1010,1099);
$z[8][4]['name']="litpic";

?>