<?php
$z[0]=Array("field","性感美女,美女私房,美女,内衣美",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",72,116);
$z[1][4]['name']="description";
$z[2]=Array("field","爱丽丝内衣秀",118,168);
$z[2][4]['name']="title";
$z[3]=Array("field","",170,209);
$z[3][4]['name']="writer";
$z[4]=Array("field","",211,250);
$z[4][4]['name']="source";
$z[5]=Array("field","",252,292);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",294,331);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2UZ9C430-301509.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2U91102440-31U40.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2U9120G40-3250N.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2U913IA0-33H32.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2U91GUF-342E0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2U91T01P-35K57.jpg{/dede:img}",333,1097);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2UZ9C430-301509_lit.jpg",1099,1188);
$z[8][4]['name']="litpic";

?>