{dede:field name='keywords'}自拍,气质,美的,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}超美的气质靓女小沁甜美自拍{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424055136120-3T949.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135424055193050-3b096.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135424055240240-4061X.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424055292T0-412V7.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/13542405534HF-42QX.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354240553Z3F-43TQ.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424055432420-44W33.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354240554K230-45O11.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/13542405551X30-464052.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/135424055560H0-4L148.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/13542405560A60-4X3F.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/135424055A2930-4aO5.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/135424055E9540-50T16.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/135424055J24Z-51H32.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/135424055L5O0-521c6.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/135424055P3340-534093.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c121130/135424055TE10-54RY.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c121130/135424055XC10-553518.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c121130/135424055941E0-5C4W.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c121130/1354240560034Z-5JR0.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c121130/135424056040a0-5WC1.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c121130/1354240560U950-5aa4.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c121130/135424056120640-603361.jpg{/dede:img}
{dede:img ddimg='' text='图 24'}/uploads/allimg/c121130/135424056164340-611V1.jpg{/dede:img}
{dede:img ddimg='' text='图 25'}/uploads/allimg/c121130/13542405620PP-621243.jpg{/dede:img}
{dede:img ddimg='' text='图 26'}/uploads/allimg/c121130/135424056253940-6395X.jpg{/dede:img}
{dede:img ddimg='' text='图 27'}/uploads/allimg/c121130/1354240562a020-644A5.jpg{/dede:img}
{dede:img ddimg='' text='图 28'}/uploads/allimg/c121130/13542405634X40-A3426.jpg{/dede:img}
{dede:img ddimg='' text='图 29'}/uploads/allimg/c121130/135424056403E0-B4326.jpg{/dede:img}
{dede:img ddimg='' text='图 30'}/uploads/allimg/c121130/135424055136120-3T949.jpg{/dede:img}
{dede:img ddimg='' text='图 31'}/uploads/allimg/c121130/135424055193050-3b096.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135424055136120-3T949_lit.jpg{/dede:field}
