<?php
$z[0]=Array("field",",",0,42);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",44,88);
$z[1][4]['name']="description";
$z[2]=Array("field","花神美境小龙女",90,142);
$z[2][4]['name']="title";
$z[3]=Array("field","",144,183);
$z[3][4]['name']="writer";
$z[4]=Array("field","",185,224);
$z[4][4]['name']="source";
$z[5]=Array("field","",226,266);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",268,305);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/1334022JDWF-113Y1.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/1334022JN54F-125296.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/1334022JW0460-1354a.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334022Ja14Z-14MI.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334022K0a230-15O58.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/1334022K1942Z-1612I.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/1334022K2b130-1KS3.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334022K424S0-1U318.jpg{/dede:img}",307,1257);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c120410/1334022K51Y50-194b8.jpg",1259,1345);
$z[8][4]['name']="litpic";

?>