{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403E5115520-11L126.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403E52520F-11Y621.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403E5305Y0-11920L.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403E5413010-1209102.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403E551R20-121KV.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403E5631210-122BA.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403E5H03Z-123C23.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403E5R3N0-1245628.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133403E591F20-1256145.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133403E60530F-1261I4.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133403E61412F-12MC2.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133403E620220-12XX4.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133403E6341I0-12912b.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133403E643X50-13041G.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133403EB04420-1315095.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133403EB5A20-132NO.jpg{/dede:img}