<?php
$z[0]=Array("field","美女,美女图片,性感美女,私房",0,68);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",70,114);
$z[1][4]['name']="description";
$z[2]=Array("field","吻痕",116,158);
$z[2][4]['name']="title";
$z[3]=Array("field","",160,199);
$z[3][4]['name']="writer";
$z[4]=Array("field","",201,240);
$z[4][4]['name']="source";
$z[5]=Array("field","",242,282);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",284,321);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2aYV140-2133a.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2aY923210-22DN.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2aYb3G0-239491.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2aZ032010-241264.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2aZ100520-25O56.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2aZ160520-2E019.jpg{/dede:img}",323,1087);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2aYV140-2133a_lit.jpg",1089,1176);
$z[8][4]['name']="litpic";

?>