{dede:field name='keywords'}韩国美女模特秀春装{/dede:field}
{dede:field name='description'}提供最漂亮的韩国美女模特秀春装{/dede:field}
{dede:field name='title'}韩国美女模特秀春装{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133405454912960-1Z48.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/13340545501050-23194.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133405455101G0-36332.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/1334054551b910-4Q40.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/1334054552Y3P-5I54.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133405455391020-C4W.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133405455491T0-J164.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/1334054555D040-T325.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133405455B01F-914a.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133405455JS20-10S52.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133405454912960-1Z48_lit.jpg{/dede:field}
