{dede:field name='keywords'}生活,四月,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}2010年四月第1期生活美女照片{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403D6060350-405016.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403D61Hb0-411514.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403D62MM0-425096.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403D63B230-432T7.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403D6450a0-44HV.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403DA10M0-451552.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403DAQ1Z-4D046.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403DB5b60-4L910.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133403DC55940-4T936.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133403DDE5F-4934V.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133403DE332F-5042B.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133403DEcX0-512425.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133403DF56020-526351.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133403DG253P-53c05.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133403DH04310-541049.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133403DHN460-554334.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/133403DIZ460-5A2O.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/133403DK03310-5H0I.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c120410/133403DKE2P-5Q616.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c120410/133403DL643P-5a3R.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c120410/133403DM64140-603055.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c120410/133403DNBD0-616354.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c120410/133403DO3R0-62A60.jpg{/dede:img}
{dede:img ddimg='' text='图 24'}/uploads/allimg/c120410/133403DP291Z-63Q07.jpg{/dede:img}
{dede:img ddimg='' text='图 25'}/uploads/allimg/c120410/133403DQ05050-643b9.jpg{/dede:img}
{dede:img ddimg='' text='图 26'}/uploads/allimg/c120410/133403DR353P-A2191.jpg{/dede:img}
{dede:img ddimg='' text='图 27'}/uploads/allimg/c120410/133403DS10420-BJ23.jpg{/dede:img}
{dede:img ddimg='' text='图 28'}/uploads/allimg/c120410/133403DT24360-C63N.jpg{/dede:img}
{dede:img ddimg='' text='图 29'}/uploads/allimg/c120410/133403DU40O0-D1231.jpg{/dede:img}
{dede:img ddimg='' text='图 30'}/uploads/allimg/c120410/133403DV3T30-EA12.jpg{/dede:img}
{dede:img ddimg='' text='图 31'}/uploads/allimg/c120410/133403DWF1Z-FS40.jpg{/dede:img}
{dede:img ddimg='' text='图 32'}/uploads/allimg/c120410/133403DXFa0-G4P1.jpg{/dede:img}
{dede:img ddimg='' text='图 33'}/uploads/allimg/c120410/133403DY434Z-HAQ.jpg{/dede:img}
{dede:img ddimg='' text='图 34'}/uploads/allimg/c120410/133403DZ2P30-Ib17.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133403D91A410-J6326.jpg{/dede:field}
