<?php
$z[0]=Array("field","俄罗斯美女",0,51);
$z[0][4]['name']="keywords";
$z[1]=Array("field","俄罗斯美女俏皮可爱，彩绘半透明内衣创意十足。",53,141);
$z[1][4]['name']="description";
$z[2]=Array("field","俄罗斯美女俏皮可爱",143,199);
$z[2][4]['name']="title";
$z[3]=Array("field","",201,240);
$z[3][4]['name']="writer";
$z[4]=Array("field","",242,281);
$z[4][4]['name']="source";
$z[5]=Array("field","",283,323);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",325,362);
$z[6][4]['name']="body";
$z[7]=Array("field","",364,403);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423X95b440-35GG.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423X9642240-3C605.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423X9D33P-3OW5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423Xa23560-3W910.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423Xa433P-3940Y.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423XaWH0-404941.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423Xb164P-4164b.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423Xb510F-424142.jpg{/dede:img}",405,1355);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423X95b440-35GG_lit.jpg",1357,1446);
$z[9][4]['name']="litpic";

?>