<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","校花李岩西绝美诱惑组图",89,149);
$z[2][4]['name']="title";
$z[3]=Array("field","",151,190);
$z[3][4]['name']="writer";
$z[4]=Array("field","",192,231);
$z[4][4]['name']="source";
$z[5]=Array("field","",233,273);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",275,312);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2W95Q5950-141W.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2W95SA50-2MN.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2W95Z2950-3YV.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2W95943L0-43C0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2W9604E60-545T.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2W96060460-E950.jpg{/dede:img}",314,1073);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2W95Q5950-141W_lit.jpg",1075,1163);
$z[8][4]['name']="litpic";

?>