{dede:noteinfo notename="Çå´¿ö¦Àö" channelid="2" macthtype="string"
    refurl="http://www.mn123.net/qingchunliangli/" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.mn123.net/qingchunliangli/list_2_(*).html"
startid="1" endid="2" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="main_column">{/dede:areastart}
    {dede:areaend}</div>{/dede:areaend}
{/dede:listrule}
