<?php
$z[0]=Array("field","性感美女,美女私房,美女",0,63);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",65,109);
$z[1][4]['name']="description";
$z[2]=Array("field","魅惑滋味入心入肺",111,165);
$z[2][4]['name']="title";
$z[3]=Array("field","",167,206);
$z[3][4]['name']="writer";
$z[4]=Array("field","",208,247);
$z[4][4]['name']="source";
$z[5]=Array("field","",249,289);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",291,328);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2a913R5Z-N413.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2a9152G0-VE8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2a9160360-b305.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2a91T9120-10I56.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2a91Z1520-11K52.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2a91cb30-124G9.jpg{/dede:img}",330,1090);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2a913R5Z-N413_lit.jpg",1092,1179);
$z[8][4]['name']="litpic";

?>