{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354240KPF20-5RX0.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354240KX13F-592925.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354240K9B2P-605940.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354240L0500Z-615922.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354240L122420-622195.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354240L1c130-634119.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354240L244250-64H17.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354240L301E0-AD57.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354240L3B4P-BD02.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354240L420910-Ca01.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354240L4I310-D5309.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/1354240L53D40-EKN.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/1354240L6041Z-F9148.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/1354240LE62P-GQ26.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/1354240LK0050-H9418.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/1354240LP2960-I10Q.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c121130/1354240LX0X0-J2436.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c121130/1354240L93PF-K4R8.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c121130/1354240M02CZ-LX23.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c121130/1354240M0LO0-M13b.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c121130/1354240M14P50-N9196.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c121130/1354240M234050-OW06.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c121130/1354240M2ZH0-P4c9.jpg{/dede:img}
{dede:img ddimg='' text='图 24'}/uploads/allimg/c121130/1354240M3641Z-Q4509.jpg{/dede:img}