{dede:field name='keywords'}写真,生活,美女,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}美空美女生活写真{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120410/133403E05c420-K9607.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120410/133403E0GL40-L3W7.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120410/133403E0P03F-M4313.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120410/133403E0W5940-N5243.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120410/133403E09CD0-Ob30.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120410/133403E10543F-P6340.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120410/133403E11521Z-QN57.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120410/133403E1221420-R6022.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120410/133403E12WP-S2L1.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120410/133403E13IY0-TI44.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c120410/133403E14C960-Ua44.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c120410/133403E15K350-V2453.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c120410/133403E1B92Z-W2007.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c120410/133403E1LJF-X1431.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c120410/133403E1VQP-YY12.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c120410/133403E1a240-Z4K4.jpg{/dede:img}
{dede:img ddimg='' text='图 17'}/uploads/allimg/c120410/133403E2054950-919517.jpg{/dede:img}
{dede:img ddimg='' text='图 18'}/uploads/allimg/c120410/133403E21Q450-92E50.jpg{/dede:img}
{dede:img ddimg='' text='图 19'}/uploads/allimg/c120410/133403E22DH0-9313H.jpg{/dede:img}
{dede:img ddimg='' text='图 20'}/uploads/allimg/c120410/133403E2341S0-945524.jpg{/dede:img}
{dede:img ddimg='' text='图 21'}/uploads/allimg/c120410/133403E242460-955U8.jpg{/dede:img}
{dede:img ddimg='' text='图 22'}/uploads/allimg/c120410/133403E2500910-962925.jpg{/dede:img}
{dede:img ddimg='' text='图 23'}/uploads/allimg/c120410/133403E25XW0-a4334.jpg{/dede:img}
{dede:img ddimg='' text='图 24'}/uploads/allimg/c120410/133403E2CZ40-bJ23.jpg{/dede:img}
{dede:img ddimg='' text='图 25'}/uploads/allimg/c120410/133403E2L3260-cBS.jpg{/dede:img}
{dede:img ddimg='' text='图 26'}/uploads/allimg/c120410/133403E2SO20-1002V0.jpg{/dede:img}
{dede:img ddimg='' text='图 27'}/uploads/allimg/c120410/133403E2Z5450-101TG.jpg{/dede:img}
{dede:img ddimg='' text='图 28'}/uploads/allimg/c120410/133403E2b1130-102M46.jpg{/dede:img}
{dede:img ddimg='' text='图 29'}/uploads/allimg/c120410/133403E3055c0-1031435.jpg{/dede:img}
{dede:img ddimg='' text='图 30'}/uploads/allimg/c120410/133403E3144J0-1045107.jpg{/dede:img}
{dede:img ddimg='' text='图 31'}/uploads/allimg/c120410/133403E3222Y0-1059221.jpg{/dede:img}
{dede:img ddimg='' text='图 32'}/uploads/allimg/c120410/133403E3291Z-10C459.jpg{/dede:img}
{dede:img ddimg='' text='图 33'}/uploads/allimg/c120410/133403E33G30-10H192.jpg{/dede:img}
{dede:img ddimg='' text='图 34'}/uploads/allimg/c120410/133403E34511P-10T940.jpg{/dede:img}
{dede:img ddimg='' text='图 35'}/uploads/allimg/c120410/133403E3555A0-1092B5.jpg{/dede:img}
{dede:img ddimg='' text='图 36'}/uploads/allimg/c120410/133403E362X30-1105Y1.jpg{/dede:img}
{dede:img ddimg='' text='图 37'}/uploads/allimg/c120410/133403E3F5160-111W02.jpg{/dede:img}
{dede:img ddimg='' text='图 38'}/uploads/allimg/c120410/133403E3M61Z-11241P.jpg{/dede:img}
{dede:img ddimg='' text='图 39'}/uploads/allimg/c120410/133403E3VQP-113D26.jpg{/dede:img}
{dede:img ddimg='' text='图 40'}/uploads/allimg/c120410/133403E3935250-11432I.jpg{/dede:img}
{dede:img ddimg='' text='图 41'}/uploads/allimg/c120410/133403E41Y610-1151948.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120410/133403E42P630-1163J9.jpg{/dede:field}
