{dede:field name='keywords'}女孩,快乐,,{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}快乐女孩{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423913T9360-3L607.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/13542391392440-3T4T.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354239140111P-39AN.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354239140S420-402354.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354239141K520-41c22.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423914251450-423E8.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423914325540-43NA.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423914401920-44H09.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354239144H420-45a24.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/13542391455M20-462315.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/135423914634Q0-4M0b.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/135423914EA50-4Q403.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/135423914K310-493Q3.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/135423914PC60-50J44.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/135423914X5920-51T08.jpg{/dede:img}
{dede:img ddimg='' text='图 16'}/uploads/allimg/c121130/135423914aLZ-52L48.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135423913T9360-3L607_lit.jpg{/dede:field}
