{dede:field name='keywords'}周秀娜师妹写真{/dede:field}
{dede:field name='description'}香港嫩模何佩瑜及余晓彤是香港某选秀节目选出的香港“新8模”的成员。两人于7月11日正式推出个人写真集，写真集尺度大胆勾魂，不逊师姐周秀娜。{/dede:field}
{dede:field name='title'}周秀娜师妹喷血写真集{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135424005026330-3XM5.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354240050M240-391D7.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135424005130G0-405202.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354240051G520-41V58.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354240052132F-42c60.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/13542400524a50-439618.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424005293b0-444593.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/13542400534N50-45cP.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/13542400540D0-4D1V.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354240054564Z-4OS0.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/13542400550N0-4Y1N.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/135424005563430-495645.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/135424005604R0-505F2.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/13542400563G40-5113J.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/135424005026330-3XM5_lit.jpg{/dede:field}
