<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","易欣性感写真",89,139);
$z[2][4]['name']="title";
$z[3]=Array("field","",141,180);
$z[3][4]['name']="writer";
$z[4]=Array("field","",182,221);
$z[4][4]['name']="source";
$z[5]=Array("field","",223,263);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",265,302);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='235' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c131124/13U2cL2564F-61Q0.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c131124/13U2cL3131F-Lb4.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c131124/13U2cL4343P-Q960.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c131124/13U2cL5MX0-92132.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c131124/13U2cLA5c0-105b4.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c131124/13U2cLK43Z-11W22.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c131124/13U2cLR5F-12A22.jpg{/dede:img}",304,1145);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c131124/13U2cL2564F-61Q0_lit.jpg",1147,1234);
$z[8][4]['name']="litpic";

?>