<?php
$z[0]=Array("noteinfo","",0,178);
$z[0][4]['notename']="ĞÔ¸ĞÃÀÅ® www.84420.com";
$z[0][4]['channelid']="2";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div class=\"grid_4 imgblock\">{/dede:areastart}\r\n    {dede:areaend}<ul class=\"pagelist\">{/dede:areaend}\r\n",180,630);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.84420.com/xgmn/list_6_(*).html";
$z[1][4]['startid']="1";
$z[1][4]['endid']="4";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="0";
$z[1][4]['usemore']="0";

?>