<?php
$z[0]=Array("field","恋上街拍的女孩-刘子淇",0,62);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美桌图片库提供恋上街拍的女孩-刘子淇。",64,145);
$z[1][4]['name']="description";
$z[2]=Array("field","恋上街拍的女孩-刘子淇",147,206);
$z[2][4]['name']="title";
$z[3]=Array("field","",208,247);
$z[3][4]['name']="writer";
$z[4]=Array("field","",249,288);
$z[4][4]['name']="source";
$z[5]=Array("field","",290,330);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",332,369);
$z[6][4]['name']="body";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='170' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c130311/13629A2F54F-193312.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c130311/13629A2FbJ0-201337.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c130311/13629A2G3KZ-219494.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c130311/13629A2GS940-225355.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c130311/13629A2H360-235611.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c130311/13629A2HWB0-24AI.jpg{/dede:img}",371,1137);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c130311/13629A2F54F-193312_lit.jpg",1139,1228);
$z[8][4]['name']="litpic";

?>