<?php
$z[0]=Array("field","日本美女新垣结衣",0,57);
$z[0][4]['name']="keywords";
$z[1]=Array("field","提供最漂亮的日本美女新垣结衣",59,131);
$z[1][4]['name']="description";
$z[2]=Array("field","日本美女新垣结衣",133,187);
$z[2][4]['name']="title";
$z[3]=Array("field","",189,228);
$z[3][4]['name']="writer";
$z[4]=Array("field","",230,269);
$z[4][4]['name']="source";
$z[5]=Array("field","",271,311);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",313,350);
$z[6][4]['name']="body";
$z[7]=Array("field","",352,391);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354244053N950-Y016.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354244054U020-c0D.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354244055MU0-101107.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135424405B92Z-1114E.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135424405M2N0-122040.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135424405V4020-132F5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135424405a0050-1432H.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135424406051010-15P50.jpg{/dede:img}",393,1353);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/1354244053N950-Y016_lit.jpg",1355,1445);
$z[9][4]['name']="litpic";

?>