<li class="l">
      	<div class="recommend"></div>
        <div class="picbox"><img data-original="[field:first_imgurl function='thumb(@me,490,350)'/]" alt="[field:fulltitle/]" width="490" height="350" />
          <div><b><a target="_blank" href="[field:arcurl/]"></a></b></div>
        </div>
        <div class="name"><a target="_blank" href="[field:arcurl/]" title="[field:fulltitle/]">[field:title/]</a></div>
      </li>