{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}时尚野性张亚凯{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/13341225A05X0-413L1.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/13341225B95960-42Z91.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/13341225DGV0-4313D.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/13341225F32T0-44c27.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/13341225H9EZ-455095.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/13341225KB3Z-463I4.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/13341225N2UZ-4OE8.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/13341225P53S0-4QV2.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/13341225R41N0-495543.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120411/13341225TF910-50S12.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/13341225A05X0-413L1_lit.jpg{/dede:field}
