{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}阳光女孩谢洛颐{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c120411/1334122AA14Z-10G05.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c120411/1334122AVLP-11Y96.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c120411/1334122B094340-12D47.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c120411/1334122B296260-131614.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c120411/1334122B51B50-146026.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c120411/1334122BKKP-152957.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c120411/1334122Bb0V0-1A063.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c120411/1334122C205F-1M556.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c120411/1334122C4333P-1U547.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c120411/1334122CA6140-1a560.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c120411/1334122AA14Z-10G05_lit.jpg{/dede:field}
