<?php
$z[0]=Array("field","呂婉柔",0,47);
$z[0][4]['name']="keywords";
$z[1]=Array("field","国内嫩模吕婉柔在香港和台湾宣传2011最新写真《Love ME》，曝光的一组写真中吕婉柔真空上阵不设防，与汪小菲的火辣短信内容、手机接二连三丢失等炒作不断之下，人气已有所暴涨。",49,258);
$z[1][4]['name']="description";
$z[2]=Array("field","呂婉柔新写真集美图曝光",260,320);
$z[2][4]['name']="title";
$z[3]=Array("field","",322,361);
$z[3][4]['name']="writer";
$z[4]=Array("field","",363,402);
$z[4][4]['name']="source";
$z[5]=Array("field","",404,444);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",446,483);
$z[6][4]['name']="body";
$z[7]=Array("field","",485,524);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423a53221Z-313B7.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423a53L310-32GN.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423a5413960-336003.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423a545aP-34G55.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423a54aE0-35H44.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423a55322P-3E3M.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423a55U160-3IM8.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423a5615130-3T160.jpg{/dede:img}",526,1479);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423a53221Z-313B7_lit.jpg",1481,1571);
$z[9][4]['name']="litpic";

?>