{dede:field name='keywords'}干露露全新写真{/dede:field}
{dede:field name='description'}话题女星干露露近日曝光一组家居写真。写真中干露露挑战自己大胆露酥胸，上演熟女极限诱惑。{/dede:field}
{dede:field name='title'}话题女王干露露全新写真{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='imgurl'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/1354241X421250-1L3S.jpg{/dede:img}
{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/1354241X463M0-1YF2.jpg{/dede:img}
{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/1354241X504910-192614.jpg{/dede:img}
{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/1354241X541G0-206229.jpg{/dede:img}
{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/1354241X5M520-211551.jpg{/dede:img}
{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/1354241X61020-221318.jpg{/dede:img}
{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/1354241X643120-2340L.jpg{/dede:img}
{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/1354241XD4P-24M92.jpg{/dede:img}
{dede:img ddimg='' text='图 9'}/uploads/allimg/c121130/1354241XH3120-251V6.jpg{/dede:img}
{dede:img ddimg='' text='图 10'}/uploads/allimg/c121130/1354241XLIZ-262E9.jpg{/dede:img}
{dede:img ddimg='' text='图 11'}/uploads/allimg/c121130/1354241XPDP-2M208.jpg{/dede:img}
{dede:img ddimg='' text='图 12'}/uploads/allimg/c121130/1354241XSP-2V510.jpg{/dede:img}
{dede:img ddimg='' text='图 13'}/uploads/allimg/c121130/1354241XWJP-29D92.jpg{/dede:img}
{dede:img ddimg='' text='图 14'}/uploads/allimg/c121130/1354241X920430-30YJ.jpg{/dede:img}
{dede:img ddimg='' text='图 15'}/uploads/allimg/c121130/1354241X960c0-31P02.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c121130/1354241X421250-1L3S_lit.jpg{/dede:field}
