<?php
$z[0]=Array("field","日本女生",0,49);
$z[0][4]['name']="keywords";
$z[1]=Array("field","漂亮日本女生",51,107);
$z[1][4]['name']="description";
$z[2]=Array("field","漂亮日本女生",109,159);
$z[2][4]['name']="title";
$z[3]=Array("field","",161,200);
$z[3][4]['name']="writer";
$z[4]=Array("field","",202,241);
$z[4][4]['name']="source";
$z[5]=Array("field","",243,283);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",285,322);
$z[6][4]['name']="body";
$z[7]=Array("field","",324,363);
$z[7][4]['name']="imgurl";
$z[8]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='150' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}\r\n{dede:img ddimg='' text='图 1'}/uploads/allimg/c121130/135423c1334450-140A.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 2'}/uploads/allimg/c121130/135423c144D0-26259.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 3'}/uploads/allimg/c121130/135423c1530O0-35V5.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 4'}/uploads/allimg/c121130/135423c16313P-421G.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 5'}/uploads/allimg/c121130/135423c1HT40-59107.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 6'}/uploads/allimg/c121130/135423c1S4210-A918.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 7'}/uploads/allimg/c121130/135423c191PF-I541.jpg{/dede:img}\r\n{dede:img ddimg='' text='图 8'}/uploads/allimg/c121130/135423c1b0960-Q946.jpg{/dede:img}",365,1312);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","/uploads/allimg/c121130/135423c1334450-140A_lit.jpg",1314,1404);
$z[9][4]['name']="litpic";

?>