<?php
$z[0]=Array("global","",50,77);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",112,139);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",178,205);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",244,271);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",310,337);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",372,399);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("channel","<a href='[field:typeurl/]' target='_blank'>[field:typename/]</a>",409,522);
$z[6][4]['type']="top";
$z[6][4]['row']="10";
$z[7]=Array("global","",531,557);
$z[7][4]['name']="cfg_powerby";

?>