<?php
$z[0]=Array("global","",72,100);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",112,140);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",194,220);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",321,349);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]\"[field:id runphp='yes']@me=(@me=='8'?' target=\"_blank\"':'');[/field:id]>[field:typename/]</a></li>\r\n      <li class='line'></li>\r\n      ",404,723);
$z[4][4]['type']="top";
$z[4][4]['row']="9";
$z[4][4]['currentstyle']="<li class='hover'><a href='~typelink~'>~typename~</a></li><li class='line'></li>";

?>