<?php
$z[0]=Array("global","",79,107);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",118,144);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",146,172);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",199,224);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("tag","<a href=\"[field:link/]\" target=\"_blank\">[field:tag /]</a> ",683,793);
$z[4][4]['row']="4";
$z[4][4]['getall']="1";
$z[4][4]['sort']="rand";
$z[5]=Array("global","",833,861);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",1178,1206);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("channel","\r\n          <li><a href='[field:typeurl/]' target='_blank'>[field:typename/]</a></li>\r\n          ",1247,1481);
$z[7][4]['type']="top";
$z[7][4]['row']="10";
$z[7][4]['currentstyle']="<li><a class='cur' href='~typelink~' target='_blank'>~typename~</a></li>";
$z[8]=Array("global","",1562,1584);
$z[8][4]['name']="cfg_url";
$z[9]=Array("global","",1603,1629);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("global","",1869,1896);
$z[10][4]['name']="cfg_basehost";
$z[11]=Array("global","",1973,2000);
$z[11][4]['name']="cfg_basehost";
$z[12]=Array("global","",2818,2845);
$z[12][4]['name']="cfg_basehost";
$z[13]=Array("global","",2864,2891);
$z[13][4]['name']="cfg_basehost";

?>