<?php
$z[0]=Array("global","",47,74);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",86,113);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",248,275);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("channel","      	\r\n      <li><a href='[field:typeurl/]' target=\"_blank\"> [field:rel/]<span>[field:typename/]</span></a></li>",298,554);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>