<?php
$z[0]=Array("global","",79,104);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",132,158);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",185,210);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",1229,1254);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n          <li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n          ",1296,1541);
$z[4][4]['type']="top";
$z[4][4]['row']="10";
$z[4][4]['currentstyle']="<li><a class='cur' href='~typelink~' ~rel~>~typename~</a></li>";

?>