<?php
$z[0]=Array("global","",66,92);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",165,192);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",201,227);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",240,266);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",297,325);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]\"[field:id runphp='yes']@me=(@me=='8'?' target=\"_blank\"':'');[/field:id]>[field:typename/]</a></li>\r\n      ",717,984);
$z[5][4]['type']="top";
$z[5][4]['row']="9";
$z[5][4]['currentstyle']="<li><a class='active' href='~typelink~'>~typename~</a></li>";

?>