<?php
$z[0]=Array("field","",370,389);
$z[0][4]['name']="title";
$z[1]=Array("global","",390,416);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",457,486);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",526,584);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",865,902);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("type","\r\n<a href=\"[field:typelink /]\"><b>[field:typename /]</b></a>\r\n",947,1032);
$z[6]=Array("list","\r\n<li><a href='view.php?aid=[field:id/]'><img src=\"[field:litpic/] \" alt=\"[field:title/]\"/></a><p><a href='view.php?aid=[field:id/]'>[field:title/]</a></p></li>\r\n",1156,1370);
$z[6][4]['titlelen']="30";
$z[6][4]['pagesize']="20";
$z[7]=Array("type","\r\n<li><a href=\"[field:typelink /]\">Ê×Ò³</a></li>\r\n",1418,1491);
$z[8]=Array("pagelist","",1497,1533);
$z[8][4]['listitem']="pre,next,";
$z[9]=Array("include","",1563,1600);
$z[9][4]['filename']="foot_m.htm";

?>