<?php
$z[0]=Array("field","",291,314);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",317,343);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",384,413);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",453,511);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",546,574);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",631,659);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("include","",770,802);
$z[6][4]['filename']="h.htm";
$z[7]=Array("arclist","\r\n        <li> <a target=\"_blank\" href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\"> <img data-original=\"[field:litpic/]\" title=\"[field:fulltitle/]\" /> <span class=\"name\">[field:title/]</span> </a> </li>\r\n        ",1118,1404);
$z[7][4]['row']="6";
$z[7][4]['flag']="c";
$z[7][4]['titlelen']="16";
$z[7][4]['channelid']="2";
$z[8]=Array("field","",1545,1567);
$z[8][4]['name']="typename";
$z[9]=Array("pagelist","",1611,1661);
$z[9][4]['listitem']="info,xxnt";
$z[9][4]['listsize']="1";
$z[10]=Array("list","\r\n      <li> <a target=\"_blank\" href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\"> <img data-original=\"[field:litpic/]\" alt=\"[field:fulltitle/]\" width=\"130\" height=\"170\" /> <span class=\"name\">[field:title/]</span> </a> </li>\r\n      ",1715,1996);
$z[10][4]['pagesize']="24";
$z[10][4]['titlelen']="16";
$z[11]=Array("pagelist","",2033,2089);
$z[11][4]['listitem']="pre,next,pageno";
$z[11][4]['listsize']="5";
$z[12]=Array("include","",2133,2166);
$z[12][4]['filename']="f1.htm";

?>