<?php
$z[0]=Array("field","",332,358);
$z[0][4]['name']="title";
$z[1]=Array("field","",402,434);
$z[1][4]['name']="description";
$z[2]=Array("field","",471,500);
$z[2][4]['name']="keywords";
$z[3]=Array("global","",551,579);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("include","",1695,1732);
$z[4][4]['filename']="header.htm";
$z[5]=Array("arclist","\r\n<li><i>[field:global.autoindex/].</i><a  href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a><em>点击:[field:click/]</em></li>\r\n",1993,2190);
$z[5][4]['row']="10";
$z[5][4]['titlelen']="30";
$z[5][4]['orderby']="click";
$z[6]=Array("arclist","\r\n<li><i>[field:global.autoindex/].</i><a  href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a><em>点击:[field:click/]</em></li>\r\n",2479,2691);
$z[6][4]['row']="10";
$z[6][4]['titlelen']="30";
$z[6][4]['orderby']="hot";
$z[6][4]['subday']="180";
$z[7]=Array("arclist","\r\n<li><a  href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a><em>点击:[field:click/]</em></li>\r\n",2985,3158);
$z[7][4]['row']="22";
$z[7][4]['titlelen']="30";
$z[7][4]['orderby']="click";
$z[7][4]['subday']="2";
$z[8]=Array("arclist","\r\n<li><i>[field:global.autoindex/].</i><a  href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a><em>点击:[field:click/]</em></li>\r\n",3446,3653);
$z[8][4]['row']="10";
$z[8][4]['titlelen']="30";
$z[8][4]['orderby']="click";
$z[8][4]['subday']="30";
$z[9]=Array("arclist","\r\n<li><i>[field:global.autoindex/].</i><a  href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a><em>点击:[field:click/]</em></li>\r\n",3944,4150);
$z[9][4]['row']="10";
$z[9][4]['titlelen']="30";
$z[9][4]['orderby']="click";
$z[9][4]['subday']="7";
$z[10]=Array("include","",4298,4333);
$z[10][4]['filename']="foot.htm";

?>