<?php
$z[0]=Array("global","",262,317);
$z[0][4]['name']="keyword";
$z[0][4]['function']="RemoveXSS(@me)";
$z[1]=Array("global","",365,397);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("include","",534,571);
$z[2][4]['filename']="header.htm";
$z[3]=Array("global","",735,790);
$z[3][4]['name']="keyword";
$z[3][4]['function']="RemoveXSS(@me)";
$z[4]=Array("list","\r\n  <li><a href=\"[field:arcurl/]\" class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\" /><i class=\"tit\">[field:title /]</i><s></s></a></li>\r\n",853,1097);
$z[4][4]['pagesize']="20";
$z[4][4]['perpage']="20";
$z[4][4]['titlelen']="120";
$z[5]=Array("pagelist","",1237,1308);
$z[5][4]['listitem']="info,index,end,pre,next,pageno";
$z[5][4]['listsize']="8";
$z[6]=Array("include","",1433,1468);
$z[6][4]['filename']="foot.htm";

?>